### ISSUE TITLE
How to access the signals on the player objects? (Mpris)

### ISSUE THREAD

**Issue by kidfromjupiter** [Aylur/ags#103]
Adding Mpris service instance itself to connections is pretty straighforward and well documented.  But the docs for `Player` say that it emits a signal for `position` as well. How do I access it? I couldn't find any information on the wiki.

I'm trying to build a progressbar for the current song position

**Comment by kotontrion** [comment]
the syntax for connections is `[Service, callback, signal]`
so something similar to
```js
[player, (slider, position) => slider.value = player.position/player.length, 'position']
```

**Comment by kidfromjupiter** [comment]
```js
ags.Widget({
   type: ProgressBar,
   className: ["progressbar"],
   connections: [
       [
        Mpris.players[0],
        (widget, position) => {
            widget.fraction =
               Mpris.players[0].position / Mpris.players[0].length;
          },
	"position",
        ],
    ],
}),

```

so... this should work fine right? But this results in a `missing arguments to connections` error

**Comment by kotontrion** [comment]
This seem correct.
Are you sure `Mpris.player[0]` is defined?
Keep in mind, that the callback of the connection is also called right after creation, so if you somewhere else have a connection to the Mpris `player-added` signal, that callback will be executed, once right after creation, even if there was no player added.

So make sure the player actually exists before creating the widget. Maye something like:
```js
        [Mpris, (box, busName) => {
            if (!busName)
                return;
            //create player widget
        }, 'player-added']
```

**Comment by Aylur** [comment]
The `position` signal on `Player` only gets emitted when you explicitly set it's value. It is basically only there to have a label in sync when you drag the slider.

Here is an example. These will get the position every second, and the label will also update when you are dragging the slider, so you can see the position as you are dragging.
```js
export const PositionSlider = player => Slider({
    onChange: ({ value }) => {
        player.position = player.length * value;
    },
    properties: [['update', slider => {
        if (slider.dragging)
            return;

        slider.visible = player.length > 0;
        if (player.length > 0)
            slider.value = player.position / player.length;
    }]],
    connections: [
        [player, s => s._update(s), 'position'],
        [1000, s => s._update(s)],
    ],
});

export const PositionLabel = player => Label({
    properties: [['update', label => {
        player.length > 0
            ? label.label = lengthStr(player.position)
            : label.visible = !!player;
    }]],
    connections: [
        [player, l => l._update(l), 'position'],
        [1000, l => l._update(l)],
    ],
});
```
