### ISSUE TITLE
ags cant find GnomeBluetooth

### ISSUE THREAD

**Issue by flick0** [Aylur/ags#105]
![image](https://github.com/Aylur/ags/assets/77581181/14a123a6-7881-48d8-8fd6-bc51fc77968e)

**Comment by fr13ndxd** [comment]
did you install it using paru?

**Comment by Aylur** [comment]
you need `gnome-bluetooth-3.0`, not `gnome-bluetooth` on Arch

**Comment by flick0** [comment]
yep works now, thank
![image](https://github.com/Aylur/ags/assets/77581181/5d07f997-8c02-4c5e-b585-e7a59f565d71)

**Comment by kotontrion** [comment]
> (also shudnt it be installed as a dependancy in aur)

yeah, that's on me. I assumed gnome-bluetooth-3.0, upower, networkmanager, and dbusmenu-gtk3 aren't needed if the corresponding services are not used, so I've put them as optional dependencies. Should have checked that better.

fixed now.
