### ISSUE TITLE
Make dependencies for services optional

### ISSUE THREAD

**Issue by Frontear** [Aylur/ags#107]
One big example is Bluetooth service demands `gnome-bluetooth-3.0`. I've disabled my bluetooth on my laptop and don't use any bluetooth services/packages, yet ags will not let me run if I do not install this package, because I guess when I import services it imports Bluetooth as well which requires the bluetooth libs.

If possible, please make these optional. NetworkManager is another good one, some people use systemd-networkd, others use something else etc, and may not depend on the network service or make their own via `Variable`. Would just be a nice QoL thing

**Comment by Aylur** [comment]
there could be a `disableServices` option, gjs can do toplevel async imports so it should be just a few lines to do this this

**Comment by Frontear** [comment]
If its possible, perhaps have a check if the imports exists, and if they dont, stderr a message stating the service will not run. I dont really know much about js or gjs to know if thats possible, but I think that would be preferable to manually needing to disable
