### ISSUE TITLE
GJS Error

### ISSUE THREAD

**Issue by SwadowMaster** [Aylur/ags#112]
HEllo i am trying to install AGS but i ahve this erro 
![image](https://github.com/Aylur/ags/assets/72133740/130f6200-e2c6-4ae2-996c-097eb7d8d61d)

**Comment by HiImJulien** [comment]
This error means, that the GJS version, which you have installed on your system is outdated. You need at least version `1.73.1` to be installed.

**Comment by SwadowMaster** [comment]
Im try to update but the version dont change any suggestion?

**Comment by Frontear** [comment]
How are you "trying" to update

**Comment by Aylur** [comment]
Based on your terminal colors I assume you are on some version of Ubuntu that has not updated `gjs` in it's repos yet. You could update your distro, or get the package from somewhere else

**Comment by SwadowMaster** [comment]
Yes, i update my distro and its work but now i have this error  
![image](https://github.com/Aylur/ags/assets/72133740/2ca52a5f-3177-4371-89f7-d64f6342144a)

**Comment by Aylur** [comment]
You need `node-typescript` https://github.com/Aylur/ags/wiki/installation#from-source

**Comment by SwadowMaster** [comment]
Apt install node-typescript throug me an erro but i can install it with npm i -g typescript and its works!! thanks for help^
