### ISSUE TITLE
AGS style.css will not load an OTF font

### ISSUE THREAD

**Issue by Frontear** [Aylur/ags#117]
This might be some issue on my PC but I can't for my life figure out what is happening.

Downloaded `apple-fonts` from the AUR, checked fontname via `fc-list` (it was SF Mono), set my font-family to "SF Mono", reload AGS, and.. nothing. AGS doesn't seem to load it, no errors in console either.

I know this _USED_ to work, because I used to do this in my dotfiles, but for whatever reason on a fresh system install it will just not work at all. It will load a different font, Symbols Nerd Font, which is also OTF, but idk. Any ideas what could be happening here?

Minimal CSS file which reproduces it:

```style.scss
@mixin text($fontFamily, $fontSize) {
    min-width: ($fontSize / 2) * 3;
    font-size: $fontSize;
    font-family: $fontFamily;
}

.text {
    @include text("SF Mono", 16px);
}
```

EDIT: How do I know its not loading? Because when I remove the font declaration, the font style and appearance remains the same, so I know for a fact its not loading, or falling back to something else.

**Comment by Aylur** [comment]
does the font show up in the inspector's visual tab? `ags inspector`
