### ISSUE TITLE
Offline build (Gentoo)

### ISSUE THREAD

**Issue by xoores** [Aylur/ags#122]
Hi,

I would like to create an ebuild so Gentoo users can install AGS. But the installation process has to be offline as the whole build is done in an isolated sandbox with no internet access.

Is there any way to "skip" `npm install`? Perhaps git submodules in repo or something similar?

Thanks

**Comment by Aylur** [comment]
Would packing the `node_modules` with the releases help?

**Comment by xoores** [comment]
I think yes - I can certainly try if you could perhaps send me an archive with those :)

**Comment by bearcatsandor** [comment]
Hey @xoores, which overlay will this ebuild be in, and what will the ebuild be called? Thank you very much for your work on this.

**Comment by xoores** [comment]
Hi @bearcatsandor, it is in [my overlay right here](https://github.com/xoores/gentoo-overlay/blob/main/gui-apps/ags/ags-1.3.0.ebuild) :slightly_smiling_face: 

I just noticed that I have a license wrong - I will fix that, but that will not prevent it from building of course :slightly_smiling_face:

**Comment by bearcatsandor** [comment]
The downloaded source file is failing it's checksum.

**Comment by kotontrion** [comment]
There are 3 ways to include the node_modules in the release:

1. include node_modules in the ags-version.tar.gz
2. have a separate node_modules.tar.gz
3. have a ags-version.tar.gz without node and a ags-version-with-node.tar.gz including the node_modules

Most people won't need the node_modules, so I personally would prefer the second or third option.

@xoores I updated the github action to include the node modules in the release using the second option over at my fork and created a release there, so you can test it.

**Comment by xoores** [comment]
@kotontrion All options are perfectly viable for this :slightly_smiling_face: And option 2 and 3 sounds good. I will update ebuild for your fork when I get home.

I edited that with sed because the target path is `com.github.Aylur.ags` and I did not want to hardcode that into an ebuild. I also did not want to change any buildpaths since I had some problems getting everything to compile and I did not really want to introduce another variable into the process.

@bearcatsandor Yeah, it fails because this repo does not have that file. You will either have to create it yourself or wait a few hours and I will create an ebuild that will use Kotontrions fork that has these files already baked in :slightly_smiling_face:

**Comment by Aylur** [comment]
the libdir was `lib/$pkgname` at first (and still should be), thats where gnome installs `gvc` too, but I changed it to `lib` so that there is no need for a patch using nix. I didn't know about `--libdir` option for meson, but that should definitely solve the conflict.
You might want to close the issue about this on `gvc`'s gitlab because they state it in their readme that its meant to be used as a sub-module

@kotontrion could you make a PR with the updated github action? would appriciate it, I will tag a 1.4 release after this issue is resolved

also let me know what installation guide I should put on the wiki for Gentoo

**Comment by kotontrion** [comment]
> @kotontrion could you make a PR with the updated github action? would appriciate it, I will tag a 1.4 release after this issue is resolved

Done.
I initially wanted to wait for xoores to confirm that this solves the issue first.

**Comment by xoores** [comment]
> > @kotontrion could you make a PR with the updated github action? would appriciate it, I will tag a 1.4 release after this issue is resolved
> 
> Done. I initially wanted to wait for xoores to confirm that this solves the issue first.

Works like a charm! :+1:

**Comment by xoores** [comment]
Also @kotontrion how did you mean that --libdir while I'm at it? I cannot really pass `lib/${pkgname}` as pkgname (or rather Gentoo's equivalent `${PN}`) is `ags`. And this will try to force install the lib into `usr/lib/libgvc.so` - which will fail.

In the Meson.build there is an `app_id = 'com.github.Aylur.ags'` and I would have to hardcode that into an ebuild or grep it from the Meson.build - which seems much worse than simple sed-ding that file :slightly_smiling_face:

**Comment by xoores** [comment]
@bearcatsandor I just pushed ebuild that uses that repo @kotontrion made :slightly_smiling_face: 

You can pull it [from here](https://github.com/xoores/gentoo-overlay/blob/main/gui-apps/ags/ags-1.3.1.ebuild) and test it out.

**Comment by bearcatsandor** [comment]
Tna kyou so much folks! I have it installed and I'm busy theming!

**Comment by Aylur** [comment]
@xoores I released 1.4.0 with node_modules

**Comment by xoores** [comment]
Working: 

```
ags --version
1.4.0
```

For Gentoo users you could add something like "Ebuilds for Portage are in [Xoores' overlay](https://github.com/xoores/gentoo-overlay/tree/main/gui-apps/ags)" to the Howto :slightly_smiling_face: 

Thanks for this, I'm currently fighting with notifications and CSS as I'm creating my own shell. And something has changed from 1.3.0 because I'm getting undefined around `Hyprland.active.workspace`. :grin:

**Comment by Aylur** [comment]
>For Gentoo users you could add something like "Ebuilds for Portage are in [Xoores' overlay](https://github.com/xoores/gentoo-overlay/tree/main/gui-apps/ags)" to the Howto 🙂

I've never used Gentoo, so I assume it would be enough to put this into the wiki as users will know what to do with it, but I would rather put exact commands on the wiki to make it clear, so what are the exact commands to get it installed?

**Comment by xoores** [comment]
I will try and add my repo to official Overlay list and then there will be a few commands on how to do it :-) I'll keep you posted - for now it is quite dependant on how any particular Gentoo user has set up his/her overlays.

Btw when I compile the 1.4 I get quite a lot "undefined" globals such as Hyprland etc... Did anything change? When I switch back to 1.3 (without touching that config) it works again...

**Comment by Aylur** [comment]
>I will try and add my repo to official Overlay list and then there will be a few commands on how to do it :-) I'll keep you posted - for now it is quite dependant on how any particular Gentoo user has set up his/her overlays.

Sound great

> Btw when I compile the 1.4 I get quite a lot "undefined" globals such as Hyprland etc... Did anything change? When I switch back to 1.3 (without touching that config) it works again...

the `ags` global got removed in 1.4.0, so you can't do `ags.Service.Hyprland` anymore, refer to the wiki on how to import them

**Comment by xoores** [comment]
I'm importing it like this (basically taken from your example/dotfiles) so I would say I was not doing it :sweat_smile: 

```js
const resource = file => `resource:///com/github/Aylur/ags/${file}.js`;
const require = async file => (await import(resource(file))).default;
const service = async file => (await require(`service/${file}`)).instance;

const Hyprland = await service('hyprland');
export const Widget = await require('widget');
export const Utils = await import(resource('utils'));
```
