### ISSUE TITLE
Audio.speaker.isMuted is not changing state when muting audio.

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/ags#123]
After a recent update, Audio.speaker.isMuted does not change its state when speaker is muted.

**Comment by matt1432** [comment]
You need to use `Audio.speaker.stream.isMuted` now. 

`Audio.speaker.isMuted` will only be true when the volume is at 0

**Comment by Aylur** [comment]
the actual `is-muted` property through `gvc` doesn't seem to be writable, so the `Stream` object's `is-muted` property returns whether the volume is 0 or not, and writing it just sets the volume to 0, it still signals when the actual `is-muted`property changes, but you need to read `Stream.stream.is-muted` for that. if you want to keep it consistent with `pavucontrol`for example you should only read `Stream.stream.is-muted` and use another tool like `pactl` to mute/unmute
its a temporary solution untill someone figures out how to write the `is-muted` property through `gvc`

**Comment by PoSayDone** [comment]
@matt1432, @Aylur thanks, closing
