### ISSUE TITLE
App launcher list of applications refresh

### ISSUE THREAD

**Issue by cafetestrest** [Aylur/ags#126]
Hi, can someone tell me is there ability to create app launcher list of applications refresh upon installation of the new app?
Also I'm wandering is there ability to run a command upon a PC's return from sleep - what I have in mind, refresh weather information?

**Comment by Aylur** [comment]
running `update-desktop-database` updates it I think. on NixOS it comes from the `desktop-file-utils` package, I am not sure for other distros, on Fedora it might be preinstalled

or you could do
```bash
ags --run-promise "
  import('resource:///com/github/Aylur/ags/service/applications.js')
    .then(m => resolve(m.default._sync()))
"
```

as for your second question, it is the job of the compositor, if you are using Hyprland check out how to [bind switches](https://wiki.hyprland.org/Configuring/Binds/#switches)
