### ISSUE TITLE
[Request] more examples

### ISSUE THREAD

**Issue by killown** [Aylur/ags#133]
can you create an example for a custom menu like this https://extensions.gnome.org/extension/4295/custom-menu-panel/
it would be great also to have an example to redirect a command output in a top panel bar

**Comment by Aylur** [comment]
>can you create an example for a custom menu like this https://extensions.gnome.org/extension/4295/custom-menu-panel/

a custom menu like that is currently not doable, because Gtk.Popover is broken, but on gtk4 it will work as expected
you can however make a window, position in to a corner, and use a button as a toggler

> it would be great also to have an example to redirect a command output in a top panel bar
you can use `Utils.exec` or `Utils.execAsync`, the example bar includes this with the date

**Comment by killown** [comment]
Thank you man!
