### ISSUE TITLE
Notifications example: Can't display images if appIcon is a path

### ISSUE THREAD

**Issue by varris1** [Aylur/ags#134]
mpDris2 is unable to display cover art because it provides a path (file:///tmp/cover-[SOMETHING].jpg) to the cover image. 

appIcon uses the function lookUpIcon which is null when supplied with a path, resulting in the default icon (dialog-information-symbolic) instead of the expected cover image.

**Comment by Aylur** [comment]
does this modification work?
```js
// ...
import GLib from 'gi://GLib';

const NotificationIcon = ({ appEntry, appIcon, image }) => {
    if (GLib.file_test(appIcon, GLib.FileTest.EXISTS))
        image = appIcon;

    if (image) {
        return Widget.Box({
// ...
```

**Comment by varris1** [comment]
> does this modification work?

Sadly not. With your example, the cover image is still not displayed. Also it seems that the condition is not true because my console.log line does not output anything:

```
if (GLib.file_test(appIcon, GLib.FileTest.EXISTS)) {
        image = appIcon;
        console.log(image);
}
```

This ugly hack seems to work but it feels, really, really wrong:

```
let icon = 'dialog-information-symbolic';

if(lookUpIcon(appIcon) || appIcon)
  icon = appIcon.replace(/^(file\:\/\/)/, "");
```

**Comment by Aylur** [comment]
GLib.file_test doesn't handle the `file://` prefix, which makes sense because it can only take a file path
It's worth a try to open up an issue on mpDris2, because most if not all notification clients will send image data in binary format as metadata, the icon is usually preserved for named icons

**Comment by Aylur** [comment]
fixed it at the notification daemon level, paths with a file:/// prefix will now be passed as image
