### ISSUE TITLE
Mpris incorrect length

### ISSUE THREAD

**Issue by ByteAtATime** [Aylur/ags#135]
Hi there, so I was creating a media control using the Mpris service. However, the length of the file I was playing seemed to be wrong. In an 18 minute video, it shows up as 120 seconds. From some digging, I believe the culprit is the following line:

https://github.com/Aylur/ags/blob/main/src/service/mpris.ts#L165

It's getting only the first 3 digits, but this doesn't work if the file is over 999 seconds (about 16-17 minutes). Did you mean to divide this by `1_000_000`?

**Comment by Aylur** [comment]
I don't even remember why I used a substring, thank you for pointing it out
