### ISSUE TITLE
Audio service "isMuted" doesn't work as intended

### ISSUE THREAD

**Issue by webflo-dev** [Aylur/ags#141]
Hello!

The audio service provides a “isMuted” property, this one is based on volume. Sadly, it seems that this check is not reliable. On my PC, muting the audio doesn't change the volume. The connection is still called, but the service property is always “false” for “isMuted”.

Is there another way to check if an audio device is muted (speaker and microphone)?

For information, I'm using Hyprland with pipewire, and the audio is controlled with pulsemixer or pactl.

**Comment by PoSayDone** [comment]
duplicate of #123

**Comment by webflo-dev** [comment]
Thanks! I missed that information!
