### ISSUE TITLE
[Mpris] How to get the current player?

### ISSUE THREAD

**Issue by webflo-dev** [Aylur/ags#142]
In the case of multiple players, I would like to get the most recently active player. Is it possible to get it with the Mpris service?

For example, I have player A and player B that appeared. I set "play" on player A, it's the active player. Then I set "play" on player B, now it should be the new active player.
With AGS and Mpris service, how can I use connection or bind to react to those changes?

**Comment by Aylur** [comment]
you can connect to Services outside of widgets, so you can set up a listener like this
```js
let active;
Mpris.connect('player-added', (mpris, bus) => {
    mpris.getPlayer(bus)?.connect('changed', player => {
        active = player;
    });
});

function getActive() {
    return active || Mpris.players[0] || null;
}
```
