### ISSUE TITLE
Error when execute ags

### ISSUE THREAD

**Issue by spigatl** [Aylur/ags#143]
**This my code.**

`// Import
import { App, Utils } from './imports.js';
// Windows
import { Bar } from './windows/bar.js';
import { Cheatsheet } from './windows/cheatsheet.js';
import { CornerTopleft, CornerTopright, CornerBottomleft, CornerBottomright } from './windows/corners.js';
import { Indicator } from './windows/osd.js';
import { Osk } from './windows/osk.js';
import { Overview } from './windows/overview.js';
import { Session } from './windows/session.js';
import { SideLeft } from './windows/sideleft.js';
import { SideRight } from './windows/sideright.js';

const CLOSE_ANIM_TIME = 150;

// SCSS compilation
Utils.exec(`sassc ${App.configDir}/scss/main.scss ${App.configDir}/style.css`);
App.resetCss();
App.applyCss(`${App.configDir}/style.css`);

// Config object
export default {
    style: `${App.configDir}/style.css`,
    stackTraceOnError: true,
    closeWindowDelay: {
        // For animations
        'sideright': CLOSE_ANIM_TIME,
        'sideleft': CLOSE_ANIM_TIME,
        'osk': CLOSE_ANIM_TIME,
        // No anims, but allow menu service update
        'session': 1,
        'overview': 1,
        'cheatsheet': 1,
    },
    windows: [
        Bar(),
        CornerTopleft(),
        CornerTopright(),
        CornerBottomleft(),
        CornerBottomright(),
        Overview(),
        Indicator(),
        Cheatsheet(),
        SideRight(),
        SideLeft(),
        Osk(), // On-screen keyboard
        Session(),
    ],
};
`

**and this my error**

`(ags:55999): Gtk-WARNING **: 14:49:58.714: Theme parsing error: gtk.css:6703:68: Invalid name of pseudo-class

(ags:55999): Gjs-WARNING **: 14:49:58.741: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/emilioduarte/.config/ags/config.js:2:0

(ags:55999): Gjs-WARNING **: 14:49:58.741: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/emilioduarte/.config/ags/config.js:2:0
Gjs-Message: 14:49:58.741: JS LOG: ERROR: No config was provided or there was an error

(ags:55999): Gjs-WARNING **: 14:49:58.741: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/emilioduarte/.config/ags/config.js:2:0`

**Comment by Aylur** [comment]
your config.js doesn't really help
you have a css error, and some import error, I can't help you without seeing the whole config

**Comment by spigatl** [comment]
hum.... thx. i will try fix this css erros.

**Comment by varris1** [comment]
The CSS error is a bug in the gruvbox GTK theme stylesheet: https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/issues/43
