### ISSUE TITLE
Doc mismatch with code for Mpris and Audio

### ISSUE THREAD

**Issue by jerrywcy** [Aylur/ags#145]
In wiki for [Mpris](https://github.com/Aylur/ags/wiki/Mpris), property includes `trackArtists`. However in code it is named `track_artists`. 

see https://github.com/Aylur/ags/blob/e98c6446e6f4cbbc94edd97073f8c2b1dd753f99/src/service/mpris.ts#L62

Similar problems applied for Audio.

Which one should I use?

**Comment by Aylur** [comment]
both are valid, you can even do `player['track-artists']`, see at the bottom of https://github.com/Aylur/ags/wiki/service
will update the wiki to make it more clear

**Comment by Aylur** [comment]
copy pasted from a comment I made on Discord

>I am going back and forth on how to name properties, because when using binds you have to use kebab-case
but anywhere else you can use kebab-case, camelCase or snake_case, so in the case of a Stream as an example
>```js
>const stream = Audio.microphone
>stream.is_muted
>stream.isMuted
>stream['is-muted']
>
>//or even
>stream['is_muted']
>stream['isMuted']
>```
>this is because gobject properties are using kebab-case internally because they are a string, but gjs sets up all three getters and setters
>also if you have a look at the gjs docs, properties are also written in kebab-case there
