### ISSUE TITLE
Hyprland Active Workspace Clients

### ISSUE THREAD

**Issue by sl33nyc** [Aylur/ags#147]
I'm running the mainline `ags` and tried the following:
```
const computeActiveApps = (self) => {
    self.children = Hyprland.clients
        .filter(client => client.workspace.id === Hyprland.active.workspace.id)
        .map(client => Widget.Button({
            child: Widget.Icon({
                className: 'appicon',
                icon: client.initialClass
            }),
            properties: [
                ['address', client.address],
            ],
        }));
};

const Apps = () => Widget.Box({
    connections: [
        [Hyprland, computeActiveApps],
    ],
});
```

Launching new clients correctly adds icons to my `Apps` widget, but closing the clients doesn't seem to trigger the `client-removed`.  If I switch workspaces, the widget correctly updates.

**Comment by Aylur** [comment]
I honestly have no idea why this was happening, maybe a race condition

**Comment by sl33nyc** [comment]
I just tried out your commit, and it looks like it fixes my issue.  Thanks!
