### ISSUE TITLE
nix flake with gtk4

### ISSUE THREAD

**Issue by Aylur** [Aylur/ags#15]
Hey @dongsu8142
I want to migrate to Gtk4, but `gtk4-layer-shell` is not packaged on nixpkgs. Is a flake still possible?
I could make everything work on Fedora by placing the .typelib and .so file in the correct path. On Arch `gtk4-layer-shell` is packaged on the AUR, and It works without tweaking. I have no idea how this works on Nix though

**Comment by dongsu8142** [comment]
You can use it by waiting for gtk4-layer-shell to be added to nixpkgs, or by adding it directly to nixpkgs, or by adding gtk4-layer-shell to nur.

**Comment by rydymth** [comment]
Does that mean that i can use gtk4 css if i installed gtk4-layer-shell from aur?
