### ISSUE TITLE
setTimeout not returning id

### ISSUE THREAD

**Issue by sl33nyc** [Aylur/ags#150]
I would attempt to fix the following myself, but I haven't had bandwidth to read through the code and understand how it works (yet).  Anyway, I have the following `Widget.Window`:
```
const MyFancyWindow = () => Widget.Window({
    name: 'fancy-window',
    child: Widget.Revealer({
        revealChild: true,
        transitionDuration: 2000,
        transition: 'crossfade',
        setup: self => {
            self.properties = [
                ['fadeOut', setTimeout(() => self.revealChild = false, 2000)],
            ];
            console.log(self._fadeOut); // FIXME should not be undefined
        },
    ...
});
```

The crossfade works, but the expected `id` returned by `setTimeout` is not set as a property.  Hence, if I want to prevent the timeout action from being triggered before 2000ms elapses, I cannot later call `clearTimeout`.  If this is a bug, then I suspect that `setInterval`'s return value is also being dropped.

**Comment by Aylur** [comment]
`properties` is not actually settable outside of the constructor, what you are doing here is literally setting revealer.properties to `[['fadeOut', id: number]]`, you can confirm by running `console.log(self.properties)` in the setup.

 currently it just silently happens, next version it will just throw an error
 but you don't need properties outside of the constructer when you have a reference to the widget e.g like in `setup`, you can just set `_fadeOut` on self directly
 ```js
setup: self => {
  self._fadeOut = setTimeout(() => self.revealChild = false, 2000);
  console.log(self._fadeOut); // the id
}
 ```

**Comment by sl33nyc** [comment]
Got it.  Thanks for the clarification.
