### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by nousername33** [Aylur/ags#152]
Like in eww, would it be possible to allow assigning namespaces to widgets? It would allow the compositor to apply compositing to the widget, and allows more feature-parity with eww.

**Comment by Aylur** [comment]
the `name` passed to windows is the layername

**Comment by Aylur** [comment]
updated the wiki https://github.com/Aylur/ags/wiki/Basic-Widgets#window

**Comment by nousername33** [comment]
Thanks for clearing this up :)
