### ISSUE TITLE
Example bar doesn't work on Asahi Linux

### ISSUE THREAD

**Issue by sahinakkaya** [Aylur/ags#154]
I am on Asahi Linux (a project which aims to port Linux to Apple Silicon devices). I have installed `ags` with `yay`:

`yay -S aylurs-gtk-shell`

When I try to use [example bar](https://github.com/Aylur/ags/tree/main/example/simple-bar) config from the repo, it gives me the following error:
```
(com.github.Aylur.ags:40190): Gjs-Console-CRITICAL **: 01:31:51.015: Error: Requiring DbusmenuGtk3, version none: Typelib file for namespace 'DbusmenuGtk3' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://DbusmenuGtk3:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

I tried searching for the specified package but couldn't find anything to install. What should I do?

My system information:
```
OS: Arch Linux ARM aarch64
Host: Apple MacBook Pro (14-inch, M2 Pro, 2023)
Kernel: 6.5.0-asahi-15-1-edge-ARCH
```

**Comment by Aylur** [comment]
the package you are looking for is `libdbusmenu-gtk3` on Arch, maybe there is an issue with it on Asahi?

**Comment by sahinakkaya** [comment]
It is fixed after installing it. I couldn't find the package myself as it didn't autocomplete :man_facepalming:

**Comment by paladhammika** [comment]
Encountering the same message as OP on NixOS. It doesn't seem that `libdbusmenu-gtk3` is a dependency in the [source](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ag/ags/package.nix#L68) for `ags` in `nixpkgs`. 

However, when I run ` nix run github:Aylur/ags` the example config opens up as it should.

**Comment by nonetrix** [comment]
I am having this on Nix as well

**Comment by paladhammika** [comment]
> I am having this on Nix as well, this issue seems related [NixOS/nixpkgs#306446](https://github.com/NixOS/nixpkgs/issues/306446)

Be sure to use the flake and the homeManagerModule. That fixed things for me.
