### ISSUE TITLE
CSS is not loaded properly on Asahi Linux

### ISSUE THREAD

**Issue by sahinakkaya** [Aylur/ags#157]
Ok, this is probably a problem related with my system (Asahi Linux) because I am experiencing the same issue on `eww` too. I wanted to try `ags` to see if this one will work but CSS files are not loading properly for me. All I see is a white bar at the top.

![ags](https://github.com/Aylur/ags/assets/32161460/65b4cc8c-c0ad-419a-8df8-3ce5f88baef1)

I don't think it is supposed to look this way. I am opening this issue just for the sake of reporting it. If it is because something broken on my system, I completely understand.

```
OS: Arch Linux ARM aarch64
Host: Apple MacBook Pro (14-inch, M2 Pro, 2023)
Kernel: 6.5.0-asahi-15-1-edge-ARCH
```

**Comment by Aylur** [comment]
It is loaded, you can see the font color beeing blue, but I think the example bar assumes you have dark gtk theme set

**Comment by sahinakkaya** [comment]
OK, this is embarrassing. 2 issues in the last 12 hours and both of them were very easy to fix :man_facepalming: Sorry for wasting your time.
