### ISSUE TITLE
nix flake type lib does not exist

### ISSUE THREAD

**Issue by isabelroses** [Aylur/ags#16]
When I use ags with nix as a flake i get the warning:
```
** (ags:296756): WARNING **: 11:46:12.888: Failed to load shared library '/nix/store/xcskqs03w7nbpl7mb22prk27xq74n3jb-ags-1.0.0/lib/libgvc.so' referenced by the typelib: /nix/store/xcskqs03w7nbpl7mb22prk27xq74n3jb-ags-1.0.0/lib/libgvc.so: cannot open shared object file: No such file or directory
```
I checked the given path, and i found that the library is under `/nix/store/xcskqs03w7nbpl7mb22prk27xq74n3jb-ags-1.0.0/lib/ags/libgvc.so` which leads to the error.

So this leads me to believe the [`lib-patch`](https://github.com/Aylur/ags/blob/main/nix/lib-path.patch) is the cause of the error.

**Comment by cafetestrest** [comment]
Hey @isabelroses, the same thing happens to me as well with nixos 23.05.
Version that is working for me is ags hash https://github.com/Aylur/ags/commit/5d313e11b061b428c208f201a8cfbb475fd66b08
Anything after it is failing to me.

**Comment by dongsu8142** [comment]
I don't know what's affecting the build. I am using the unstable version

**Comment by isabelroses** [comment]
> I don't know what's affecting the build. I am using the unstable version

Yeah im on unstable too, but all i can figure would be the lib patch

**Comment by wizardwatch** [comment]
The error goes away if one removes the volume widget of the simple config. I am on nixos unstable. Also worth noting is that I had to add execAsync to the const = ags.Utils section to make the workspaces work.

**Comment by dongsu8142** [comment]
I am constantly thinking about how to solve this problem

**Comment by musjj** [comment]
I actually tried removing the patch, but I still get the same error.
