### ISSUE TITLE
not working aylurs-gtk-shell-git-v1.4.0.r3.gc7b2607-1

### ISSUE THREAD

**Issue by killown** [Aylur/ags#164]
(com.github.Aylur.ags:12277): Gtk-WARNING **: 01:47:55.902: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class

(com.github.Aylur.ags:12277): Gjs-Console-WARNING **: 01:47:56.338: Calling Widget({ type }) is deprecated. Use Widget.subclass instead, or open up an issue/PR to include Gtk_Separator on Widget

(com.github.Aylur.ags:12277): Gjs-Console-CRITICAL **: 01:47:56.338: Error: Invalid value 'undefined' for property connections in object initializer.
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:10:12
Widget@resource:///com/github/Aylur/ags/widget.js:50:12
default@file:///home/neo/.config/ags/js/misc/Separator.js:4:70
SeparatorDot@file:///home/neo/.config/ags/js/bar/TopBar.js:29:55
Start@file:///home/neo/.config/ags/js/bar/TopBar.js:41:9
default@file:///home/neo/.config/ags/js/bar/TopBar.js:98:22
forMonitors/<@file:///home/neo/.config/ags/js/utils.js:11:32
forMonitors@file:///home/neo/.config/ags/js/utils.js:11:15
@file:///home/neo/.config/ags/config.js:31:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
Error: "failed to open image: No such file or directory (os error 2)"

(com.github.Aylur.ags:12277): Gjs-WARNING **: 01:47:56.340: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by killown** [comment]
1.4.0 working fine, git version, not

**Comment by Aylur** [comment]
There were some breaking changes (again)
You should use `Widget.Separator` now instead
