### ISSUE TITLE
Mpris getting an error when trying to cache cover art

### ISSUE THREAD

**Issue by JakeTompkins** [Aylur/ags#165]
I'm using the bar from the examples directory and most of it is working fine except for this portion. I'm not sure what kind of diagnostics I can give you to make debugging easier, but let me know what you'll need and I'll get it to you ASAP. The error is below:

`Gio.IOErrorEnum: Operation not supported
_cacheCoverArt/<@resource:///com/github/Aylur/ags/service/mpris.js:152:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

**Comment by Aylur** [comment]
is `gvfs` installed on your system?

**Comment by JakeTompkins** [comment]
> is `gvfs` installed on your system?

It looks like it is not. Let me install quickly and see if that does it
