### ISSUE TITLE
Add metadata change signal to Mpris service

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/ags#170]
It would be cool to be able to monitor track changes specifically, rather than all player changes.

**Comment by Aylur** [comment]
it was missing from the docs, but you can connect to `notify::trackid` signal on a Player

**Comment by PoSayDone** [comment]
Okie, closing.

**Comment by PoSayDone** [comment]
could I ask for some help?
i'm trying to connect to track change like this:
```
const id = Mpris.connect('player-changed', (MprisObj, busName) => {
	this._mprisPlayer = Mpris.getPlayer(busName);
	this._mprisPlayer.connect('notify::trackid', () => {
		console.log(this._mprisPlayer._trackid);
		Utils.execAsync(`python ${App.configDir}/bin/getCoverColors ${this._mprisPlayer.coverPath}`)
			.then(commandString => {
				this._colors.set(busName, JSON.parse(commandString));
				this._coverPaths.set(busName, this._mprisPlayer.coverPath);
				this.emit('changed');
			})
			.catch(() => { });
	});
```
but that what I have in console:
![image](https://github.com/Aylur/ags/assets/29358657/5523dd99-2bbc-4f4b-8ed1-5fc18379bd8e)
Am I doing something wrong?
