### ISSUE TITLE
Duplicated access points

### ISSUE THREAD

**Issue by zoriya** [Aylur/ags#173]
When we have multiples access point for the same SSID (like a public Wi-Fi with multiples routers or a 2.5Ghz and a 5Ghz network with the same SSID), the access point is returned multiples times. I don't think this is by design, but it makes the network list unusable when there are many duplicates. Example:

![image](https://github.com/Aylur/ags/assets/32224410/2f3f98a7-1546-470c-9d18-8085f5c8bfe2)

I don't know if simply filtering to make SSIDs uniques is the correct way to handle this.

**Comment by matt1432** [comment]
I had the same issue and was wondering the same thing

**Comment by Aylur** [comment]
It is by design because they are two separate access point objects in `NM`, a filter on the array should be a sensible solution.
