### ISSUE TITLE
Add pointer cursor on button hover

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/ags#175]
For now only possible way to have pointer cursor on button hover is to use this function on setup
```javascript
export function setupCursorHover(button) {
    const display = Gdk.Display.get_default();
    button.connect('enter-notify-event', () => {
        const cursor = Gdk.Cursor.new_from_name(display, 'pointer');
        button.get_window().set_cursor(cursor);
    });

    button.connect('leave-notify-event', () => {
        const cursor = Gdk.Cursor.new_from_name(display, 'default');
        button.get_window().set_cursor(cursor);
    });
}
```

**Comment by PoSayDone** [comment]
It's possible to add this in button widget like this, but maybe the better way Is to add property `cursor` with union type of all cursor values from https://docs.gtk.org/gdk3/ctor.Cursor.new_from_name.html in base widget and set it with `pointer` for button and slider by default.
![image](https://github.com/Aylur/ags/assets/29358657/2989cc34-fee5-4249-96f1-b672436209bb)

**Comment by Aylur** [comment]
it is available on all widgets, although it won't work for some, Label for example
