### ISSUE TITLE
how to make blur background

### ISSUE THREAD

**Issue by SuceV587** [Aylur/ags#179]
hyprland blur configure not work on ags window ;

how can make a blur background for ags window???

**Comment by PoSayDone** [comment]
Use blurls option with your ags window name
example:
```
decoration{
    blurls=notifications
}
```

If you want rounded corners not to be blurred, use the layerrule ignorealpha option
example:
```
layerrule=ignorealpha[0.97],notifications
```

**Comment by SuceV587** [comment]
@PoSayDone 

It works for me . Thanks very much.

**Comment by AdsonCicilioti** [comment]
Hi @Aylur, I've set the some window name on hyprland `blurls` but blur ins't blurred yet.
![image](https://github.com/Aylur/ags/assets/6278398/22e73985-35c5-4032-b3ce-e49870e664b5)
![image](https://github.com/Aylur/ags/assets/6278398/a3265f56-1ac5-459a-aaab-c70c6b20c08f)
![image](https://github.com/Aylur/ags/assets/6278398/e8ec260d-5ec7-4f7d-8ff3-b7dbcb36bddb)

I'm using your dotfiles on NixOS Flakes.

**Comment by Aylur** [comment]
They should be already blurred, you can find the code in `js/setup/hyprland.js`

**Comment by AdsonCicilioti** [comment]
> They should be already blurred, you can find the code in `js/setup/hyprland.js`

 Really... I found this function in `js/settings/hyprland.js`:
 ![image](https://github.com/Aylur/ags/assets/6278398/57e2dc81-b615-4669-8541-f62202d5cdc8)

 But I don't know why it's not working.  But I'll make some edits and try to understand better. 

 I really liked the possibility of creating a theme via widget inputs dynamically, but I'm not sure if I want to control some aspects of Hyprland.  But yes it is an excellent demonstration.

**Comment by Aylur** [comment]
even if you have styles set in your config, this will overwrite them at runtime with hyprctl calls
try removing the first if statement, maybe you you have your /tmp persist between boots

**Comment by AdsonCicilioti** [comment]
Right!
 Really... Everything works without this init state marking logic.
 It's a very personal thing to want this, but after all, these are your dotfiles, and it's up to me to adjust.  Thanks for helping me with this.

 In my case, as I'm starting to experiment with `ags`, I still tinker a lot with my file `~/.config/hypr/hyprland.conf`, and every time I change hyprland it reloads and cleans the ags injections via ` hyprctl`.
 I know you chose to do everything for `ags` via `hyprctl`, but I believe that a dynamically generated file would be the best of both worlds.
 hyprland settings file allows you to embed a second file.  I will try to implement some initial logic.  If you can and want to leave your comments to help me in the process.

**Comment by Aylur** [comment]
I do this so the `hyprland.conf` file is fully seperate and there is no need to edit it, this what makes sense to me, because I use `home-manager`, but I understand why you would want to generate a file and import it instead. I would just edit both `hyprlandInit` and `setupHyprland` methods to generate a file in `~/.cache` and import them in `hyprland.conf`

**Comment by AdsonCicilioti** [comment]
> I do this so the `hyprland.conf` file is fully seperate and there is no need to edit it, this what makes sense to me, because I use `home-manager`, but I understand why you would want to generate a file and import it instead. I would just edit both `hyprlandInit` and `setupHyprland` methods to generate a file in `~/.cache` and import them in `hyprland.conf`

Cool!..
It's great to be able to use both approaches... I also use home-manager and after I started using flakes, the `config.lib.file.mkOutOfStoreSymlink` function no longer works like it did in traditional mode, as flakes creates a separate package in the `store`.  In other words, I no longer have hyprland hot-reloading when editing its `conf` file.  Thank you for your clarifications and considerations.  Soon I hope to collaborate with `ags`. Cya!
