### ISSUE TITLE
Setting exclusivity to 'exclusive' or exclusive to true at runtime does not work.

### ISSUE THREAD

**Issue by matt1432** [Aylur/ags#180]
I'm trying to do an exclusivity toggle for a window and it seems like it's not possible to make a window exclusive once it's been initialized. Making it not exclusive works though.

**Comment by Aylur** [comment]
I couldn't reproduce. This one seems to work as expected
```js
import Widget from 'resource:///com/github/Aylur/ags/widget.js';

const win = Widget.Window({
    name: 'asd',
    focusable: true,
    popup: true,
    child: Widget.Box()
})

const entry1 = Widget.Entry({
    placeholder_text: 'anchor',
    on_accept: ({ text }) => win.anchor = JSON.parse(text || '[]'),
})

const entry2 = Widget.Entry({
    placeholder_text: 'exclusivity',
    on_accept: ({ text }) => win.exclusivity = text || 'normal',
})

win.child.children = [
    entry1,
    entry2,
    Widget.Button({
        label: 'print',
        on_clicked: () => print(win.exclusivity, win.anchor)
    })
]

export default { windows: [win] }
```

**Comment by matt1432** [comment]
Have you tried it without `focusable: true` ?

**Comment by matt1432** [comment]
That's not the issue nevermind that. I don't know what the problem is because your thing was working but mine isn't.

**Comment by matt1432** [comment]
Is there any reason why this wouldn't be working?
```js
App.getWindow('osk').exclusivity = App.getWindow('osk').exclusivity === 'normal' ? 'exclusive' : 'normal';
```

**Comment by matt1432** [comment]
This is an issue on my side, apparently, not fixed yet but I doubt it is an issue with ags directly

**Comment by Aylur** [comment]
if you run getWindow synchronously on startup it won't return the window, because the config object that contains the reference isn't loaded yet
