### ISSUE TITLE
Laggy transitions

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/ags#184]
Hi, I have this issue: 
If I use transitions on windows with a large number of widgets, window opening animations are incredibly laggy, but the window closing animations don't lag.
This problem does not occur on windows with a small number of widgets, such as OSD.
Also this problem does not show up on my full hd monitor, but only on my laptop screen, with a resolution of 2880x1800@90.
It does not matter what type of animation to use: crossfade or slide, the problem occurs in any case.
I also tried to put the maximum frequency for my GPU, but it did not help much.

**Comment by PoSayDone** [comment]
A video demonstrating the issue:
https://github.com/Aylur/ags/assets/29358657/ed4c3262-ce41-46a4-99d2-05344d3090ae

**Comment by its-darsh** [comment]
what is your system specs and what graphic drivers you're using?

**Comment by PoSayDone** [comment]
> what is your system specs and what graphic drivers you're using?

I7 1360p with IGPU

**Comment by its-darsh** [comment]
> I7 1360p with IGPU
what graphics drivers you're in and what is your hyprland version

**Comment by PoSayDone** [comment]
> > I7 1360p with IGPU
> 
> what graphics drivers you're in and what is your hyprland version

Mesa 23.1.9
Hyprland latest git (646f4bc63861e03b01fed3833bb65d1d014e1bf3)

**Comment by its-darsh** [comment]
> > what graphics drivers you're in and what is your hyprland version
> 
> Mesa 23.1.9 Hyprland latest git (646f4bc63861e03b01fed3833bb65d1d014e1bf3)

downgrading to 0.28.0 fix's that?

**Comment by daUnknownCoder** [comment]
I also have a same issue

[Kooha-2023-11-28-20-49-52.webm](https://github.com/Aylur/ags/assets/84800625/18faf612-c00e-4d79-afd7-2d7c2bb22ad9)

the transitions of workspaces is laggy...
hyprland 0.30.0-1 [pacman]

**Comment by PoSayDone** [comment]
I've tried to disable scaling on my laptop monitor and now animations are buttery smooth.
But when I set my previous scale value (1.8) or 2.0 It's lagging as before.
(my monitor resolution is 2880x1800 if needed)

**Comment by Aylur** [comment]
this might be a limitation with gtk3, not sure what might be causing this

**Comment by daUnknownCoder** [comment]
> I've tried to disable scaling on my laptop monitor and now animations are buttery smooth.

how can we do that?

**Comment by PoSayDone** [comment]
> > > what graphics drivers you're in and what is your hyprland version
> > 
> > 
> > Mesa 23.1.9 Hyprland latest git (646f4bc63861e03b01fed3833bb65d1d014e1bf3)
> 
> downgrading to 0.28.0 fix's that?

can't test, 0.28.0 version not starting on my laptop with:
`[CRITICAL] m_sWLRBackend was NULL!`
