### ISSUE TITLE
Touch Input Inconsistencies / Support

### ISSUE THREAD

**Issue by nine7nine** [Aylur/ags#188]
Touch Input is very inconsistent with AGS.

- For example, I can touch a button in the TopBar to reveal a widget, but once the widget is revealed  I can't unfocus with a click / hide it with touch input... mouse clicks  allow me to click away focus: resulting in the widget disappearing. (eg: with Date/Dashboard, QuickSettings, etc).

- the same is true of clicking a button in the TopBar: with mouse clicks, the second time clicked will hide the widget, but with touch input - it does nothing.

I'm not sure what the solution is here, if there is a way to wrap or mask touch inputs or something like that. -- or if maybe this is a hyprland issue, in part... but it's mildly annoying ;-)

It'd be nice to know if this is a Hyprland or AGS issue though.

**Comment by Aylur** [comment]
I would move this issue to my [dotfiles](https://github.com/Aylur/dotfiles), because this sounds like an issue with how I made my setup (assuming you do use it), but I will leave this here as I am not sure if this is from how the `Window.popup` property works.
I don't have a device with touchscreen, so I can't test it, but how does this behave?
```js
import Widget from 'resource:///com/github/Aylur/ags/widget.js';

const win = Widget.Window({
    name: 'test',
    popup: true,
    visible: true,
    focusable: true,
    child: Widget.Label({
        label: 'tap away',
    }),
    connections: [['button-press-event', (self) => {
        print(self.get_pointer());
    }]],
});

export default { windows: [win] }
```

**Comment by nine7nine** [comment]
Thanks for the response, Aylur.

I'll give this a try later on, when I'm in front of my machine.

Yes, my dotfiles are based on yours - but i had assumed that AGS itself may have required some touch related stuff. but you very well could be right, that it's purely an issue with lacking this support in your dotfiles...

interestingly, the Dock does work fine - if i'm on a empty desktop and the dock is showing, but i touch elsewhere, the dock does hide... So it really just seems to be TopBar & PopUp related.

**Comment by Aylur** [comment]
hmm, the dock shouldn't hide on click away, if the workspace is empty, only if you hover over it and leave the cursor.
I don't know how touch input is handled in Gtk3 or Hyprland, so not sure where the issue is

**Comment by Aylur** [comment]
Gtk4 will solve most issues yeah, in gtk3 touch events are a special thing you have to add on top, while in gtk4 its supported just like mouse and keyboard events
