### ISSUE TITLE
Setting the visible property dynamically

### ISSUE THREAD

**Issue by BigfootN** [Aylur/ags#190]
Hello,

I am trying to set the `visible` attribute of a `Label` dynamically:

This what the `connections` looks like:

```js
connections: [
        [musicStatus, self => {
            if (!musicStatus.value.active) {
                self.children[0].visible = false;
                self.children[1].visible = false;
                return;
            }

            self.children[0].visible = true;
            self.children[1].visible = true;
            self.children[0].label = musicStatus.value.track;
            self.children[1].label = musicStatus.value.artist;
        }]
    ],
```

Here is my `musicStatus`:

```js
const musicStatus = Variable('{ "active": false }', {
    poll: [300, `python ${App.configDir}/scripts/spotify.py`, out => {
        return JSON.parse(out);
    }],
});
```

Unfortunately the `visible` attribute doesn't seem to change anything. The children are always displayed or never.

Thank you very much for any help

**Comment by Aylur** [comment]
Assuming `self.children[0]`and `self.children[1]` is a label widget, and your script returns a json string containing an object that has an active attribute set to true this should work.
Are you sure your script returns what you are expecting it to?

Mind that `musicStatus.value.active` might be undefined first, because the initial value doesn't go through the transform method, meaning its a `string` and not `{ active: boolean }`

**Comment by Aylur** [comment]
this seems like a weird gtk behavior, turns out when you want to set every children invisible, it won't work
```js
const Label = (poll) => Widget.Label({
    label: 'test',
    connections: poll ? [[1000, self => {
        print(self.visible)
        self.visible = !self.visible;
    }]] : [],
})

const win = Widget.Window({
    name: 'test',
    child: Widget.Box({
        children: [
            Label(true),
            Label(true),
            Label(false), // won't work without this dummy label
        ]
    })
})
```

but I can't think of a scenario where this would make sense, you should just hide the container itself

**Comment by BigfootN** [comment]
Should the code you presented work ? I'll try it when I have time.

> you should just hide the container itself

Apart from `visible = false` what do you mean ?

Thank you for your help.

**Comment by BigfootN** [comment]
Thank you I'll try that

**Comment by BigfootN** [comment]
I'm sorry but your example still didn't work.

I even tried to add `self.children[x].visible = true` and still didn't work.

**Comment by Aylur** [comment]
if you add another child to `inner_box` it would probably solve your issue
if you plan on to having it as a single child, just go up the widget tree and hide the container widget which is not a single child, in this case going all the way up to the window

**Comment by BigfootN** [comment]
Thank you for your quick reply.

> if you add another child to inner_box it would probably solve your issue

Why is that ?

> in this case going all the way up to the window

So I suppose "hiding" the window ? (which is not what I specifically wish for)

**Comment by Aylur** [comment]
>Why is that ?

as I mentioned above "this seems like a weird gtk behavior, turns out when you want to set every children invisible, it won't work"
and since its an only child, you are setting *every* children invisible

>So I suppose "hiding" the window ? (which is not what I specifically wish for)

your widget tree currently looks something like this
```
   window
      |
  inner_box
      |
  musicBox
    |    |
label    label
```

so setting the two label to invisible is equivalent to setting the window invisible

**Comment by BigfootN** [comment]
Oh okay thank you.

> this seems like a weird gtk behavior, turns out when you want to set every children invisible, it won't work

Now I understand what you mean by that.

In any case, I was planning on adding another child.

Thank you for the explanation and your time and help.
