### ISSUE TITLE
Is there anyway to change the transition timing function of Widget.Revealer?

### ISSUE THREAD

**Issue by AnhQuanTrl** [Aylur/ags#193]
I am not really proficient at GJS so this is a newbie question. Can I change the timing function of the Revealer. I want to change it to be a bit like "ease-out" effect instead of the current transition.

**Comment by Aylur** [comment]
You can only change its animation duration, the revealer widget doesn't support revealing unfortunately. Maybe gtk4 will allow it, not sure tho haven't checked it
