### ISSUE TITLE
The wiki example for the Menu Widget doesn't work

### ISSUE THREAD

**Issue by HyperTTPS** [Aylur/ags#197]
I'm new to ags so I might be wrong, but when setting ags up I tried the example for the [Menu Widget](https://github.com/Aylur/ags/wiki/Basic-Widgets#menu):
```js
// to have a menu popup on click
const button = Widget.Button({
    child: Widget.Label('click to open menu'),
    onClicked: (_, event) => Widget.Menu({
        children: [
            Widget.MenuItem({
                child: Widget.Label('hello'),
            }),
        ],
    }).popup_at_pointer(event),
});
```
When running it,  it would give the following error:
`(com.github.Aylur.ags:350394): Gjs-CRITICAL **: 22:58:15.663: JS ERROR: Error: Expected an object of type GdkEvent for argument 'trigger_event' but got type undefined`

i.e. the `event` parameter in the `onClicked` event in the example is undefined when passing it to `popup_at_pointer`.

It seems that `onClicked` has the correct behaviour, and it might instead be an error in the example because when you go up to the [Button Widget](https://github.com/Aylur/ags/wiki/Basic-Widgets#button), it says that the `onClicked` event has type `() => void` and not `(event: Gdk.Event) => boolean` like all the other events.

**Comment by Aylur** [comment]
The snippet is wrong, I meant to write `onPrimaryClick` and it seems, the casing on some properties are also wrong
Will fix, thank you
