### ISSUE TITLE
ERROR: Program 'tsc' not found or not executable

### ISSUE THREAD

**Issue by FR13NXD** [Aylur/ags#2]
![image](https://github.com/Aylur/ags/assets/127687150/7cadbb7f-84eb-422e-a5a8-6b17d7151184)

**Comment by FR13NXD** [comment]
nevermind i didnt have typescript, but i have another issue 

`
[15/18] Generating src/typescript-compile with a custom command
FAILED: src/tsc-output
/usr/bin/tsc --outDir /home/fr13nd/ags/build/tsc-out
../src/app.ts(1,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/app.ts(2,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/app.ts(3,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/app.ts(4,21): error TS2307: Cannot find module 'gi://GObject' or its corresponding type declarations.
../src/app.ts(27,30): error TS2576: Property 'connect' does not exist on type 'App'. Did you mean to access the static member 'App.connect' instead?
../src/app.ts(41,31): error TS2339: Property 'emit' does not exist on type 'App'.
../src/app.ts(45,31): error TS2339: Property 'emit' does not exist on type 'App'.
../src/app.ts(54,23): error TS2576: Property 'quit' does not exist on type 'App'. Did you mean to access the static member 'App.quit' instead?
../src/app.ts(68,14): error TS2339: Property 'hold' does not exist on type 'App'.
../src/app.ts(108,14): error TS2551: Property 'add_action' does not exist on type 'App'. Did you mean '_addAction'?
../src/dbus/dbus.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/dbus/mpris.ts(1,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/dbus/mpris.ts(2,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/dbus/upower.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/main.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/main.ts(2,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/main.ts(52,26): error TS2339: Property 'run' does not exist on type 'App'.
../src/service/apps.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/service/apps.ts(2,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/apps.ts(78,21): error TS7006: Parameter 'app' implicitly has an 'any' type.
../src/service/apps.ts(79,18): error TS7006: Parameter 'app' implicitly has an 'any' type.
../src/service/apps.ts(81,14): error TS2339: Property 'emit' does not exist on type 'ApplicationsService'.
../src/service/battery.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/service/battery.ts(2,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/battery.ts(63,14): error TS2339: Property 'emit' does not exist on type 'BatteryService'.
../src/service/bluetooth.ts(1,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/bluetooth.ts(136,14): error TS2339: Property 'emit' does not exist on type 'BluetoothService'.
../src/service/hyprland.ts(1,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/service/hyprland.ts(2,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/service/hyprland.ts(3,21): error TS2307: Cannot find module 'gi://GObject' or its corresponding type declarations.
../src/service/hyprland.ts(4,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/hyprland.ts(108,18): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(117,18): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(144,18): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(175,18): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(180,18): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(194,14): error TS2339: Property 'emit' does not exist on type 'HyprlandService'.
../src/service/hyprland.ts(228,58): error TS7006: Parameter 'stdout' implicitly has an 'any' type.
../src/service/hyprland.ts(228,66): error TS7006: Parameter 'res' implicitly has an 'any' type.
../src/service/mpris.ts(1,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/service/mpris.ts(2,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/service/mpris.ts(3,21): error TS2307: Cannot find module 'gi://GObject' or its corresponding type declarations.
../src/service/mpris.ts(4,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/mpris.ts(78,14): error TS2339: Property 'emit' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(154,14): error TS2339: Property 'emit' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(185,26): error TS2339: Property 'emit' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(212,14): error TS2339: Property 'emit' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(275,16): error TS2339: Property 'connect' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(277,18): error TS2339: Property 'emit' does not exist on type 'MprisService'.
../src/service/mpris.ts(280,16): error TS2339: Property 'connect' does not exist on type 'MprisPlayer'.
../src/service/mpris.ts(281,18): error TS2339: Property 'emit' does not exist on type 'MprisService'.
../src/service/notifications.ts(1,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/service/notifications.ts(2,23): error TS2307: Cannot find module 'gi://GdkPixbuf' or its corresponding type declarations.
../src/service/notifications.ts(3,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/service/notifications.ts(4,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/notifications.ts(60,14): error TS2339: Property 'emit' does not exist on type 'NotificationsService'.
../src/service/notifications.ts(246,14): error TS2339: Property 'emit' does not exist on type 'NotificationsService'.
../src/service/service.ts(1,21): error TS2307: Cannot find module 'gi://GObject' or its corresponding type declarations.
../src/service/service.ts(2,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/service/service.ts(38,27): error TS2339: Property 'connect' does not exist on type 'Service'.
../src/service/service.ts(39,46): error TS2339: Property 'disconnect' does not exist on type 'Service'.
../src/utils.ts(1,17): error TS2307: Cannot find module 'gi://Gdk?version=3.0' or its corresponding type declarations.
../src/utils.ts(2,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/utils.ts(3,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/utils.ts(4,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/utils.ts(5,21): error TS2307: Cannot find module 'gi://GObject' or its corresponding type declarations.
../src/utils.ts(90,10): error TS7006: Parameter '_file' implicitly has an 'any' type.
../src/utils.ts(90,17): error TS7006: Parameter 'result' implicitly has an 'any' type.
../src/utils.ts(241,50): error TS7006: Parameter 'proc' implicitly has an 'any' type.
../src/utils.ts(241,56): error TS7006: Parameter 'res' implicitly has an 'any' type.
../src/widget.ts(1,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/window.ts(1,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/window.ts(2,17): error TS2307: Cannot find module 'gi://Gdk?version=3.0' or its corresponding type declarations.
../src/window.ts(115,41): error TS7006: Parameter '_' implicitly has an 'any' type.
../src/window.ts(115,44): error TS7006: Parameter 'event' implicitly has an 'any' type.
[16/18] Generating subprojects/gvc/Gvc-1.0...stom command (wrapped by meson to set env)
ninja: build stopped: subcommand failed.
Could not rebuild /home/fr13nd/ags/build
`

**Comment by Aylur** [comment]
oh yeah I forgot this part, updated the readme
you need `nodejs` then cd into the cloned repo and do `npm install`, this will get the type definitions and typescript too. after it finished you can `meson install`

**Comment by Aylur** [comment]
No wait thats not it. How did you clone the repo? The git submodlues were not cloned

**Comment by FR13NXD** [comment]
i did:
git clone https://github.com/Aylur/ags.git 
cd ags
npm i
meson setup build
meson install -C build

**Comment by Aylur** [comment]
try
```bash
git clone --recursive https://github.com/Aylur/ags.git
```

**Comment by FR13NXD** [comment]
oh that works now
