### ISSUE TITLE
AGS does not recover from laptop lid shut

### ISSUE THREAD

**Issue by ldelossa** [Aylur/ags#205]
Hello,

When I'm using AGS and a widge if shown on the screen, if I close the laptop it appears AGS loses the GTKMonitor and never recovers it. 

This leads to the widgets unloading and any subsequent widget loading to fail.

**Comment by SystematicError** [comment]
Can you provide a reproducible config and system/AGS version info? AGS handles suspension fine for me; I'm on NixOS unstable and using the latest version of AGS via the flake.
