### ISSUE TITLE
ArchLinux Missing meson and typescript packages in installation instructions

### ISSUE THREAD

**Issue by M0hit-5-5** [Aylur/ags#21]
Hi, i was trying to install ags on archlinux and i ran into these issues

`src/meson.build:2:6: ERROR: Program 'tsc' not found or not executable`
and
`Unknown command: meson`

I fixed these issues by installing the "meson" and the "typescript" package. 

`sudo pacman -S meson typescript`

**Comment by Aylur** [comment]
added meson to the list, typescript should be installed when doing `npm install` did it not work?

**Comment by nobleach** [comment]
Not the original poster but, I did `npm i -g typescript`. I still haven't been able to find `menson` anywhere. I'm also on Arch so I'm confused why I can't find it.

**Comment by M0hit-5-5** [comment]
I tried compiling fresh after removing the typescript package from python. Npm install does not install typescript.

**Comment by Artofaj** [comment]
I can confirm typescritpt not being installed by npm. This relies on user interaction, which is ok, but could be documented?

**Comment by Aylur** [comment]
I just realized meson won't know where typescript was installed by npm
Updated the wiki
