### ISSUE TITLE
Revealer's on_hover_lost works only if the cursor is moved in the window

### ISSUE THREAD

**Issue by Raptorox** [Aylur/ags#221]
I have a Revealer widget whose reveal_child is toggled by a variable, set in on_hover and on_hover_lost in the EventBox it is inside.
However, it seems that on_hover_lost only fires when I move the cursor outside the Revealer.
Otherwise, if I move the cursor outside the window straight from the revealer, it gets stuck on its revealed state

**Comment by Raptorox** [comment]
The trimmed down code of the widget:
```js
export const power = Widget.EventBox({
    on_hover: () => Vars.power.value = true,
    on_hover_lost: () => Vars.power.value = false,
    child: Widget.Box({
        children: [
            Widget.Revealer({
                transition: "slide_left",
                transition_duration: 550,
                reveal_child: true,
                binds: [['reveal_child', Vars.power]],
        ]
    })
})
```

**Comment by Raptorox** [comment]
I'm using Hyprland v0.33.1 on Arch if that changes anything

**Comment by Aylur** [comment]
I know about this issue. It was an attempt to improve the hover callbacks of `EventBox`, because `on_hover_lost` would get executed even if the widget was still being hovered, now it won't fire off when its on the edge of a window.
You can mostly solve this by adding a 1-2 px padding on the window, so there is place for the hover state to register.
This is a low priority issue, because transitioning to gtk4 will fix this.

**Comment by Raptorox** [comment]
How to add the padding then? I tried setting class_name to 'bar' and trying either bar, .bar and #bar in the css but it just doesn't work. The export default has style: App.configDir + '/style.css', and that's where I'm putting the style in

**Comment by Raptorox** [comment]
I came over from EWW, and completely forgot about window#bar targeting. Well, that works, so issue fixed!

**Comment by Balssh** [comment]
@Raptorox mind if you share how you implemented this? I'm having some trouble.

**Comment by Raptorox** [comment]
Well, I quite literally did the exact same thing Aylur has shown. In config.js I put
```js
export default {
    style: App.configDir + '/style.css',
    windows: [
        bar
    ]
}
```
Window definition is
```js
const bar = Widget.Window({
    name: 'bar',
    anchor: ['top', 'left', 'right'],
    exclusivity: 'exclusive',
    child: Widget.Box({
        children: [
            power // the revealer widget, imported from a file
        ]
    })
})
```
And in style.css (located in config root, as per the style parameter) I put
```js
window#bar > box {
    padding: 4px;
}
```

Maybe your window has a different name, I'm pretty sure it should be `window#{window_name}`, `not window#bar` all the time. And if you have a `child: {revealer_widget}` and not `{box}`, I think you should also set it to `window#{window_name} > revealer`

**Comment by Balssh** [comment]
Thanks, I'll look around as my config is more akin to Aylurs. Still learning scss and js.
