### ISSUE TITLE
USB tethering

### ISSUE THREAD

**Issue by heisfer** [Aylur/ags#224]
Is it possible to add usb tethering support? like  status shows disconnected or i'm missing something

**Comment by Aylur** [comment]
Might be. I am not aware of any backend we could use, but I am sure there is.
Is there gnome extension that does this that you know of?

**Comment by heisfer** [comment]
Well what I mean by that is status icon that internet is "connected" 
![image](https://github.com/Aylur/ags/assets/28564678/9fd8e04b-d8e2-4c35-b252-059404746d41)
for example
