### ISSUE TITLE
Icon inside CircularProgress

### ISSUE THREAD

**Issue by Raptorox** [Aylur/ags#241]
Is it possible to add an icon inside a CircularProgress? And lower the size of the Progress's width to boot, it's too big for me

**Comment by Raptorox** [comment]
Alright, apparently I just can't read, I got most of the issues resolved by actually reading the wiki properly, but I still don't know where to get the icon names from.

**Comment by Aylur** [comment]
you can list icons with [Gtk.IconTheme](https://gjs-docs.gnome.org/gtk30~3.0/gtk.icontheme)
```js
import Gtk from 'gi://Gtk'
const icons = Gtk.IconTheme.get_default().list_icons(null)
print(icons)
```

**Comment by Raptorox** [comment]
Okay, thanks. I hate the icon names, but what can I do, it's what Gtk has
