### ISSUE TITLE
Notification Timeout Property

### ISSUE THREAD

**Issue by Trent-Just-Trent** [Aylur/ags#244]
My apologies if this a simple question with a simple solution. 
is there a way to have the expiration from the original notification sent with a timeout option accessed from the notification service?
For example with “notify-send -t 5000 hello-world” would return a notification service with
Notification.expiration=5000
Notification.summary=“hello-world”

how to access that timeout, expiration property?
If it doesn’t exist can you add such property to notification or point me in the right direction to add property?

Thanks

**Comment by kotontrion** [comment]
This is already implemented, but you can't access that property directly, iirc.

It works like that:
Notification is created, its `popup` property is set to true and the `notify` signal is emitted on the Notifications service.
After the specified expiration time has passed (it defaults to config.notificationPopupTimeout if not specified or config.notificationForceTimeout is set to true) the `popup` property of that Notification object is set to false and the `dismiss` signal is emitted.

**Comment by Trent-Just-Trent** [comment]
I understand. My intent was to animate a circle using the timeout of the notification. I appreciate your creply

**Comment by Trent-Just-Trent** [comment]
> This is already implemented, but you can't access that property directly, iirc.
> 
> It works like that: Notification is created, its `popup` property is set to true and the `notify` signal is emitted on the Notifications service. After the specified expiration time has passed (it defaults to config.notificationPopupTimeout if not specified or config.notificationForceTimeout is set to true) the `popup` property of that Notification object is set to false and the `dismiss` signal is emitted.



> This is already implemented, but you can't access that property directly, iirc.
> 
> It works like that: Notification is created, its `popup` property is set to true and the `notify` signal is emitted on the Notifications service. After the specified expiration time has passed (it defaults to config.notificationPopupTimeout if not specified or config.notificationForceTimeout is set to true) the `popup` property of that Notification object is set to false and the `dismiss` signal is emitted.

I understand. My intent was to animate a circle using the timeout of the notification. I appreciate your reply

**Comment by Aylur** [comment]
The `popup: boolean` property should be removed in favor of an `expiration: number` property.
Reopened this, so that I can keep track of this, and implement it later

**Comment by Aylur** [comment]
>The timeout time in milliseconds since the display of the notification at which the notification should automatically close.
>If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification.
>If 0, the notification never expires. 

I have just realized that I misunderstood how the expiration parameter should work. I won't change it now, we will keep using this parameter as a timeout for how long should it be a `popup`, or maybe adding another option would solve this as I prefer the current behavior, although most clients don't specify this parameter anyway. 

@Trent-Just-Trent you can now access `Notification.timeout`, but keep in mind that it will be 0 most of the time if you don't specify `notificationForceTimeout` and `notificationPopupTimeout` in the config object

**Comment by Trent-Just-Trent** [comment]
Awesome. A bit late but I appreciate your help with this.
