### ISSUE TITLE
Keybinindgs for widgets

### ISSUE THREAD

**Issue by yassinebenarbia** [Aylur/ags#248]
Hi, is there a way to add key binds listening for widgetswhere it looks as the following
`Widgets.widget({..., keybind_sequence: "Alt Enter", keybind_handler: self => { doStuff() } } )`
as that would be perfect to extend the capability and allow for more advanced customization for each widget

**Comment by kotontrion** [comment]
This is currently possible with the `key-press-event`signal. Here is an example from my config:
```js
widget.on("key-press-event", (_, event) => {
      const keyval = event.get_keyval()[1];
      if (event.get_state()[1] != (Gdk.ModifierType.MOD1_MASK)) return;
      switch (keyval) {
        case Gdk.KEY_n:
        case Gdk.KEY_Tab:
          LauncherState.next();
          break;
        case Gdk.KEY_p:
          LauncherState.prev();
          break;
        case Gdk.KEY_0:
        case Gdk.KEY_KP_0:
          LauncherState.setIndex(0);
          break;
        ...
})
```
Have a look at the Gdk docs to get a list of the modifier types and key values, MOD1 is the alt key.
I admit that this is not as clean looking,  as having properties for it, but it works.

**Comment by Aylur** [comment]
a `keybind` property sounds useful as an abstraction over this that would be some thing like
```js
Widget({
  keybinds: [
    ['Mod1+n', self => { }]
  ],
  
  // or maybe
  setup: self => self
    .keybind('Mod1+n', self => { })
})
```

**Comment by yassinebenarbia** [comment]
I guess providing both capabilities would be nice tho, or providing a service that can be binded to a widget to listen for keystrokes, but ig the first option is nicer.

**Comment by kotontrion** [comment]
Having a service for this won't work, because of the way gtk works. The events can only be received by widgets.
The keybinds: [...] Will break types, similar his connections and binds worked at older releases.
So .keybind() is the best option of these. If it returns self, similar .hook, .baind and .on this would be useful.

```js
Widget({...})
    .hook(...)
    .keybind('Mod1+n', self => { })
    .keybind('Mod1+p', self => { })
```
