### ISSUE TITLE
Changes to the config files resetting when ags is restarted.

### ISSUE THREAD

**Issue by NextStep-IM** [Aylur/ags#249]
### Issue:
I changed a font family in style.css but when I restarted ags to check if it worked, style.css had gone to its original configuration. I am on Arch + Hyprland, and I am using end_4's hyprland dotfiles. 

### Expected Result:
The change to the file should have been saved even if there was no result.

### How to Reproduce:
1- Change a file in ags directory.
2- Kill ags and then start it again.
3- Check the changed file.

**Comment by kotontrion** [comment]
end-4's config uses scss, which is compiled into the style.css file, therefore changes will be overwritten as soon as you start ags.
You should change the scss files in the scss directory.

**Comment by NextStep-IM** [comment]
> end-4's config uses scss, which is compiled into the style.css file, therefore changes will be overwritten as soon as you start ags. You should change the scss files in the scss directory.

That worked. Thank you so much!

**Comment by NextStep-IM** [comment]
> end-4's config uses scss, which is compiled into the style.css file, therefore changes will be overwritten as soon as you start ags. You should change the scss files in the scss directory.

That worked. Thank you so much!
