### ISSUE TITLE
setup copr repo

### ISSUE THREAD

**Issue by Amcolex** [Aylur/ags#25]
First of all, this is looking like an amazing project. You clearly are putting in loads of work, so thanks! it looks very promising!

I'd love to test it out, but i'm currently running on silverblue (universal blue), so build it from source isn't any easy option. 

Any chance of setting up a copr repo to make to easier for people to install and test it?

**Comment by Aylur** [comment]
I might look into it, but I won't promise anything. In the meantime, you can test it in a toolbox or distrobox container, although when I tested it some of the Services did not work.

**Comment by Amcolex** [comment]
Sounds good. I managed to get it working for now as a nix pkg 👍

**Comment by mrhyperbit** [comment]
### Repository Details
- **Repository Name:** [solopasha/hyprland]
- **Repository URL:** [[URL](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/)]

### Instructions
Follow these steps to set up the Copr repository:

```bash
sudo dnf copr enable solopasha/hyprland
sudo dnf install aylurs-gtk-shell
```

### Additional Information
- If you encounter any issues or have questions about using the Copr repository, please feel free to comment on this issue for assistance.
- Make sure to keep your system up to date to receive the latest package updates from the Copr repository.
- [Copr Github Repo](https://github.com/solopasha/hyprlandRPM)

**Comment by Aylur** [comment]
I feel honored, been using your copr for a while now for Hyprland
Thank you, added it to the [wiki](https://github.com/Aylur/ags/wiki/installation) too

**Comment by NikkSaan** [comment]
@mrhyperbit 

Thank you! But..

> * This repo already has hyprland, waybar, eww, etc.

I think bundling different packages like this provides a bad user experience. I added your copr repo for AGS, but after system update I noticed I would also get newer version of hyprland and other programs which I would prefer not to upgrade.
