### ISSUE TITLE
ags can't see my battery

### ISSUE THREAD

**Issue by danknil** [Aylur/ags#252]
### Issue:
Battery.available returns false, but upower see my battery.
`upower -d` output: https://pastebin.com/fW2vLJmx

**Comment by danknil** [comment]
fixed after i use Battery.bind("available"). I don't know if this expected behaviour tho

**Comment by kotontrion** [comment]
This is expected. Every service is async, so the properties are most likely not initialized properly when accessed directly after start. Using the properties in connections like bind, or hook is the recommended way.

**Comment by danknil** [comment]
Thanks for the explanation! Closing the issue.
