### ISSUE TITLE
Clarification about dependencies

### ISSUE THREAD

**Issue by DaniD3v** [Aylur/ags#253]
I'm writing a gentoo ebuild for this because the one in the xira repo is broken.

The official PKGBUILD has the following dependencies.

makedepends=('meson' 'npm')
depends=('glib2' 'libpulse' 'glibc' 'typescript' 'gjs' 'gtk3' 'gtk-layer-shell' 'gobject-introspection' 'libsoup3')
optdepends=('gnome-bluetooth-3.0: required for bluetooth service'
            'upower: required for battery service'
            'networkmanager: required for network service'
            'libdbusmenu-gtk3: required for systemtray service'

However the gentoo ebuild I found (which apperently worked 2 months ago) has these dependencies

DEPEND="
	dev-libs/gjs
	x11-libs/gtk+
	gui-libs/gtk-layer-shell[introspection]
	net-wireless/gnome-bluetooth

	sys-power/upower
	net-misc/networkmanager
	dev-libs/gobject-introspection
	dev-libs/libdbusmenu[gtk3]
"
BDEPEND="
	net-libs/nodejs
	dev-lang/typescript
	dev-util/meson
"

I don't really care about the bdepends, but I'm wondering how the ebuild worked when he didn't include dependencies like libsoup3. Is that a optional dependency with networkmanager? also does this really require libpulse? Maybe the ebuild writer just happened to have that installed on his system or is it kinda optional as well?

Also do you have any plans of adding use-flags/features to prevent compiling specific parts you don't need? Don't know if that's even possible with ts tho.

**Comment by kotontrion** [comment]
I haven't gotten around to test the dependencies properly yet. There are a few packages listed as dependencies, that can be moved to the make dependencies.

libsoup3 is a dependency introduced in the latest release (v1.6.3) and is required. (needed for Utils.fetch)
libpulse is optional, but required for the audio service
typescript and gobject-introspection should be make dependencies

**Comment by Aylur** [comment]
We can move the `libsoup3` import into a dynamic import in js so that it is not a hard dependency
I plan on a `Utils.notify` function that will depend on `libnotify` and I plan to make it optional too
