### ISSUE TITLE
can't access env variables using the `exec` utility

### ISSUE THREAD

**Issue by yassinebenarbia** [Aylur/ags#264]
using the `exec` utility, I can't access the environment variable `$HOME` or any other env var with the `echo` command so the following code will result to showing `$HOME` instead of `/home/usr`
```js
import * as Utils from 'resource:///com/github/Aylur/ags/utils.js';
console.log(Utils.exec("echo $HOME"));
```

**Comment by Aylur** [comment]
> Both exec and execAsync launches the given binary on its own

so three things:
- Utils.exec runs echo with the passed string `$HOME`, thats why it prints it, the `echo` binary doesn't know what it is, it just prints it as a string
- variables prefixed with `$` that you are trying to get is a `bash` thing, so you should run it with bash
- don't do this, if you want to get an env variable use the language's tools

```js
import GLib from 'gi://GLib'
const home = GLib.getenv('HOME')

// or better yet
const home = GLib.get_home_dir()

// since 1.7.1
import * as Utils from 'resource:///com/github/Aylur/ags/utils.js';
const home = Utils.HOME
```
