### ISSUE TITLE
reactive mpris player position?

### ISSUE THREAD

**Issue by xyangst** [Aylur/ags#268]
what i tried:
```js
Widget.Label({label:player.bind("position").transform(String)})
```
the position in that label only updates when i manually the track changes or i manually set the position. How do i make the label update automatically eg once a second or something?

**Comment by kotontrion** [comment]
the position property does only emit a signal when set explicitly. To update it regularly you have to poll it:
```js
Widget.Label().poll(1000, (self => self.label = `${player.position}`))
```
