### ISSUE TITLE
Bluetooth service not detecting bluetooth

### ISSUE THREAD

**Issue by kylfp** [Aylur/ags#270]
OS is Arch. I have enabled experimental features on the /etc/bluetooth/main.conf. For some reason I cannot get the bluetooth service to work. I have tried multiple configurations including a label simply stating if the bluetooth is turned on or off. I'm not sure if this is an issue or me just missing something completely. 

```
import Widget from 'resource:///com/github/Aylur/ags/widget.js';
import Bluetooth from 'resource:///com/github/Aylur/ags/service/audio.js';

const BTIndicator = () => Widget.Icon().hook(Bluetooth, self => {
  const status = Bluetooth.enabled;
  self.icon = status ? 'bluetooth-active-symbolic' : 'bluetooth-disabled-symbolic';
  self.tooltip = Bluetooth.connected_devices[0].name;
})

export default BTIndicator;
```
I've included this screenshot showing a connected bluetooth device and the indicator output on a bar showing it disabled.

![20240122_18h15m42s_grim](https://github.com/Aylur/ags/assets/126174592/48c7adfd-5cdc-456e-88ed-692bf745a585)

**Comment by Aylur** [comment]
you are importing audio, not bluetooth
```js
import Bluetooth from 'resource:///com/github/Aylur/ags/service/audio.js';
```

**Comment by kylfp** [comment]
Well isn't that a 'bruh' moment. Let's pretend this didn't happen.
