### ISSUE TITLE
crash when monitor turned off and on in Hyprland

### ISSUE THREAD

**Issue by phonetic112** [Aylur/ags#284]
When I turn my monitor off and on again in Hyprland, ags crashes with this error:

```
(com.github.Aylur.ags:23455): Gjs-WARNING **: 14:15:05.338: JS ERROR: Gio.IOErrorEnum: Could not connect: Resource temporarily unavailable
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
sendMessage@resource:///com/github/Aylur/ags/service/hyprland.js:125:34
_syncWorkspaces@resource:///com/github/Aylur/ags/service/hyprland.js:165:36
_onEvent@resource:///com/github/Aylur/ags/service/hyprland.js:215:32
_watchSocket/<@resource:///com/github/Aylur/ags/service/hyprland.js:120:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Gwenodai** [comment]
Any idea how to fix this? I've been running into the same issue with swapping a monitor from mirroring to extending and vice versa. Ags will just randomly crash about 20% of the time. For now I've just taken to calling ags on a 5 second delay after any script that changes monitor configs in case it crashes.

**Comment by phonetic112** [comment]
I've worked around this (and other issues with monitor disconnects in Hyprland) by just using the HDMI port on my monitor instead of DP. HDMI keeps the monitor connected to the GPU when I turn it off on my ASUS monitor, so maybe try that

**Comment by Gwenodai** [comment]
My issue is that I'm not disconnecting it physically at all. I'm just changing it from mirroring to not mirroring.
I've actually mostly worked around it now by just running ags with this script now. It's silly that it's needed but it works. (also have to close spotify after launching as it unhides when the ags tray dissapears along with ags lol)

```
#!/usr/bin/env bash

while ! /usr/local/bin/ags
do
    sleep 1 && hyprctl dispatch closewindow "Spotify" &
done
```

**Comment by ccarlile** [comment]
I'm experiencing similar behavior when I turn my monitor off an on, except only the bar disappears (I'm still able to invoke a e.g. launcher widget from the wm keybinds) and I don't get any error logs.

**Comment by ccarlile** [comment]
I will add that invoking the inspector after power cycling the monitor, all the per-monitor windows seem to be gone, but e.g. the AppLauncher widget is still listed. Attempting to re-invoke the bar with `ags -t bar0` doesn't work, it errors with

```
(com.github.Aylur.ags:1596296): Gjs-CRITICAL **: 11:02:15.307: Object .Ags_Window (0x1d65fa0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0xafcbb0 ==
#0         bc52d0 i   resource:///com/github/Aylur/ags/app.js:117 (17e5bb8b71f0 @ 47)
#1         bc5240 i   resource:///com/github/Aylur/ags/app.js:283 (17e5bb8b7c90 @ 20)
#2         bc5160 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329 (17e5bb8869c0 @ 185)
#3         bc50b0 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408 (17e5bb886b00 @ 34)
#4         bc4fe8 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (17e5bb87c420 @ 139)
```

output of hyprctl monitors
```
❯ hyprctl monitors
Monitor HDMI-A-1 (ID 0):
	2560x1080@59.97800 at 0x0
	description: LG Electronics LG HDR WFHD 0x0007A8C5 (HDMI-A-1)
	make: LG Electronics
	model: LG HDR WFHD
	serial: 0x0007A8C5
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

I'm using slightly modified asztal (Aylur's config)

**Comment by kotontrion** [comment]
> I'm experiencing similar behavior when I turn my monitor off an on, except only the bar disappears (I'm still able to invoke a e.g. launcher widget from the wm keybinds) and I don't get any error logs.

This is because the monitor disconnected, which then destroys all windows bound to that monitor. To solve this you need to recreate the windows when the monitor is added again. This is unrelated to the crash reported in this issue.

My config supports multimonitor setups with monitors added/removed during runtime. Here is the part of the config responsible for this: (addMonitorWindows functions creates the windows and adds them)

```js
  const display = Gdk.Display.get_default();
  for (let m = 0;  m < display?.get_n_monitors();  m++) {
    const monitor = display?.get_monitor(m);
    addMonitorWindows(monitor);
  }

  display?.connect("monitor-added", (disp, monitor) => {
    addMonitorWindows(monitor);
  });

  display?.connect("monitor-removed", (disp, monitor) => {
    App.windows.forEach(win => {
      if(win.gdkmonitor === monitor) App.removeWindow(win);
    });
  });
```

**Comment by ccarlile** [comment]
@kotontrion Thanks for hopping in and providing this info! For my own edification:
> This is because the monitor disconnected, which then destroys all windows bound to that monitor.

Is this an ags thing, a wayland thing, or something else? Could you point me in a direction to learn more?

**Comment by kotontrion** [comment]
That is part of the layer-shell protocol. When a Layer Window is bound to a monitor it gets destroyed when that monitor is disconnected. This is done by the gtk-layer-shell library. That is also the reason why your launcher still works, as it is probably not bound to a specific monitor and therefore pops up on the currently focused one and does not get destroyed on monitor disconnects.

Also note that while the window is destroyed, ags has holds a reference to it in `App.windows`. That's why you get the `window is already disposed`error when trying to open it using `ags -t bar0`and why I call `App.removeWindow` on monitor disconnects, to clean it up.

**Comment by Gwenodai** [comment]
> > I'm experiencing similar behavior when I turn my monitor off an on, except only the bar disappears (I'm still able to invoke a e.g. launcher widget from the wm keybinds) and I don't get any error logs.
> 
> Yeah that's what happens for me too. Hence I just run that script above at startup.

Oh I feel like I totally misunderstood here then. I thought your launcher was a seperate program and you were saying that other programs don't crash, just ags. My entire ags crashes. Like the whole process dies when one monitor changes.

**Comment by TakodaS** [comment]
> > I'm experiencing similar behavior when I turn my monitor off an on, except only the bar disappears (I'm still able to invoke a e.g. launcher widget from the wm keybinds) and I don't get any error logs.
> 
> This is because the monitor disconnected, which then destroys all windows bound to that monitor. To solve this you need to recreate the windows when the monitor is added again. This is unrelated to the crash reported in this issue.
> 
> My config supports multimonitor setups with monitors added/removed during runtime. Here is the part of the config responsible for this: (addMonitorWindows functions creates the windows and adds them)
> 
> ```js
>   const display = Gdk.Display.get_default();
>   for (let m = 0;  m < display?.get_n_monitors();  m++) {
>     const monitor = display?.get_monitor(m);
>     addMonitorWindows(monitor);
>   }
> 
>   display?.connect("monitor-added", (disp, monitor) => {
>     addMonitorWindows(monitor);
>   });
> 
>   display?.connect("monitor-removed", (disp, monitor) => {
>     App.windows.forEach(win => {
>       if(win.gdkmonitor === monitor) App.removeWindow(win);
>     });
>   });
> ```
I tried to get this along with using the native hyprland service

```javascript
hyprland.connect('monitor-added', (_, monitor) => {
    addMonitorWindows(monitor)
  );
})

hyprland.connect('monitor-removed', (_, monitor) => {
  App.windows.forEach(window => {
    if (window.monitor === monitor) {
      App.removeWindow(window.name)
      }
    }
  );
})
```

however, nothing referencing monitors by number will work since these are dynamically assigned. If I connect a monitor it is very possible that `bar0` will find itself on monitor 1 and thus the only solution is basically to delete and recreate all winodws each time, which is not ideal (see hyprwm/Hyprland#2601)

The solution is that ags should utilize the additional information provided by the new Hyprland `monitoraddedv2` event, or more generally, let `Gtk.window` to be [explicitly set by display name ](https://stackoverflow.com/questions/72790137/c-gtk-how-to-set-display-screen-for-gtk-application-window-to-appear).

**Comment by miyl** [comment]
So is this disappearing bar different from the crash? I have a similar log entry, but checking processes I can see `ags` is still running. 
Not sure if the log happened in this session where ags remains, though, or if it was another time where ags crashed/stopped.

In my case it's a laptop with external monitor setup, where only the external monitor is on and then occasionally turns off via `hypridle`, in case it's relevant. The issue of `ags` disappearing - for one reason or another - happens daily.

**Comment by papHL91** [comment]
There is no need to recreate necessarily, it's the default behavior on gtk, but you can use **Gtk.Window.hide_on_close(true)** and then your window gets hidden but not destroyed. After that, when the monitor is reconnected, you can simply use **Gtk.Window.set_monitor** (the correct monitor must be found) and then **Gtk Window.show()**, and the window come back to the monitor without lost its state, the instance is not deleted

**Comment by The-Lost-Light** [comment]
> There is no need to recreate necessarily, it's the default behavior on gtk, but you can use **Gtk.Window.hide_on_close(true)** and then your window gets hidden but not destroyed. After that, when the monitor is reconnected, you can simply use **Gtk.Window.set_monitor** (the correct monitor must be found) and then **Gtk Window.show()**, and the window come back to the monitor without lost its state, the instance is not deleted

ok, thank you for your suggestion, this is my improved version
```typescript
import Gtk from "types/@girs/gtk-3.0/gtk-3.0";
import Window from "types/widgets/window";

import Hyprland from "@services/hyprland";

type agsWindow = Window<Gtk.Widget, unknown>;
type fixed = (id?: number) => agsWindow;
type osd = () => agsWindow;

export const createWindows = (windows: (fixed | osd)[], id?: number) =>
	windows.flatMap(window => {
		if (window.length)
			return Hyprland.monitors.flatMap(monitor => {
				if (id === -1 || monitor.id === id)
					return window(monitor.id).on("destroy", (self: agsWindow) => App.removeWindow(self));
				else return [];
			});
		else return window().on("delete-event", (self: agsWindow) => (self.hide(), true));
	});

export const recreateWindows = (windows: fixed[], id?: number) => {
	App.windows.forEach(window => {
		if (id !== undefined && window["monitor"] === id) App.removeWindow(window);
	});

	App.config({ windows: createWindows(windows, id) });
};

export const toggleMonitorWindows = (fixedWindows: fixed[]) => {
	Hyprland.connect("monitor-removed", (_, name) => recreateWindows(fixedWindows, Hyprland.getMonitorID(name)));
	Hyprland.connect("monitor-added", (_, name) => recreateWindows(fixedWindows, Hyprland.getMonitorID(name)));
};

export const initialWindows = (windows: (fixed | osd)[]) => {
	const fixedWindows = windows.filter(window => window.length);
	Hyprland.connect("monitor-removed", (_, name) => recreateWindows(fixedWindows, Hyprland.getMonitorID(name)));
	Hyprland.connect("monitor-added", (_, name) => recreateWindows(fixedWindows, Hyprland.getMonitorID(name)));

	return createWindows(windows, -1);
};
export default initialWindows;
```

```typescript
export default App.config({
	windows: Hyprland.initialWindows([Bar, Powermenu]),
});
```
