### ISSUE TITLE
setup.sh doesn't create declarations for utils subfolder

### ISSUE THREAD

**Issue by micha4w** [Aylur/ags#285]
I use my own Service.Register function, so that I can do automatic reloading, for this I used to import `registerGObject` from `.../ags/gobject.js`, but recently `gobject.ts` has been moved into the `utils/` subfolder, for which no type declarations exist.

So it would be nice to add something like this to `example/starter-config/setup.sh`:
```sh
for file in ./src/utils/*.ts; do
	resource "utils/$(basename -s .ts $file)" >>$dts
done
```

**Comment by Aylur** [comment]
I am currently working on updating the wiki, and I plan to remove `example/starter-config` completely in favor of the `--init` cli flag.
The script that generates the types is `post_install.sh`, feel free to open up a PR, we could also export them in utils.ts
