### ISSUE TITLE
support negative spacing

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [Aylur/ags#288]
I got following errors when trying to set Box.spacing as a negative number:
`(com.github.Aylur.ags:118181): GLib-GObject-CRITICAL **: 23:38:57.324: value "-30" of type 'gint' is invalid or out of range for property 'spacing' of type 'gint'`
Is it possible to allow using negative number for spacing? EWW works fine with negative spacing

**Comment by Aylur** [comment]
both EWW and AGS just sets the Gtk.Box.spacing property, so I don't think it works on EWW either
if you want negative spacing, you can use negative margins on its children in css
```cs
box.your-box > * {
  margin: 0 -30px;
}
```
