### ISSUE TITLE
abnormal offset of ProgressBar widget

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [Aylur/ags#289]
progressbar.trough.progress has a default margin property while trough hasn't, I had to unset it in the css property,
![screenshot-20240204000507_grim](https://github.com/Aylur/ags/assets/89444744/5593be66-dade-467d-931e-e823b912a97e)

And also If a ProgressBar  has a sibling, it will have a abnormal y offset and I had to adjust it's position by changing it's css margin property, here's my code:
```
const batteryProgress = Widget.Box({
	"vpack": "center",
	"spacing": 0,
	"hpack": "center",
	"children": [
		Widget.ProgressBar({
			"visible": battery.bind('available'),
			"show-text": false,
			"css": `
				trough progress {
					background-color: #FFFFFF;
					min-height: 10px;
					min-width: 20px;
				}
				trough {
					min-height: 10px;
					min-width: 20px;
				}
			`,
			"value": battery.bind('percent').transform(p => p > 0 ? p / 100 : 0),
			"class-name": battery.bind('charging').transform(ch => ch ? 'charging' : ''),
		}),
		Widget.Label({
			"label": ``
		})
	]
})
```
![screenshot-20240204000252_grim](https://github.com/Aylur/ags/assets/89444744/6c11b32c-e26f-431a-9c95-e207db06d08f)

**Comment by Aylur** [comment]
that is just how gtk + your default gtk theme works, AGS doesn't set any css, it all comes from gtk themes
