### ISSUE TITLE
Alternative config path

### ISSUE THREAD

**Issue by Amcolex** [Aylur/ags#29]
Given that it seems the goal of ags (+ your dot files) is pretty close to making a full desktop environment, would it make sense to allow the option to have the config files inside /etc/ ?

**Comment by Aylur** [comment]
It would I guess. Adding a simple `--path` flag should be easy. What would be the use for it though?

**Comment by Aylur** [comment]
added `--config` and `--bus-name` flags besides other things in https://github.com/Aylur/ags/commit/737fc95e67fd5f9d5a313b2cc1380b7d2a2c3e2d
`--config` defaults to `~/.config/ags/config.js/ ` and `--bus-name` defaults to `"ags"`
the bus is used to launch multiple instances

**Comment by DevAlien** [comment]
@Aylur this can be closed I believe
