### ISSUE TITLE
Listening to Hyprland's option changes

### ISSUE THREAD

**Issue by musjj** [Aylur/ags#294]
Is there a way to listen to option changes in Hyprland? I wanted to react to gap changes so that I can adjust my bar's margins, but I couldn't figure out a good way to do it.

**Comment by Aylur** [comment]
There is no IPC event for config changes, You could monitor the config file, but there is no reliable way to do this.
You might want to ask for this feature over at Hyprland

**Comment by qxb3** [comment]
there is this `configreloaded`
![240212_11h07m01s_screenshot](https://github.com/Aylur/ags/assets/59109346/39e90120-6586-4922-8314-3cba9da5aa5f)

**Comment by musjj** [comment]
I tried that, but it looks like that the signal isn't triggered even when I edit `~/.config/hypr/hyprland.conf`. Tested with:

```typescript
const label = Widget.Label({ label: `${0}` });
Hyprland.connect("event", (_, name: string) => {
  if (name == "configreloaded") {
    label.label = `${parseInt(label.label) + 1}`;
  }
});
```

Also with:

```bash
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do echo "$line"; done
```

It's also not triggered when you change your settings via `hyprctl`:

```bash
hyprctl keyword general:border_size
```

I wonder if listening to the `changed` signal would be enough here.

Another thing is that `ags` doesn't provide a way to retrieve an option's value in a structured way, like `hyperctl -j`:

```bash
$ hyprctl -j getoption general:border_size
{
    "option": "general:border_size",
    "int": 3,
    "float": -340282346638528859811704183484516925440.00000,
    "str": "",
    "data": "0x0",
    "set": true
}
```

Instead, you're getting the plain text format which you will then need to parse manually. Is there an equivalent to the `-j` flag in `ags`?

**Comment by musjj** [comment]
Unfortunately, the signal isn't triggered when you change your settings via `hyprctl`:

```bash
hyprctl keyword general:border_size
```

I wonder if listening to the `changed` signal would be enough here.

Another thing is that `ags` doesn't provide a way to retrieve an option's value in a structured way, like `hyperctl -j`:

```bash
$ hyprctl -j getoption general:border_size
{
    "option": "general:border_size",
    "int": 3,
    "float": -340282346638528859811704183484516925440.00000,
    "str": "",
    "data": "0x0",
    "set": true
}
```

Instead, you're getting the plain text format which you will then need to parse manually. Is there an equivalent to the `-j` flag in `ags`?

**Comment by kotontrion** [comment]
the configreloaded signal is only emitted by Hyprland if the config file is reloaded. It won't be emitted when the config was modified using hyprctl. I think there is now way to detect this without polling using `hyprctl getoption` as of now. This would require a change in Hyprland.

Also note that this singal is not implemented in ags, you can however still connect to the event signal
```js
Widget.Label(...).hook(Hyprland, (label, event, params) => {
  if(event === "configreloaded") {
    //config was reloaded
  }
}, "event")
```


> Another thing is that ags doesn't provide a way to retrieve an option's value in a structured way, like hyperctl -j:

`Hyprland.sendMessage()` which is being replaced by `Hyprland.message()` and `Hyprland.messageAsync()` use the Hyprland socket directly. so to get the result as json you would have to do this:

```js
const border_size = JSON.parse(Hyprland.message("j/keyword general:border_size"))
```

**Comment by musjj** [comment]
Thanks for the tips! The `globalThis` method looks nice, I'll try it out!
