### ISSUE TITLE
Can we install ags on non-systemd distros like void linux or alpine linux?

### ISSUE THREAD

**Issue by RipDr19** [Aylur/ags#295]

**Comment by Aylur** [comment]
I don't know, I never tried, I don't use these systems. If other gobject based programs work there I don't see why this would not

**Comment by kotontrion** [comment]
It should work.

ags itself does is completely independent of the init system. The only thing that might break are maybe some of the services, as the optional dependencies for them might do. But as far as I know those aren't hard dependencies and work with different init systems as well.

There is also an open PR to add an ags package to void linux already.

**Comment by blacklightpy** [comment]
Yes, I use it. As for ags, you clone the repo, then run `meson setup build` and `meson install -C build`. For updating, you run `meson setup --reconfigure build` and `meson install -C build`. 

For Aylur's dotfiles, follow the guide I posted at Aylur/dotfiles#100 for the required dependencies, and running it on musl libc.

**Comment by delacemane** [comment]
@blacklightpy followed guide, got error after running meson setup build:

gutils| Run-time dependency pam found: NO (tried pkgconfig and cmake)

subprojects/gutils/meson.build:13:2: ERROR: Dependency "pam" not found, tried pkgconfig and cmake

**Comment by blacklightpy** [comment]
@delacemane Oops my bad. `pam-devel` should be installed for that. I must've missed it while I got some bad editing.

**Comment by blacklightpy** [comment]
Will Astal break on non-systemd distros?

**Comment by Aylur** [comment]
it should not
