### ISSUE TITLE
Stack children property and add_named

### ISSUE THREAD

**Issue by kotontrion** [Aylur/ags#296]
I add widgets to a stack dynamically using `stack.add_named(widget, name)`
The widget is added to the stack and can be shown, but it is not added the stack.children property and the `notify::children`signal is not emitted.

**Comment by Aylur** [comment]
this is a bit tricky and I eventually decided against supporting adding children after construction because its type cannot be changed
but it should work either way I suppose

**Comment by Aylur** [comment]
You could also do
```js
stack.children = {
  ...stack.children,
  newName: newWidget,
}
```
this works, but the type checker won't like it
