### ISSUE TITLE
Suddently stop working as of latest update

### ISSUE THREAD

**Issue by Morphexe** [Aylur/ags#30]
I updated Hyprland, and AGS last night, it seems that for some reason AGS no longer renders the windows on screen anymore.

There are no errors on ags side when running `ags` just a couple of warnings, but no windows render sadly.

Any idea on how to even debug this?

**Comment by Aylur** [comment]
Backup your config, and run with a simple config like
```js
var config = {
  windows: [
    {
      name: 'test',
      child: {
        label: 'test',
        style: 'min-width: 100px; min-height: 100px;'
      }
    }
  ]
}
```
* if this window pops up, then it means something inside the config is wrong
* if it doesn't, then I have no idea what the issue could be, but it's probably not with ags

**Comment by Morphexe** [comment]
I found the issue, hyrpland is now returning data in the following format :

hyrprctl - j monitors

```
hyprctl -j monitors
adding monitors
[{
    "id": 0,
    "name": "HDMI-A-1",
    "description": "LG Electronics LG TV SSCR2 0x01010101 (HDMI-A-1)",
    "make": "LG Electronics",
    "model": "LG TV SSCR2",
    "serial": "0x01010101",
    "width": 3840,
    "height": 2160,
    "refreshRate": 60.000000,
    "x": 0,
    "y": 0,
    "activeWorkspace": {
        "id": 1,
        "name": "1"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 0, 0, 0],
    "scale": 1.00,
    "transform": 0,
    "focused": true,
    "dpmsStatus": true,
    "vrr": false
}]
```

I am patching the Hyprland Service by making a JSON.parse function that find the first[ or { and reads the json from there instead.

**Comment by cenunix** [comment]
Could you share here @Morphexe i think I'm running into the same issue.

**Comment by Morphexe** [comment]
You might be better off rollbacking hyprland until a new version is out. I patched mine manually, but there are a few other places that were giving me errors - it seems this is due to a mistake on hyprland leaving log messages out!

**Comment by lukeemhigh** [comment]
The issue with Hyprland has been solved in the latest commit
