### ISSUE TITLE
After opening a new window ags causes some strange windows movement + display sizes in cells format [Hyprland] [ags as bar]

### ISSUE THREAD

**Issue by playfulCloud** [Aylur/ags#304]

**Comment by playfulCloud** [comment]
![Uploading 2024-02-15-221434_hyprshot.png…]()

**Comment by playfulCloud** [comment]
![2024-02-15-221434_hyprshot](https://github.com/Aylur/ags/assets/55619673/c216cb35-edbc-47f9-9e5d-234ac46f1a2a)
Something like that during any interaction with kitty or browser etc

**Comment by playfulCloud** [comment]
![Uploading 2024-02-16-003354_hyprshot.png…]()

**Comment by playfulCloud** [comment]
![2024-02-16-003354_hyprshot](https://github.com/Aylur/ags/assets/55619673/7e5d72b8-bb92-416f-9373-79c679cb5c3c)
this is the more precise one

**Comment by playfulCloud** [comment]
During process of trying to fix that bug it appeared that code which is posted as an example for bar and workspaces is the reason

**Comment by BeyondMagic** [comment]
I think sharing the window's **code** and a video would be more helpful to understand it.
