### ISSUE TITLE
Utils.notify should accept arbitrary hints

### ISSUE THREAD

**Issue by ttoino** [Aylur/ags#314]
Some non-standard hints (like `value` for making progress bars) are quite useful, but the current implementation of `Utils.notify` only allows known hints to be passed as arguments.

I suggest adding an additional `hints` argument, or just accepting arbitrary arguments in this function (though I personally prefer the first option).

**Comment by Aylur** [comment]
yeah, the hints are kind of hard coded, I'll try to refactor the notifications daemon, and Utils.notify to make it more flexible
