### ISSUE TITLE
Widget.Slider adjustment props don't seem to work in the constructor

### ISSUE THREAD

**Issue by ttoino** [Aylur/ags#316]
Passing `min` and `max` to the `Widget.Slider` function does not seem to work. Curiously, these properties do seem to work when set after the fact.

```javascript
Widget.Slider({
	// Does not work
    min: 0,
    max: 100,
	step: 5,
    value: 50,
    setup: (slider) => {
		// Works
        slider.min = 0;
        slider.max = 100;
		slider.step: 5,
    },
})
```

**Comment by Aylur** [comment]
what version? it should work, and it seems to work on 1.7.6 and 1.7.7

**Comment by ttoino** [comment]
I'm using 1.7.6 but it still doesn't seem to work, I'll try to do some more testing
