### ISSUE TITLE
Hyprland border flickers when closing a window with `closeWindowDelay`

### ISSUE THREAD

**Issue by musjj** [Aylur/ags#317]
It seems that when a window is closed and `closeWindowDelay` is set, the border of the active window in Hyprland flickers for a bit.

https://github.com/Aylur/ags/assets/72612857/cda861e4-837b-4487-81d6-1249b213efaf

You can observe it when clicking away from the quicksettings popup window in your [dotfiles](https://github.com/Aylur/dotfiles). Interestingly, toggling the popup via the systemindicator button on the bar doesn't have this effect.

I first thought that the focus was being stolen by something temporarily. So I tried to listen to the `activewindow` event from the Hyprland socket, but it looks like that the active window didn't even change during the transition.

**Comment by Aylur** [comment]
It is most probably a Hyprland bug from switching focus from layer to client

**Comment by musjj** [comment]
Yeah, might be something Hyprland-specific. Another thing I'm noticing is that it depends on your mouse click speed. If you tap *really* fast, the effect doesn't happen.

**Comment by musjj** [comment]
I recently tried https://github.com/ErikReider/SwayNotificationCenter and it has a functional click-away behavior that doesn't have this problem. I wonder how they implemented it.
