### ISSUE TITLE
adding markup support for label's tooltip

### ISSUE THREAD

**Issue by ShadowS0ng** [Aylur/ags#321]
I think the tooltip needs support for markup ,when you use markup to change the text's font,color,etc... . it gets inconsistent with the basic text that the tooltip shows.
so having it would be nice 🙏

**Comment by Aylur** [comment]
I think you are looking for `tooltip-markup`
```js
Widget.Label({
  tooltip_markup: "<i>hello</i>"
})
```

**Comment by Aylur** [comment]
don't forget to also check the classes its derived from, `tooltip-markup` is on Gtk.Widget, the base class
