### ISSUE TITLE
Refresh rate dropped highly

### ISSUE THREAD

**Issue by Root-Time** [Aylur/ags#322]
When i use ags in Hyprland it cuts my refresh rate in half. My Monitor has 100hz if i enabled it drops to 50hz but exactly 50 fps not 1 more or less.
![image](https://github.com/Aylur/ags/assets/76535404/a038cf9d-9307-4121-8329-44380a594b31)
I use Aylur dotfile for the ags configs.
I use Arch.

**Comment by Aylur** [comment]
Does it happen with other gtk-layer-shell apps? waybar, swaync or gtk-layer-shell-demo?

**Comment by Root-Time** [comment]
I tried waybar, swaync and the python demo gtk-layer-shell and everwhere i had 99-100fps.

**Comment by Root-Time** [comment]
Have you an example for an other gtk-layer-shell apps instead of the demos that are more performance needed.

**Comment by Aylur** [comment]
Is this also happening on an empty config?
are you perchance using the PowerProfiles service? maybe you are setting it to power saver mode thats causing this?

**Comment by Root-Time** [comment]
> Is this also happening on an empty config? are you perchance using the PowerProfiles service? maybe you are setting it to power saver mode thats causing this?

Fixed by installing rog-control-center

**Comment by Root-Time** [comment]
Installing rog-control-center fixed my issue.
