### ISSUE TITLE
Hyprland active client incorrectly set to empty on window close

### ISSUE THREAD

**Issue by Eggrror404** [Aylur/ags#329]
When there are two windows in a workspace and one is being closed, both `activewindow` and `closewindow` events gets fired
And it seems that `closewindow` is called after `activewindow` so `active.client` is set to empty instead of whatever that's active.

In this config:
```js
const hyprland = await Service.import("hyprland");

hyprland.connect("event", (_, name, data) => {
  console.log("event:", name, data);
});
hyprland.active.client.connect("notify::title", () => {
  console.log("active:", hyprland.active.client.title);
});
```

The output:
```
Gjs-Console-Message: 21:31:24.516: event: activewindow Alacritty,Alacritty
Gjs-Console-Message: 21:31:24.517: event: activewindowv2 56bb9c62d080
Gjs-Console-Message: 21:31:24.520: active:
Gjs-Console-Message: 21:31:24.520: event: closewindow 56bb9c6294d0
```

The active client is now empty because of `closewindow`.

**Comment by BeyondMagic** [comment]
I can replicate.

**Comment by Aylur** [comment]
not sure what could be done about this as this is much more of an issue with Hyprland, try opening an issue there

**Comment by Eggrror404** [comment]
My initial thought was to just check for the active client on closewindow, but wasn't sure if thats a good idea

will report to hyprland later :)

**Comment by plsmphnx** [comment]
Would this not be fixed by checking if the active client address matches the address of the closed window before clearing out the active client [here](https://github.com/Aylur/ags/blob/5ada4829b5aa29773561bfa55c4bbcef39d0ced2/src/service/hyprland.ts#L337)? When I repro this, I get a brief flicker of what should be the active window title, which suggests it's being set correctly before being cleared.

**Comment by plsmphnx** [comment]
I did a quick test of wrapping that block in `if (this._active.client.address === '0x' + argv[0]) {`, and it appears to fix the issue for me.

**Comment by plsmphnx** [comment]
`src/service/hyprland.ts`, I replaced lines 337-340 with:
```ts
if (this._active.client.address === '0x' + argv[0]) {
    this._active.client.updateProperty('class', '');
    this._active.client.updateProperty('title', '');
    this._active.client.updateProperty('address', '');
    this._active.client.emit('changed');
}
```

**Comment by BeyondMagic** [comment]
Thank you :)

**Comment by Eggrror404** [comment]
@Aylur we've got a fix for this issue :)

If @plsmphnx 's fix is good enough then I'll not file the issue to Hyprland.

(sorry for the delay, I was kinda busy with other things)
