### ISSUE TITLE
Popups show up very small

### ISSUE THREAD

**Issue by sistemasolaris** [Aylur/ags#330]
This issue occurred in my configuration specifically when trying to make notification popups, and I have noticed it happen not only on my own notification widgets, but on the example notification popup provided and in other dotfiles I have tried.

The following image has been scaled 10x bigger for visualizing:

![notification-bug](https://github.com/Aylur/ags/assets/125316554/1eb436c3-6aea-4e18-a458-437344f70445)

The logs are completely empty, with no warnings or errors when receiving a notification.

Running on EndeavourOS, using Hyprland as the compositor. Can reproduce the issue both on the version of ags available on the AUR (version 1.7.7) and when building from source, on version 1.7.8. The issue started happening earlier this week, after rebooting the system.

I would be happy to provide more information if needed.

**Comment by its-darsh** [comment]
what version of hyprland you're running?, does other LayerShell windows show up the same way? (i.e wofi or dunst)

**Comment by sistemasolaris** [comment]
Hyprland 0.36.0

dunst does not behave the same way, it shows up properly, but wofi does seem to do the same thing. Could this be a problem with hyprland?

**Comment by its-darsh** [comment]
hyprland issue, try upgrading to git, i'm on `0.36.0.r22.6e3a494d-1` and this issues doesn't seem to exist

**Comment by sistemasolaris** [comment]
Reinstalling hyprland fixed it, thank you for the help
