### ISSUE TITLE
Not able to fetch any players while using Mpris service

### ISSUE THREAD

**Issue by MohitR1999** [Aylur/ags#342]
Hi,
I've been using ags for a while and it's fantastic. However, I'm running into an issue while trying out the Mpris service. I'm not able to list any players, although I can list them using playerctl. I can control the play pause and other functionalities using playerctl but I wanna make a widget using ags, hope someone can help me out in pointing out what I'm doing wrong.

Attaching the code I'm trying out:
```
const mpris = await Service.import('mpris');

function Player() {
    print(mpris.players); // prints nothing, even if I have a player running
    return Widget.Button({
        onClicked : () => {
            // player.playPause()
        },

        child : Widget.Label('player')
    })
}

export default Player;
```

Attaching my system config:
```
OS: Arch Linux x86_64
Kernel: 6.7.9-arch1-1
DE: Hyprland
Ags version: 1.8.0
```

**Comment by Aylur** [comment]
your are accessing it on startup synchronously which will result in an empty array because it looks for available players asynchronously
have a look at the exmaple widget on the wiki https://aylur.github.io/ags-docs/services/mpris/#example-widget

**Comment by MohitR1999** [comment]
Hi,
Thanks a lot man, I was so confused. Now I'm unblocked :)

Thanks and regards,
*Mohit Ranjan*
