### ISSUE TITLE
Utils.monitorFile not registering events

### ISSUE THREAD

**Issue by MaxiHafer** [Aylur/ags#348]
Monitoring files as in https://aylur.github.io/ags-docs/config/custom-service/ is currently not working.

I am trying to build a temperature service. It seems `Utils.monitorFile` is not getting notified on file changes. Maybe I made an obvious mistake but I cannot seem to find one.

Service logic:
```gjs
#temperatureValue = 0;

#onChange(file) {
        this.#temperatureValue = Number(Utils.readFile(file));
        console.log("temperature-value changed: " + this.#temperatureValue);
        this.changed("temperature-value");

        this.emit("temperature-changed", this.#temperatureValue);
}

constructor(tempFile = "/sys/class/hwmon/hwmon1/temp1_input") {
        super();

        console.log("current temperature: " + Utils.readFile(tempFile));

        Utils.monitorFile(tempFile, (file) => {
            this.#onChange(file);
        });

        this.#onChange(tempFile);
}
```

Log output:
```log
❯ ags
Gjs-Console-Message: 01:47:51.554: current temperature: 47125

Gjs-Console-Message: 01:47:51.554: temperature-value changed: 47125
```

`this.#onChange` only gets called once. It does not receive events through `Utils.monitorFile`.

Does the monitor get garbage collected once the execution of the block finishes?

**Comment by Aylur** [comment]
some system files cannot be monitored

**Comment by Aylur** [comment]
you can also see this behavior using `inotifywatch`

**Comment by MaxiHafer** [comment]
Thank you for the clarification. It seems like most of the files in `/sys` and `/proc` cannot be monitored, as they are provided by `sysfs` and their content is determined at the time of access as per `inotify` documentation.

**Comment by MaxiHafer** [comment]
Sorry to necro this. Maybe a small disclaimer in the custom service example would be advisable. The use of `/sys/class/brightness` in the example is a little bit misleading, as it encourages users to use other pseudo filesystems which are probably provided by `sysfs` and thus cannot be monitored.

I opened a pull request for the docs. https://github.com/Aylur/ags-docs/pull/22
