### ISSUE TITLE
keymode exclusive doesnt grab device, and hyprland shortcuts keep working

### ISSUE THREAD

**Issue by almostnobody** [Aylur/ags#350]
i think that grabbing needs to be called explicitly in my case(i want to make sure that menu i open has ability to have any shortcuts regardless of the global ones.

https://docs.gtk.org/gdk3/method.Seat.grab.html

https://gjs-docs.gjsify.org/classes/Gdk_3_0.Gdk.Device.html#grab

seems like this is what im trying to do, but i cannot figure out how its done with js lib

questions:

 - does keymode: "exclusive" supposed to grab device/seat?
 - any plans to support such a mode?

**Comment by Aylur** [comment]
I don't know about the implementation details of `keymode` its just calling the `gtk-layer-shell` method
In my experience, keybindings of the compositor won't be caught layer shells, not sure if its doable

**Comment by Aylur** [comment]
life happened and I got kind of busy
a few widget subclasses are left to do on Astal, aswell as the wiki
I find `gtk4-layer-shell` to be a but unstable and it crashed on me a few times, so I don't think I'll be switching to it soon, but I do plan to maintain both Astal and AGS
