### ISSUE TITLE
hoverLost event callback is never invoked

### ISSUE THREAD

**Issue by coolstrong** [Aylur/ags#351]
I would like to implement closing popups on losing hover with some debounce, as I am aware there is no non-hacky way to implement click-away (and I don't like it anyway). But it seems that `hoverLost` event is broken - no matter whether it is `EventBox` or `Button`, the event is never fired. Simplest example print nothing when cursor leaves button:

```js
Widget.Button({
  label: "123",
  onHoverLost: () => print("hover lost"),
})
```
Tried either with stable and git version hosted on aur.

Are there any pitfalls when working with that event?

**Comment by Aylur** [comment]
`onHoverLost` needs the window to still have focus, you can workaround it by connecting to `leave-notify-event`
```js
Widget.Button({
    setup: self => self.on("leave-notify-event", () => {
        // instead of on_hover_lost
    })
})
```
