### ISSUE TITLE
Update "First Widgets" section of the wiki

### ISSUE THREAD

**Issue by Davido264** [Aylur/ags#353]
I recently started to learn ags, I read the wiki and viewed some configs. 

I found that the  _"First Widgets"_ section of the wiki says that the content of `config.js` contains:
```js
App.config({
    windows: [
         ...
    ]
})
```
But in some configs I saw, the content of `config.js` contains:
```js
export default {
     windows: [
         ...
    ]
}
```
Both of them work.

In adition, when using an lsp for type checking, `App.config` gives an error due  to `config` not specified as a property on the type `App`.

I think it would be a good idea to update the wiki and state that the configuration can be set with `export default {}` as an alternative to `App.config({})`

**Comment by Aylur** [comment]
> In adition, when using an lsp for type checking, App.config gives an error due to config not specified as a property on the type App

this is either because your ags version is out of date, or you are using nix, and your types are out of date

its not an alternative, `export default {}` has been deprecated in favor of `App.config` in 1.8.0, which ags should warn you about
