### ISSUE TITLE
Stack seems to prioritize showing box widget over other widgets

### ISSUE THREAD

**Issue by TheRiceCold** [Aylur/ags#359]
`ags version`: 1.8.0

I notice this issue when I was writing this [script](https://github.com/TheRiceCold/kaizen-widgets/blob/e7e75f9f9969dea07f8378a528469e96524daf11/windows/bar/widgets/media/Stack.ts). The code below is just a short sample.

``` js
export default () => Widget.Stack({
  // shown: 'child1', // This doesn't help
  transition: 'slide_up_down',
  children: {
    child1: Widget.Label('Test label'),
    child2: Widget.Box([ ])
  },
  // setup: self => self.shown = 'child1' // This also doesn't help
})
```

**Comment by h-banii** [comment]
hmmm I just managed to reproduce it with just labels (using this [example](https://aylur.github.io/ags-docs/config/widgets/#stack) from the wiki) so it might not be specific to Boxes...

```js
const stack = Widget.Stack({
  children: {
    'child1': Widget.Label('first child'),
    'child2': Widget.Label('second child'),
  },
  shown: 'child2', // it shows the first child...
})
```

Using a variable works as expected though
```js
const shownVariable = Variable('child2');

const stack = Widget.Stack({
  children: {
    'child1': Widget.Label('first child'),
    'child2': Widget.Label('second child'),
  },
  shown: shownVariable.bind(), // it shows the second child
})
```

**Comment by Aylur** [comment]
the gobject constructor might run the shown setter before the children, in which case setting it statically doesn't work
but I feel the `shown` property is usully bound to something, similar to `visible`, so this can be safely ignored, maybe its worth a mention on the wiki

**Comment by kotontrion** [comment]
If you want to set the shown property statically anyway, you might have luck setting it in the setup method, which should be the last thing executed. Didn't try this though.

```js
const stack = Widget.Stack({
  children: {
    'child1': Widget.Label('first child'),
    'child2': Widget.Label('second child'),
  },
  setup: self => {
    self.shown= 'child2'
  }
})
```

**Comment by TheRiceCold** [comment]
I expect the child1(Label) to show up first without using `shown` statically or dynamically, but it always shows the child2(Box) first so I what I did is change child2 to EventBox and it worked.

``` js
Widget.Stack({
  children: {
    'child1': Widget.Label('first child'),
    'child2': Widget.EventBox({ }), // does not force itself to show up first unlike box widget
  }
})
```

**Comment by TheRiceCold** [comment]
> If you want to set the shown property statically anyway, you might have luck setting it in the setup method, which should be the last thing executed. Didn't try this though.
> 
> ```js
> const stack = Widget.Stack({
>   children: {
>     'child1': Widget.Label('first child'),
>     'child2': Widget.Label('second child'),
>   },
>   setup: self => {
>     self.shown = 'child2'
>   }
> })
> ```

I've tried that but the box(child2) still forces itself to show up first.

**Comment by TheRiceCold** [comment]
> hmmm I just managed to reproduce it with just lables, so it might not be specific to Boxes...
> 
> ```js
> const stack = Widget.Stack({
>   children: {
>     'child1': Widget.Label('first child'),
>     'child2': Widget.Label('second child'),
>   },
>   shown: 'child2', // it shows the first child...
> })
> ```
> 
> Using a variable works as expected though
> 
> ```js
> const shownVariable = Variable('child2');
> 
> const stack = Widget.Stack({
>   children: {
>     'child1': Widget.Label('first child'),
>     'child2': Widget.Label('second child'),
>   },
>   shown: shownVariable.bind(), // it shows the second child
> })
> ```

I'm trying to show child1 first, but child2(Box) forces itself to show up first. It worked when I replace Box with EventBox.

**Comment by GuessWhatBBQ** [comment]
> the gobject constructor might run the shown setter before the children, in which case setting it statically doesn't work but I feel the `shown` property is usully bound to something, similar to `visible`, so this can be safely ignored, maybe its worth a mention on the wiki

It definitely should be mentioned on the wiki. The example for [stacks](https://aylur.github.io/ags-docs/config/widgets/#stack) also make use of them in the non-functional way. I was under the impression that stacks don't work on my system for some reason after directly pasting code from the wiki.
