### ISSUE TITLE
links in label

### ISSUE THREAD

**Issue by kotontrion** [Aylur/ags#364]
you can use links in labels by using the `<a>`tag. But this tag is not part of Pango markup and therefore it isn't recognized as valid markup and `GLib.markup_escape_text`is used to sanitize the text, even though it would be valid.

currently this can be circumvented by using the set_markup method to set the labels text like this:
```js
Widget.Label({
  ...
}).on("realize", self => {
  self.set_markup("This is a <a href=\"https://www.github.com\">test link</a>")
})
```

**Comment by whoslucifer** [comment]
I dont understand.  How do I impliment this
