### ISSUE TITLE
Workspace order in Hyprland (or: Being an idiot..)

### ISSUE THREAD

**Issue by Qpernicus** [Aylur/ags#370]
I just started trying out AGS and mimic my EWW bar (just a plain bar with workspaces and a few things like battery, idle inhibitor etc). And i cant wrap my head around a problem. Which has ALL to do with me being a complete novice at .. well anything in JS really.. 

I used this example: https://github.com/Aylur/ags/tree/main/example/simple-bar

Specifically this: 

```
function Workspaces() {
    const activeId = hyprland.active.workspace.bind("id")
    const workspaces = hyprland.bind("workspaces")
        .as(ws => ws.map(({ id }) => Widget.Button({
            on_clicked: () => hyprland.messageAsync(`dispatch workspace ${id}`),
            child: Widget.Label(`${id}`),
            class_name: activeId.as(i => `${i === id ? "focused" : ""}`),
        })))

    return Widget.Box({
        class_name: "workspaces",
        children: workspaces,
    })
}
```

and tried this as well: https://aylur.github.io/ags-docs/services/hyprland/

```
const Workspaces = () => Widget.EventBox({
    onScrollUp: () => dispatch('+1'),
    onScrollDown: () => dispatch('-1'),
    child: Widget.Box({
        children: Array.from({ length: 10 }, (_, i) => i + 1).map(i => Widget.Button({
            attribute: i,
            label: `${i}`,
            onClicked: () => dispatch(i),
        })),

        // remove this setup hook if you want fixed number of buttons
        setup: self => self.hook(hyprland, () => self.children.forEach(btn => {
            btn.visible = hyprland.workspaces.some(ws => ws.id === btn.attribute);
        })),
    }),
})
```

I dont have several monitors so it might work with the second method, but I would like to understand this. The problem is that the FIRST option shows the workspaces in order of ' startup'  and since my bluetooth is on WS 9, that shows as one of the first ones. But i would like just alphanumerical like in example 2. But example 2 doesn't adhere to my css file (which is probably because of naming of the several elements/class). 

So the issue here is ME but can someone help?

**Comment by andre-brandao** [comment]
Im also trying an ags config, heres how I got my workspaces working 
```js
function Workspaces() {
  const activeId = hyprland.active.workspace.bind("id");
  const workspaces = hyprland.bind("workspaces").as((ws) =>
    ws
      // remove scratchpads from the list
      .filter(({ id }) => id > 0)
      // sort by id
      .sort((a, b) => a.id - b.id)
      .map(({ id }) =>
        Widget.Button({
          on_clicked: () => hyprland.messageAsync(`dispatch workspace ${id}`),
          child: Widget.Label(`${id}`),
          class_name: activeId.as((i) => `${i === id ? "focused" : ""}`),
        })
      )
  );

  return Widget.Box({
    class_name: "workspaces",
    children: workspaces,
  });
}
```
Hope it helps

**Comment by Qpernicus** [comment]
> Im also trying an ags config, heres how I got my workspaces working
> 
> ```js
> function Workspaces() {
>   const activeId = hyprland.active.workspace.bind("id");
>   const workspaces = hyprland.bind("workspaces").as((ws) =>
>     ws
>       // remove scratchpads from the list
>       .filter(({ id }) => id > 0)
>       // sort by id
>       .sort((a, b) => a.id - b.id)
>       .map(({ id }) =>
>         Widget.Button({
>           on_clicked: () => hyprland.messageAsync(`dispatch workspace ${id}`),
>           child: Widget.Label(`${id}`),
>           class_name: activeId.as((i) => `${i === id ? "focused" : ""}`),
>         })
>       )
>   );
> 
>   return Widget.Box({
>     class_name: "workspaces",
>     children: workspaces,
>   });
> }
> ```
> 
> Hope it helps

Thanks! That works as intended at least. And i get what you do, so that helps ' translating'  as well.. thanks again!

I'll close for now, these are for issues not tutorials offcourse.
