### ISSUE TITLE
onClick triggers on mouse release, not on press

### ISSUE THREAD

**Issue by end-4** [Aylur/ags#38]
- The function assigned to `onClick` runs when the mouse button is released, not pressed
- This makes interaction feel slower
- Can we have `onClick` for mouse press and `onClickRelease` for release?

**Comment by Aylur** [comment]
I was actually thinking of removing that property altogether with `onSecondaryClick` and `onMiddleClick` props too, and just mention in the wiki how to use the Gtk native signal, but that is a better idea, for better DX.

in the meantime this how you can achieve this
```js
const button = {
    type: 'button',
    child: 'true',
    // 'button-release-event' for the release event
    connections: [['button-press-event', (widget, event) => {
        const { Gdk } = imports.gi;
        const button = event.get_button()[1]; // event is a Gdk.Event

        if (button === Gdk.BUTTON_SECONDARY)
            print('right click'); // assuming right handed mouse

        if (button === Gdk.BUTTON_MIDDLE)
            print('middle click');

        if (button === Gdk.BUTTON_PRIMARY)
            print('left click');
    }]],
};
```

**Comment by Aylur** [comment]
I have implemented your suggestion for button and eventbox, also updated the wiki
