### ISSUE TITLE
errors: gvc can not be cloned

### ISSUE THREAD

**Issue by alphanhp** [Aylur/ags#382]
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libgnome-volume-control/': The requested URL returned error: 503
fatal: clone of 'https://gitlab.gnome.org/GNOME/libgnome-volume-control' into submodule path '/home/ale/.cache/dots-hyprland/cache/ags/subprojects/gvc' failed
Failed to clone 'subprojects/gvc'. Retry scheduled
Cloning into '/home/ale/.cache/dots-hyprland/cache/ags/subprojects/gvc'...
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libgnome-volume-control/': The requested URL returned error: 503
fatal: clone of 'https://gitlab.gnome.org/GNOME/libgnome-volume-control' into submodule path '/home/ale/.cache/dots-hyprland/cache/ags/subprojects/gvc' failed
Failed to clone 'subprojects/gvc' a second time, aborting

meson.build:22:0: ERROR: git submodule failed to init

it seems like that gvc in gitlab has some trouble, could I have some way to be flexiblely dealing with this? Thx.

**Comment by Aylur** [comment]
its up now, so its probably resolved, but yes, node_modules and gvc are shipped with every release
you can download https://github.com/Aylur/ags/releases/download/v1.8.0/ags-v1.8.0.tar.gz and gvc is in there in the submodules folder
