### ISSUE TITLE
Window with 'on-demand' keymode doesn't let go keyboard focus

### ISSUE THREAD

**Issue by singul4ri7y** [Aylur/ags#386]
I got bar with an Entry widget on which I would like to type text. I am using 'on-demand' as keymode. I am facing several problems, notably: 
1) The bar does not let go of keyboard focus, even if I click another window.
2) The other buttons and widgets on bar can get focus if I press tab, showing an inner border, just like a normal window. It's annoying.

I am using Hyprland as my window manager. I am new to GTK in general. Am I missing something? Thanks in advanced.

**Comment by JustasPolis** [comment]
Maybe something related https://github.com/hyprwm/Hyprland/issues/4973 ?

**Comment by singul4ri7y** [comment]
@JustasPolis could be. With 'on-demand' keymode the keyboard focus enables just by hovering on the widgets and gets stuck since, unless you do some weird stuff like moving any window around to regain the focus on the windows. The problem could be anything; could be with AGS or wlr-layer-shell (protocols are still unstable) or most likely Hyprland.
