### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by Di-KaZ** [Aylur/ags#39]
Hi there ! 

Great work with ags looking forwad to use it,

How can one get intellisense on its config file using ags ?

Even better, is it possible to write it in typescript ?

Thanks in advance :)

edit : wrong repo, my bad

**Comment by Aylur** [comment]
I don't think it's possible to get intellisense right now, since you are essentially working with plain js obsects.
If you want to use typescript I would have a line in config.js that would run `tsc` before importing modules.

I have some plans for ags v1 where instead of passing plain objects you would pass them with a function call like
```js
// instead of this
const button1 = ags.Widget({
  type: 'button',
  onClick: () => {},
  child: { type: 'box', children: [/* widgets*/] }
});

// you would do this
const button2 = Button({
  onClick: () => {},
  child: Box({ children: [/* widgets */] )}
});
```
and with this, it would be possible to import function definitions and therefore have intellisense

**Comment by Aylur** [comment]
But for user defined widgets I am not sure how intellisense would be achieved, since `imports`  is not recognized like `import`, at least not on whatever lsp I have

**Comment by Di-KaZ** [comment]
That would be really cool to be able to get intellisense, your proposed syntax looks great

I saw some libs for gjs that can be used to generate typing for it maybe, you can benefit from it

Thank you for your answer

**Comment by Aylur** [comment]
Just saw gnome migrate to es modules. I will do the same and the import problem will be solved too

**Comment by Suyashtnt** [comment]
Any progress on the migration to ESM? Has it potentially improved typings?

**Comment by Suyashtnt** [comment]
> Custom defined widgets are automatically inferred, since they are just functions, but the builtin widgets don't have type definitions yet, JsDoc might be better than typescript types, since most people are not using tsserver, but I don't have the patience to write them manually

you can import dts files in jsdoc. Maybe using https://github.com/Rich-Harris/dts-buddy to create a dts file and shipping that as a downloadable to put into your ~/.config/ags file could be a good idea

**Comment by nenikitov** [comment]
Here is [`ags.ts`](https://github.com/Aylur/ags/files/12555193/ags.txt) file I made for my config to get intellisense. I have it in the `.config/ags`.

 This file is incomplete: there are TODOs left and I didn't cover all widget properties.

**Comment by Aylur** [comment]
https://github.com/Aylur/ags/commit/11414ffef205062bd4cdea3e5d717acb32996551

**Comment by Eclextic** [comment]
@Aylur 
So how exactly does this now work?
I pulled the changes... Nothing changed? No Intellisense?

Could you please elaborate on why this was closed?

**Comment by Aylur** [comment]
****

**Comment by Aylur** [comment]
Didn't mean to reopen, I just missclicked
Checkout the typescript wiki page, you need to grab tsconfig.json, package.json and run the setup script that will grab the typedefinitions
