### ISSUE TITLE
System tray wont start when imported twice or randomly when reloading

### ISSUE THREAD

**Issue by coolstrong** [Aylur/ags#393]
If I try to import system tray from two different files, service appears empty and produces the following line in console:

> Another system tray is already running

This also happens when I reload ags (`ags -q && ags`), especially when I do it after connecting/disconnecting external monitors. 

Is there a way to kill the running system tray?

**Comment by Aylur** [comment]
only one system tray service can be running at once
you are either running a rouge instance of ags with a different busname, or some other tool like waybar
