### ISSUE TITLE
Missing inverted property for Widget.Slider.

### ISSUE THREAD

**Issue by minhnbnt** [Aylur/ags#394]
In eww, there is flipped property which allows rotating the scale to reverse its direction.
```
(defwidget metric [value onchange class]
	(box :orientation "v"
	     :class class
	     :halign "center"
	     (scale :min 0
                    :max 101
	            :orientation "v"
	            :flipped true ; HERE
	            :value value
	            :onchange onchange)))
```
How can I get the same functionality in ags?

**Comment by Aylur** [comment]
you are looking for `inverted: true`
https://gjs-docs.gnome.org/gtk30~3.0/gtk.range#property-inverted
