### ISSUE TITLE
Refactor Code From Aylur/dotfiles to AGS

### ISSUE THREAD

**Issue by P9EA5Y** [Aylur/ags#395]
Certain services and widgets from [Aylur/dotfiles](https://github.com/Aylur/dotfiles) can serve a more general use case, is it possible to include some of which in AGS?

**Comment by Aylur** [comment]
They are somewhat tailored to my specific needs and all of them work with an external library
I don't want to include any service in ags that depends on an external binary call

**Comment by P9EA5Y** [comment]
> They are somewhat tailored to my specific needs and all of them work with an external library
> 
> I don't want to include any service in ags that depends on an external binary call

Certain widgets such as the bar, control center, and application launcher could have services requiring external services stripped, with just a minimal framework to build around.
