### ISSUE TITLE
Build failing on Arch

### ISSUE THREAD

**Issue by imryanide** [Aylur/ags#4]
Trying to build this on Arch, and after meson install -C build, i get error TS2307 Cannot find modules error

**Comment by Aylur** [comment]
after following the installation from the wiki, do you still have an issue?

**Comment by mistertuna93** [comment]
Hey there,
I am experiencing a similar issue I did
Git clone recursive
npm install
meson setup build
meson install -C build.

The error returned is TS7006 implicit type is any for device, res, ap, _s, result, device.

I have tried deleting and repulling the repo a few times to no avail. Any ideas?

Thanks in advance, 
Charles

**Comment by thyeun** [comment]
@mistertuna93 try clone the repos with ```git clone --recursive```.
