### ISSUE TITLE
Make style property use relative pathing to the config file, not executable

### ISSUE THREAD

**Issue by Frontear** [Aylur/ags#40]
One complaint I have about the way ags seems to work the paths is that if its relative, its sourced from wherever ags was run. Now in my setup I run it through a shell executable with the PWD in $HOME, but I'd like to make my dotfiles flexible to all workloads, but I can't develop anything like that because of the way style works.

Using `style: "~/.config/ags/style.css"` causes ags to try and find the config in `$PWD/~/.config/ags/style.css`. I _have_ to use explicit pathing, but that breaks if I use a different user, since `$HOME` won't work there. 

One solution would be to make pathing relative to the config, which iirc is also how eww works (if we want to bring up parity with the inspiration project). Another would be to allow `~`, `$HOME`, or just `.config/ags/style.css` as values that can just work as is. There's probably more solutions, and I'm open to any fix, I'd just like some clarity on this choice of path resolving.

**Comment by Aylur** [comment]
I meant style to take an absolute path, because I didn't even check if it could take a relative path
there are multiple solutions for this using GLib
```js
// this is in utils.js
export const USER = GLib.get_user_name();
export const CONFIG_DIR = `${GLib.get_user_config_dir()}/${pkg.name}`;

// you can import them like this
ags.Utils.USER
ags.Utils.CONFIG_DIR

// so
style: ags.Utils.CONFIG_DIR + '/style.css'
```

you could also set environment variables and get them with GLib
```js
const { GLib } = imports.gi;
print(GLib.getenv('USER'));
print(GLib.getenv('HOME'));
```

**Comment by Frontear** [comment]
ah okay, my js inexperience has shown itself, glad to see fixes then, thanks
