### ISSUE TITLE
Ability to disable notification daemon

### ISSUE THREAD

**Issue by TeChn4K** [Aylur/ags#402]
Hello there,

Is there a way to completely disable the AGS notification daemon?

I would like to keep my current daemon (Dunst), but it can't start because of AGS taking the seat.

```
Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'com.github.Aylur.ags' with PID '28725'.
```

Thanks!

**Comment by kotontrion** [comment]
the notification daemon is started as soon as you import the notifications service. So if you don't want to use ags as the notification daemon, just don't import the notifications service.

**Comment by TeChn4K** [comment]
Oh thanks for the clarification
I had a useless import of the notification service lying around.
