### ISSUE TITLE
Gentoo installation - Cant get overview

### ISSUE THREAD

**Issue by JaKooLit** [Aylur/ags#419]
Hello.. Well Ive been trying for days and I couldnt figured out issue 

I have it installed on my Gentoo Desktop with global ~amd64
![ags-overview](https://github.com/Aylur/ags/assets/85185940/9b253ec6-1a0c-4eac-a24e-5a0f4788116f)

I have on both my mini-PC and laptop , both no-multilib feature and this how it looks
![ags-overview-no-multilib](https://github.com/Aylur/ags/assets/85185940/33947610-79d9-4b7d-996c-ef13ae0487c0)
I have X on my make.conf so its not an X issue..

Would like to know some ideas..

thanks

On nixos, I have the issue issue but later on found out that I have to enable the xservices.. phew

**Comment by Aylur** [comment]
can't really help you without any error log or source code
and I don't think xservices would affect anything, its just gtk, layer shells and some backend code which is faulty or the user code doesn't handle some error case which is most likely

**Comment by JaKooLit** [comment]
![Screenshot_15-May_01-25-45_19975](https://github.com/Aylur/ags/assets/85185940/a471421a-33d9-4834-8b08-b83cd57c501b)
thanks for your reply.... here is what is showing

**Comment by JaKooLit** [comment]
I found the issue. Apparently the overview code which was shared to me needs xrandr

installing xrandr fixed the issue

Sorry to bother you. I should have check the code first
