### ISSUE TITLE
Notification sound at notification popup

### ISSUE THREAD

**Issue by RipDr19** [Aylur/ags#422]
Is there any way we can enable notification sound to be played anytime a notification pops up or a device is connected?

**Comment by kotontrion** [comment]
ags does not have this feature builtin.
You can however play a sound yourself when a new notification is received. The easiest way to this is by using some external tool like mpv with Utils.execAsync.

**Comment by keifufu** [comment]
To add to kotontrion's comment, both pulseaudio and pipewire have tools to play audio from a file, `paplay` and `pw-play` respectively.
