### ISSUE TITLE
Is it possible to get colors defined in a GTK theme?

### ISSUE THREAD

**Issue by Freemason-12** [Aylur/ags#424]
I wanted to make my window borders match my GTK theme accent color, and in order to do that, I thought I need to access something like `@themebg` or `@themefg` colors.
Is it possible on AGS (or maybe GJS)?
I'm using sway, I was able to script away the behavior of workspace widget, and an active window name widget by using sway IPC

**Comment by Aylur** [comment]
your default gtk theme variables are all available in css
have a look at the [example bar's css](https://github.com/Aylur/ags/blob/main/example/simple-bar/style.css)
to have a list of available variables you should refer to the source of the gtk theme you are using by default

**Comment by Freemason-12** [comment]
I know that they're available on CSS, but how can I apply those css colors into a sway window border, not GTK window or a widget?
