### ISSUE TITLE
inverted circular progress bar values act wierd

### ISSUE THREAD

**Issue by tms-meister** [Aylur/ags#428]
when inverted is set to true, the start_at and end_at values for a circular progress bar don't make sense with what is actually being displayed.

**Comment by sungyoonc** [comment]
Can you check if https://github.com/Aylur/ags/pull/423 solves it?

**Comment by tms-meister** [comment]
yup, seems to be fixed.
I started working on a fix myself before I saw yours lol, I guess I'll just wait for this to get merged now
