### ISSUE TITLE
`App.windows` is always empty

### ISSUE THREAD

**Issue by realSaltyFish** [Aylur/ags#437]
No matter what window I create and add, `App.windows` is always empty. Is this supposed to be the correct way to retrieve all windows?

Minimal config file:
```javascript
App.add_window(Widget.Window({}))
console.log(JSON.stringify(App.windows))
```

**Comment by h-banii** [comment]
I never had to use it before so I don't know if this is the best way, but `get_windows` should work

```js
App.add_window(Widget.Window({}));
console.log(App.get_windows());
```

Or use `App.config`
```js
App.config({
  windows: [
    Widget.Window({
      name: 'yay',
    })
  ]
});

console.log(App.windows);
```

**Comment by Aylur** [comment]
it can be a bit confusing `App.add_window` is the default function of Gtk.Application
the function you are looking for is `App.addWindow` in camelCase
