### ISSUE TITLE
network service doesn't notice when Ethernet appears

### ISSUE THREAD

**Issue by agriffis** [Aylur/ags#443]
My laptop doesn't have Ethernet, but my dock does. This means that I have an `NM.DeviceEthernet` that comes and goes.

When I plug in my dock, ags doesn't handle the change. This is because the network service only calls `new Wired(this._getDevice(NM.DeviceType.ETHERNET) as NM.DeviceEthernet)` once when it is initialized.

I think that handling this properly would involve some rewriting in `network.ts`. Is it worth digging into since you're already working on the rewrite in vala?

**Comment by Aylur** [comment]
any help with network is appreciated, since its still nm, I can just translate any typescript to vala once I get to it
