### ISSUE TITLE
ags does not exit subprocesses upon quitting

### ISSUE THREAD

**Issue by keifufu** [Aylur/ags#444]
Given the following variable:
```ts
const track = Variable("", {
  listen: "wnpcli metadata -f '{{artist}} - {{title}}' -F",
});
```

when running `ags --quit` wnpcli remains running.

I know i can use `track.stopListening()` to exit the process but I could not find a way to hook/listen to --quit.

**Comment by Aylur** [comment]
subprocesses are definitely not left unhandled by glib
are you sure the `wnpcli` process you is a child process of ags?

**Comment by keifufu** [comment]
This happens with playerctl or and process that keeps open and prints to stdout too
