### ISSUE TITLE
Question about Widget.Window

### ISSUE THREAD

**Issue by Davido264** [Aylur/ags#445]
I want to create a window that can be detected by hyprland, and then send it to a special workspace. Is this possible using ags?

**Comment by faileon** [comment]
I was wondering the same recently and

**Comment by kotontrion** [comment]
Not that you can't use some AGS specific things like hook and bind with Gtk.Window directly.

If you want to use them you can add that by subclassing it yourself.

```js
const window = Gtk.Window({
  ...
})

const RegularWindow = Widget.subclass(Gtk.Window)
const window2 = RegularWindow({
  ...
})

//does not work
window.hook(...)
window.keybind(...)


//works
window2.hook(...)
window2.keybind(...)

```

**Comment by Davido264** [comment]
It works, thanks :3
