### ISSUE TITLE
Ags not starting

### ISSUE THREAD

**Issue by afreireo** [Aylur/ags#447]
after update all system, arch linux

(com.github.Aylur.ags:6378): Gjs-Console-CRITICAL **: 01:40:26.167: Gio.IOErrorEnum: Could not connect: No such file or directory
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
_socketStream@resource:///com/github/Aylur/ags/service/hyprland.js:140:34
message@resource:///com/github/Aylur/ags/service/hyprland.js:151:43
Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:102:41
@resource:///com/github/Aylur/ags/service/hyprland.js:321:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by paindespik** [comment]
i have this problem, how did you solve it please ?

**Comment by afreireo** [comment]
> i have this problem, how did you solve it please ?

just reinstalling it
