### ISSUE TITLE
Example NotificationPopups issue

### ISSUE THREAD

**Issue by rafaeljacov** [Aylur/ags#450]
I added the example to my config. but for some reason, when the very first popup is spawned, the default icon is showed even if there is and image associated with the notification, but the issue doesn't persist on the next popups. I used spotify to test this

**Comment by Aylur** [comment]
its an issue with spotify, whenever you start it up, its inital mpris values are empty and so are its notifications
if it annoys you you could force it by skipping a song the first time you launch it which will set its values
```js
// you can put this code anywhere
const mpris = await Service.import("mpris")
mpris.connect("player-added", (_, bus) => {
  if (bus.includes("spotify") {
    mpris.getPlayer(bus).next()
    mpris.getPlayer(bus).previous()
  }
})
```
