### ISSUE TITLE
Warning: Failed to connect to context

### ISSUE THREAD

**Issue by ThreadyTick4475** [Aylur/ags#453]
Upon trying to start ags with the bar example(this issue does not occur when using the config generated by `ags init`) in nixos 24.05 with hyprland, the bar does not display and the following warnings are printed:

- `Failed to connect to context: Connection refused`
- `JS ERROR: Error: Requiring DbusmenuGtk3, version none: Typelib file for namespace 'DbusmenuGtk3' (any version) not found`

After about five seconds the first error occurs a second time. These errors persist after explicitly installing [libdbusmenu-gtk3](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/libraries/libdbusmenu/default.nix).

**Comment by EternalBlissed** [comment]
Having the same issue, there is a solution involving adding an overlay to fix it in https://github.com/NixOS/nixpkgs/issues/306446

**Comment by Aylur** [comment]
its an issue with the nixpkgs package, you can use the flake instead
