### ISSUE TITLE
new dependency required for Arch Linux - glib2-devel

### ISSUE THREAD

**Issue by JaKooLit** [Aylur/ags#459]
After recent update with Arch Linux,

it seems new depency required is glib2-devel

during build process, it is looking for glib2

checked system, glib2 is installed

tried to install glib2-devel, and it successfully built and installed

![rn_image_picker_lib_temp_6a0fc6d8-4c25-4979-8f67-46128c153c93](https://github.com/Aylur/ags/assets/85185940/1ac5b8ca-1fe2-493c-98d5-450739afeef7)

**Comment by kotontrion** [comment]
glib2 was split into separate glib2 and glib2-devel packages only recently.
somehow i missed this change.

It is fixed now. Thanks for reporting.
