### ISSUE TITLE
can labwc work with your project

### ISSUE THREAD

**Issue by daktras420** [Aylur/ags#46]
i like the look would love to see a application or start menu. but can i use your project with labwc current labwc for example doesn't support multiple desktops aka workspaces? help info pointers or alternative config and need files would be a huge help.
i have kanashi for my wallpaper manager it uses waybg to load the wallpaper as a backend. mako for events and libindecator for tray support for different wayland bar and panles use it. wire plumber and pipewire is my sound network manager is for network and bauh if my gui application manager. i want to switch to eww instead of waybar and rofi. please help?

**Comment by Aylur** [comment]
Ags uses gtk-layer-shell to display on wayland layer shell. If labwc supports wlr-layer-shell it will work

**Comment by daktras420** [comment]
When i configure it since labwc doesn't support multiple workspaces or
desktops i will try to remove the desktop switcher from the panel example
but some suggestions of how to do a menu. I am currently using keybindings
to wofi to bring up my application menu and power menu would like to have
buttons on the bar to do the same thing any snippets code wise would be a
huge help. Thank you in advance. I did read the documentation but not sure
how to use it for what i whant to do sorry for my lack of knowledge.

**Comment by daktras420** [comment]
Awsome and thank you ill compile and install once there done please keep me
posted?

**Comment by daktras420** [comment]
Also an idea for theme not sure if you'd like the idea but something like
the below link so there's a few options... I made a space like theme
between backgrounds and launcher theme scripts and exicuting them via
keybindings, but had to use themes that didn't use workspace switcher or it
crashed. Because labwc doesn't support multiple desktops or workspaces no
wlr-workspace integration yet.

https://github.com/adi1090x/rofi
