### ISSUE TITLE
NixOS: GVC refuses connection when using PipeWire

### ISSUE THREAD

**Issue by arunoruto** [Aylur/ags#466]
I am currently running AGS with hyprland using NixOS. I have installed it using flakes as described by the [vimjoyer video](https://www.youtube.com/watch?v=GvpTUKaXqNk). I wanted to have a volume indicator, but it seems like it can't find a connection to the emulated PulseAudio server using PipeWire. My NixOS config for sound looks like this:
```nix
sound.enable = lib.mkForce false;
hardware.pulseaudio.enable = false;
security.rtkit.enable = true;

services.pipewire = {
  enable = true;
  audio.enable = true;
  alsa = {
    enable = true;
    support32Bit = true;
  };
  pulse.enable = true;
  jack.enable = true;
};
```

I am not sure if I am missing something? the `services.pipewire.pulse.enable = true` line should provide a simulated pulse server.

**Comment by Aylur** [comment]
I think you also need `hardware.pulseaudio.enable = true`

**Comment by miathetrain** [comment]
I'm also using Hyprland on NixOS while using PipeWire. AGS Audio service works perfectly fine for me, without having pulseaudio enabled

**Comment by arunoruto** [comment]
> I think you also need `hardware.pulseaudio.enable = true`

If pulseaudio is enabled, it is in conflict with pipewire. I am not sure what I did now, but it seems to work. Maybe it took a few reboots for things to click nicely 😅 
I will close this issue for now, but if I notice some problems again, I will open a new up!
