### ISSUE TITLE
(intermediate value).runAsync is not a function error when running ags

### ISSUE THREAD

**Issue by Hyppothalamus** [Aylur/ags#469]
I have followed the install instructions from the wiki for building from source because there is no package for debian 12.

Everything works as expected. I can create the config directory with ags --init

But when I try to run with the example config from the docs.

```js
const myLabel = Widget.Label({
    label: 'some example content',
})

const myBar = Widget.Window({
    name: 'bar',
    anchor: ['top', 'left', 'right'],
    child: myLabel,
})

App.config({ windows: [myBar] })
```
I get an error saying .runAsync is not a function.
This is the stacktrace:
```
ags

(com.github.Aylur.ags:61143): Gjs-CRITICAL **: 18:21:29.803: JS ERROR: TypeError: (intermediate value).runAsync is not a function
main@resource:///com/github/Aylur/ags/main.js:134:20
@file:///usr/local/bin/ags:36:31


(com.github.Aylur.ags:61143): Gjs-CRITICAL **: 18:21:29.803: Module file:///usr/local/bin/ags threw an exception
```

I am running debian 12 with sway window manager installed from package manager
this is sway version 1.7

Is there anythin I can do to fix this issue?

If you need anything else from me just comment I will try to reply ASAP

Already thanks for the help :)

**Comment by Aylur** [comment]
I am guessing debian ships an older version of gjs
ags needs gjs >1.77
`gjs --version`

**Comment by Hyppothalamus** [comment]
My gjs version was indeed lower than what it should be.

I am going to try apt pinning for now so I can install gjs 1.77 or higher.

For anayone having the same issue on debian and wondering how to apt-pin I am gonna follow this [guide](http://jaqque.sbih.org/kplug/apt-pinning.html)

Thanks for the quick reply

**Comment by Hyppothalamus** [comment]
with apt-pinning I was able to install gjs 1.80.2 and able to run ags.

Thanks for the help.
