### ISSUE TITLE
Status Bar lists workspaces out of order

### ISSUE THREAD

**Issue by bratfizyk** [Aylur/ags#470]
According to docs, to Workspaces part of the Status bar is based on the output of `hyprctl workspaces -j`.

I haven't checked its docs, but from my experience it lists workspaces based on the time they were created, without sorting. e.g.

![image](https://github.com/Aylur/ags/assets/10075099/5bf5f805-d89c-4477-a9e1-0889e7af3c78)

As a solution, it is possible to add sorting to the Widget, e.g. something like this:

```js
function Workspaces() {
    const activeId = hyprland.active.workspace.bind("id")
    const workspaces =
        hyprland.bind("workspaces")
            .as(ws => 
                ws.sort(({id:a},{id:b}) => a - b)
                .map(({ id }) => Widget.Button({
                    on_clicked: () => hyprland.messageAsync(`dispatch workspace ${id}`),
                    child: Widget.Label(`${id}`),
                    class_name: activeId.as(i => `${i === id ? "focused" : ""}`),
                }
            ))
        )

    return Widget.Box({
        class_name: "workspaces",
        children: workspaces,
    })
}
```

I'm happy to create a PR for this it this is what you want.

**Comment by yari-dog** [comment]
there is the option to just write your own workspace service to do this for you. I wrote a wrapper for the notification service to help me filter out specific notifications from specific places

**Comment by Aylur** [comment]
this is intended
the array has to be sorted by the end user, just like you did

**Comment by bratfizyk** [comment]
Hi @Aylur.
Thanks for responding. I've adjusted it to my needs as you suggested.
Cheers!
