### ISSUE TITLE
Strange artifacts appear on bar at random

### ISSUE THREAD

**Issue by nonetrix** [Aylur/ags#471]
If you look closely you can see a strange pixel formation on the bar, this seems to appear seemingly randomly and also appears on both of my monitors at the same time in which I have two bars. Only way to remove it is if text over writes where the pixels are placed trying to move my cursor over it or a window does nothing. This makes me rule out Hyprland or hardware failure mostly, but it could still be either of those. I am honestly just curious if anyone has encountered this and what it could be. First time I had this it was just one random red pixel, but red or orange seems to be the theme
![2024-06-23-144644_hyprshot](https://github.com/Aylur/ags/assets/45698918/78d685bb-0378-49b3-9df5-cf2699c7d495)
![2024-06-23-144644_hyprshot](https://github.com/Aylur/ags/assets/45698918/a3a602d8-24ff-442e-ab85-8f55bd6222fa)
Also, I haven't noticed any system stability issues really besides ones that I know are software bugs. I can stress my GPU for hours and nothing out of the ordinary really

**Comment by Aylur** [comment]
check it with the inspector to make sure its not a widget you placed there

**Comment by nonetrix** [comment]
Will if it comes up again comes up once every blue moon seemingly

**Comment by nonetrix** [comment]
I found way to reproduce it! Get a bunch of windows all with different titles but sameish length then quickly move between them updating the window title widget, eventually you will get a red pixel. I was able to do it with one window named `cava`, "btop", and finally `~` like this 
![image](https://github.com/user-attachments/assets/9bef7343-de97-4268-96f6-3381ddf23ada)
then hovering over another window with a bigger title will remove it
![image](https://github.com/user-attachments/assets/09f8073f-9923-40a9-aeb6-d86d573bc6f5)
I will give my config later but it's a mess for sure I added a bunch of white space to visually separate code as I was working on it and generally it's hacked together and has some bugs

**Comment by nonetrix** [comment]
Also media player widget timestamp does it as well

**Comment by TeChn4K** [comment]
I seem to be having the same issue: weird colored pixels artifacts.
They disappear on mouse hover.

Look at the battery indicator, the name of the day and the number of minutes on the clock.

Before mouse hover
![screenshot_2024-10-18_10-48-44](https://github.com/user-attachments/assets/ea86bb1d-53bd-4c47-b4ba-ff587df7d223)

After mouse hover
![screenshot_2024-10-18_10-53-40](https://github.com/user-attachments/assets/a255a9bd-e5c3-4bfb-a0b2-57491726cfdb)

**Comment by nonetrix** [comment]
Seems similar, I suspect it to be a font rendering bug in GTK version this uses. Am I right or nah?
