### ISSUE TITLE
[Issue]  AGS v1.8.2 error on startup fin NIXOS unstable  CssErrorProvider expected a length / junk at end of value for margin

### ISSUE THREAD

**Issue by dwilliam62** [Aylur/ags#475]
Running NIXOS   Attached configuration. 
[diag.txt](https://github.com/user-attachments/files/15956074/diag.txt)

 On startup I see this error 
![image](https://github.com/Aylur/ags/assets/129223418/c35883d4-3f44-4b1c-9356-bd50c2e3e953)

With AGS running I try ags -t overview 
Where I see these errors 

![image](https://github.com/Aylur/ags/assets/129223418/e1cbfb98-3df7-468f-8317-6c33579ec219)

 What gets outputted is:
![image](https://github.com/Aylur/ags/assets/129223418/17549a77-b477-4e35-aa36-c2d140794f27)

I am using the hyprland dots from  
https://github.com/JaKooLit/Hyprland-Dots

 Which in arch, ubuntu, debian all work fine.   In NIXOS for the author AGS works fine as well

It seems like I am missing a package ?  

Any help or suggestions would be appreciated

**Comment by dwilliam62** [comment]
JaKookLit suggested I also add glib  which seems to have resovled the Upower issues no other change 
![image](https://github.com/Aylur/ags/assets/129223418/9d856eb5-4cf4-463f-bbb1-0bd94b4c2de1)

There is a addional message now about Junk at end of margin

**Comment by Aylur** [comment]
contact the author of the dotfiles, its an issue with their css

**Comment by dwilliam62** [comment]
Except it works in his NIXOS environment just fine.
