### ISSUE TITLE
Workspaces get stuck sometimes

### ISSUE THREAD

**Issue by DADA30000** [Aylur/ags#477]
Check top left corner
https://drive.google.com/file/d/1TQB0XmybFs6L89wUa13FpzC2pG_DSKY3/view?usp=sharing

**Comment by enk-it** [comment]
This looks like [https://github.com/Aylur/ags/pull/465](url)
You can try building ags with that pr yourself and check if it works.

**Comment by DADA30000** [comment]
Looked into it and I think it will fix my issue, I will check it later
