### ISSUE TITLE
Wireless network icon doesn't change when it's turned off

### ISSUE THREAD

**Issue by fadelior** [Aylur/ags#478]
The wireless icon doesn't change when I tried to turn off the wireless network. But when restarting, It will show that the wireless network is indeed off and when it started again, it does showing the icon stating that it has been turned on. Tried to turn it off again, it doesn't showed up

https://github.com/Aylur/ags/assets/78681226/f965e2d6-791f-4701-b1a2-b0b7d25c88ab

(For note: it's the default GTK icon)

Version: 
AGS: 1.8.2-2
NetworkManager: 1.48.2-1

**Comment by Aylur** [comment]
can't help you without source code
you are either not binding the property correctly or using hooks wrong

**Comment by fadelior** [comment]
seems I forgot about the source code
```
const network = await Service.import('network')
App.addIcons(`${App.configDir}/assets`)

const wifiIndicator = () => Widget.Icon ({
	className: 'icon',
	icon: network.wifi.bind('icon_name')
})

const networkIndicator = () => Widget.Stack({
    children: {
        wifi: wifiIndicator(),
        wired: Widget.Label({ label: 'wired' }),
        // vpn: 'vpn_'
    },
    shown: network.bind('primary').as(p => p || 'wifi'),
});

export default networkIndicator
```
It's basically the same code from the example

**Comment by fadelior** [comment]
is the issue still relevant? It seems you want to change the network service (?)

**Comment by Programeldev** [comment]
> seems I forgot about the source code
> 
> ```
> const network = await Service.import('network')
> App.addIcons(`${App.configDir}/assets`)
> 
> const wifiIndicator = () => Widget.Icon ({
> 	className: 'icon',
> 	icon: network.wifi.bind('icon_name')
> })
> 
> const networkIndicator = () => Widget.Stack({
>     children: {
>         wifi: wifiIndicator(),
>         wired: Widget.Label({ label: 'wired' }),
>         // vpn: 'vpn_'
>     },
>     shown: network.bind('primary').as(p => p || 'wifi'),
> });
> 
> export default networkIndicator
> ```
> 
> It's basically the same code from the example

This dont work for me too but I found solution from Aylur dotfiles, check this

`
const NetworkIndicator = () => Widget.Icon().hook(network, self => {
    const icon = network[network.primary || "wifi"]?.icon_name
    self.icon = icon || ""
    self.visible = !!icon
})
`

**Comment by fadelior** [comment]
Thanks, it worked!. It could be that I'm using the bind function incorrectly
