### ISSUE TITLE
How would I got about spawning the example for each monitor

### ISSUE THREAD

**Issue by Yaikava** [Aylur/ags#48]
How would I got about spawning the example bar for each monitor? Cannot figure how I would do that.
I know how to spawn more of the bars. Right now it launches on the monitor that I am on when launching ags. Do I need to like add some padding or something?

**Comment by Aylur** [comment]
by making it a function and calling it as many times as you want
```js
const bar = (monitor) => ({
    name: `bar${monitor}`, // make sure its still unique
    anchor: ['top', 'left', 'right'],
    exclusive: true,
    child: { /* stuff */ }
});

var config = { windows: [bar(0), bar(1), bar(2)] };
```

**Comment by Yaikava** [comment]
Thanks
I understand how to get more of them. But this just gets me 2 bars on 1 monitor. How can I move the 2nd bar to the other monitor?

**Comment by Yaikava** [comment]
Maybe am missing something obvious. Sorry if that is the case.

**Comment by Aylur** [comment]
my bad, forgot to add monitor to the attributes
you have to set the monitor property of a window to a number which is the id of the monitor you want it to appear on

**Comment by Yaikava** [comment]
ok, got it to work. Thanks

**Comment by Yaikava** [comment]
I will leave this here in case anyone needs it.
```
const bar = (monitor) => ({
    name: `bar${monitor}`, // make sure its still unique
    monitor,
    anchor: ['top', 'left', 'right'],
    exclusive: true,
    child: { /* stuff */ },
    monitor,
});

var config = { windows: [bar(0), bar(1), bar(2)] };
```
