### ISSUE TITLE
Chromium Notifications Show raw HTML

### ISSUE THREAD

**Issue by notthansen** [Aylur/ags#480]
### Discussed in https://github.com/Aylur/ags/discussions/479

<div type='discussions-op-text'>

<sup>Originally posted by **notthansen** June 28, 2024</sup>
![image](https://github.com/Aylur/ags/assets/75609068/0a6efb0f-5941-4b01-a152-fdda79af41d7)

Notifications from any chromium based browser from chromium,google chrome , vivaldi and even brave show notifications with the browser icon and some raw html script holding the link instead of a formatted preview text and an icon for the corresponding web app .Firefox notifications work just fine but I cant use it because it runs in a very skibidi way on my computer.

I have tried installing all these browsers from different aurs  , pacman and even snapd but the issue is still persistent so it has to be sth to do with how the notification daemon is rendering notifications from any chromium browser

Does anyone know how to fix this</div>

**Comment by kotontrion** [comment]
The icon is set by chromium, so if it decides to put its own icon there instead of the one of the web app, then there is nothing ags can do. This has to be addressed in chromium.
Chromium seems to out the link to the web app at the beginning of the notification text. This link is not rendered as a link, see issue #364 for more on that.

**Comment by notthansen** [comment]
> The icon is set by chromium, so if it decides to put its own icon there instead of the one of the web app, then there is nothing ags can do. This has to be addressed in chromium. Chromium seems to put the link to the web app at the beginning of the notification text. This link is not rendered as a link, see issue #364 for more on that.

I appreciate
