### ISSUE TITLE
Typescript Types aren't being (correctly?) recognized

### ISSUE THREAD

**Issue by TheAyes** [Aylur/ags#489]
I'm trying to use Typescript since I'm most comfortable with that, but after an init the types are extremly weird and even throw warnings in javascript. Essentially the props throw this error with the example bar (with the date and time):
```
Argument type
{   exclusivity: string,   anchor: string[],   name: string,   monitor: number,   child: Label<unknown> }
is not assignable to parameter type any
```
This applies to other widgets aswell. Effectively saying `X is not assignable to any`

While this is just a static analysis error it's still very distracting. Building I haven't tried yet since... Even if it builds, what's the point if everything I do is shown as an error.

The command I used to init was `ags --init --config ./config/ags/config.ts`

`tsconfig`
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "lib": [
      "ES2022"
    ],
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "noImplicitAny": false,
    "baseUrl": ".",
    "typeRoots": [
      "./types"
    ],
    "skipLibCheck": true
  }
}
```

![image](https://github.com/Aylur/ags/assets/68541335/de31dc62-4580-4414-a84d-e78cdd0c0df1)

**Comment by Aylur** [comment]
did the `types` directory correctly symlink when running `--init`?

**Comment by TheAyes** [comment]
It appears the language server wasn't running. I'm using typescript like always but never seen that the lsp just decided to turn itself off.

Anyway. Unrelated to your Project.
