### ISSUE TITLE
ags fails to build when following the installation guide from the wiki on ubuntu 24.04

### ISSUE THREAD

**Issue by lntcT** [Aylur/ags#490]
When following the "From Source" installation guide on the wiki ags fails to build and returns:

FAILED: src/tsc-output
/usr/bin/tsc --outDir /home/lntct/git/ags/build/tsc-out
../src/utils/binding.ts(9,5): error TS1139: Type parameter declaration expected.
../src/utils/binding.ts(9,16): error TS1005: ',' expected.
../src/utils/binding.ts(9,27): error TS1005: ',' expected.
../src/utils/binding.ts(10,10): error TS1005: ';' expected.
../src/utils/binding.ts(10,32): error TS1005: ',' expected.
../src/utils/binding.ts(10,37): error TS1005: ';' expected.
../src/utils/binding.ts(10,47): error TS1005: ';' expected.
../src/utils/binding.ts(11,1): error TS1109: Expression expected.
../src/utils/binding.ts(11,7): error TS1005: ')' expected.
../src/utils/binding.ts(11,17): error TS1005: ';' expected.
../src/utils/binding.ts(11,39): error TS1005: ';' expected.
../src/utils/binding.ts(21,5): error TS1139: Type parameter declaration expected.
../src/utils/binding.ts(21,16): error TS1005: ',' expected.
../src/utils/binding.ts(21,32): error TS1005: ',' expected.
../src/utils/binding.ts(22,10): error TS1005: ';' expected.
../src/utils/binding.ts(22,32): error TS1005: ',' expected.
../src/utils/binding.ts(22,37): error TS1005: ';' expected.
../src/utils/binding.ts(22,47): error TS1005: ';' expected.
../src/utils/binding.ts(23,1): error TS1109: Expression expected.
../src/utils/binding.ts(23,7): error TS1005: ')' expected.
../src/utils/binding.ts(23,17): error TS1005: ';' expected.
../src/utils/binding.ts(23,39): error TS1005: ';' expected.
ninja: build stopped: subcommand failed.
Could not rebuild /home/lntct/git/ags/build

**Comment by BenCassidy33** [comment]
I had this error and i solved it by updating my tsc to the latest version (5.5.3)

**Comment by lntcT** [comment]
> I had this error and i solved it by updating my tsc to the latest version (5.5.3)

Will test when i get home later today or tomorrow

**Comment by lntcT** [comment]
This appears to have been an issue on my end (my nodejs/npm was completely nuked to the point that i couldnt even run "npm" without errors). 
Closing this.
