### ISSUE TITLE
[Question] Gif preview

### ISSUE THREAD

**Issue by myryk31415** [Aylur/ags#492]
So I am trying to my a wallpaper picker for swww and support gifs as well.

If I just use the give as Wiget.icon it throws this error:
`JS ERROR: GdkPixbuf.PixbufError: Not all frames of the GIF image were loaded.`

I found this line in script from JaKooLit:
`printf "$(echo "${PICS[$i]}" | cut -d. -f1)\x00icon\x1f${wallDIR}/${PICS[$i]}\n"`
output for an example gif:
`mygif^@icon^_/home/user/path/to/file/mygif.gif`
This then gets piped into rofi.

Is there anyway to get a preview or a thumbnail of the gif?

**Comment by myryk31415** [comment]
regarding the line from the script, I just checked the picker again and it doesn't have a thumbnail either

**Comment by myryk31415** [comment]
I found a workaround: setting the gif / image as css background, this way gifs are shown as well. (Even though not animated.)

**Comment by croots** [comment]
Hey @myryk31415 !

I'm trying to get a theme picker working on my ags1 setup as well and I think I'm experiencing the exact same issue as you are. Could you elaborate on how you went about it? The widget icon doesn't have a background element and I'm not a javascript/css person at all.

**Comment by myryk31415** [comment]
I think there were a couple of ways to go about it, but everything had some downsides:

1. Setting the gif as background
 
3.

**Comment by myryk31415** [comment]
(First comment deleted cause I sent it unfinished on accident)

**Comment by myryk31415** [comment]
I tried a couple of ways to go about it, but all of them had downsides.

1. Setting the gif as css-background
For this approach you need to use a different widget (box should work), you can adjust the size however you like and make the gif always match the size of the box, however it won't be animated and it used up a lot of resources for me. (I had like 200 items though, should be fine for a few)
2. Using GdkPixbuf
```
let animation = GdkPixbuf.PixbufAnimation.new_from_file(path);
let image = Gtk.Image.new_from_animation(animation);
```
And then setting the image as the child of e.g. a box.
I think I had some issues with the gifs being the original size? Or sized incorrectly in general?

Hope that helps :)

**Comment by myryk31415** [comment]
Ahh regarding the background I found how I did that:
```
self.css = `background-image: url("${path}");`;
```
maybe it does work on icon widgets as well? I'm not sure anymore. but I think boxes had some properties which made it easier to get the exact size i wanted.
