### ISSUE TITLE
After hyprland crash, getting error: "JS ERROR: Gio.IOErrorEnum: Could not connect: Connection refused"

### ISSUE THREAD

**Issue by rykugur** [Aylur/ags#493]
I'm just digging in to AGS, and also experiencing some intermittent crashes on Hyprland (unrelated to AGS as far as I'm concerned). However, after starting Hyprland back up and trying to re-run `ags`, I get this error:

![image](https://github.com/Aylur/ags/assets/2609898/14c7373a-b054-40ee-a7d0-1777660de4e7)

Rebooting will fix the issue until the next time hyprland crashes while AGS is running.

## Other info

![image](https://github.com/Aylur/ags/assets/2609898/0e57d435-2e4a-4be1-84eb-fb267784a339)

EDIT: I'm currently running the config defined here: https://github.com/Aylur/ags/tree/main/example/simple-bar

**Comment by redxtech** [comment]
Can confirm, getting the same error after restarting hyprland. I'm using a completely different ags configuration.

**Comment by Aylur** [comment]
I am pretty sure this is an issue with Hyprland, I also get this sometimes when restarting Hyprland even with `hyprctl`
