### ISSUE TITLE
How to launchapp with my terminal?

### ISSUE THREAD

**Issue by lVentus** [Aylur/ags#497]
I am writing a launcherpad for my tablet now. I can launch gui app perfectly. But when I try to launch tui apps, like btop, it will throw an error:
```
 JS ERROR: Gio.IOErrorEnum: Unable to find terminal required for application. 
```
btw I am using Kitty

**Comment by myryk31415** [comment]
which command do you use to launch the TUI?

**Comment by lVentus** [comment]
> which command do you use to launch the TUI?

just app.launch()

**Comment by kotontrion** [comment]
Similar question got asked recently here: #464

**Comment by deng232** [comment]
Kitty isn't known terminal in Gio
