### ISSUE TITLE
If ags is killed, apps launched with the Applications service are killed too

### ISSUE THREAD

**Issue by end-4** [Aylur/ags#50]
This happens if we use `launch()` of the app from the `Applications` service

**Comment by ferrreo** [comment]
Had a quick look at this and it looks like it is a gtk thing as launch in the service just calls the GIO func launch.

Might be possible to give it it's own context maybe to stop it happening though not really sure.

**Comment by Aylur** [comment]
are you perhaps launching ags on a terminal, launch some apps, then ctrl+c?

**Comment by end-4** [comment]
> are you perhaps launching ags on a terminal, launch some apps, then ctrl+c?

yes
i see, when i kill ags using `pkill` instead of Ctrl+C, this doesn't happen
