### ISSUE TITLE
DBusmenuGtk3 Error

### ISSUE THREAD

**Issue by Coelhomatias** [Aylur/ags#501]
I just updated Arch to the latest version (24.07) and did a clean install of ags.
Now every time I try to open ags I get this error:
Gjs-Console-CRITICAL **: Error: Requiring DbusmenuGtk3, version none: Typelib file for namespace 'DbusmenuGtk3' (any version) not found
I can't figure out what is causing this issue.

**Comment by antecrescent** [comment]
Did you install [`libdbusmenu-gtk3`](https://archlinux.org/packages/extra/x86_64/libdbusmenu-gtk3/)?

**Comment by Coelhomatias** [comment]
Thank you very much, this solved my issue. I install my system with an ansible playbook and perhaps one of the existing packages I install changed it's dependencies. Solving that now.
I'll be closing the issue, thanks again for the fast reply!
