### ISSUE TITLE
AGS bar reloading on GTK elements and on new workspace in hyprland

### ISSUE THREAD

**Issue by andrwui** [Aylur/ags#502]
Sorry if the title isn't accurate...

I just tried making a bar, almost the same as the example bar, with some tweaks on the css and each element separated in its own file.

When i change to a workspace with nothing on it, or open a GTK menu like the GIMP left click menu, the bar reloads and causes the windows to jump suddenly for an instant which makes it look weird...

I don't know if this is a me problem or what but I wanted to know if someone knew what is the problem and how to fix it.

**Comment by Aylur** [comment]
share your config, I won't be able to tell you without a way to reproduce

**Comment by andrwui** [comment]
It somehow fixed itself when I compiled everything to typescript and sass. I couldn't reproduce the error in any way since.

**Comment by kaptcha0** [comment]
I also have the same issue. It also happens when I switch to another tab on my browser, or change files in Zed.
