### ISSUE TITLE
Can't style calendar

### ISSUE THREAD

**Issue by neyhden** [Aylur/ags#506]
I'm trying to apply style to the calendar widget, but I have no idea how to access them. According to the GTK page, the node hierarchy should look something like this:

![image](https://github.com/user-attachments/assets/661512b0-019c-4ccd-a79b-7c82ed769818)

But when I open the inspector, I get this:

![image](https://github.com/user-attachments/assets/069e6286-07cc-4ac9-a81f-41f954a3ad15)

Tried to make selectors anyways in css like:

calendar label {...}
calendar grid label {...}
.today {...}
galendar grid {...}
calendar > grid {...}

But none seem to work, although I can still access the calendar to change its background. Tried to look at other people's dotfiles for reference but everyone uses scss, which I don't know how to use, so, how could I access the individual days in css to make the calendar useful?

**Comment by Aylur** [comment]
that is the gtk4 calendar widget
I don't know where or even if the gtk3 widget is documented, but you can refer to the defaukt gtk3 theme source code <https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L3924>

**Comment by neyhden** [comment]
Thanks, I'll look into it :D
