### ISSUE TITLE
Keyboard layout on Hyprland

### ISSUE THREAD

**Issue by igorepst** [Aylur/ags#52]
Hi, I suspect the keyboard layout doesn't work properly. I am using `ags` from the latest commit `0ee0d52`, `Hyprland` 0.28.0-1 on ArchLinux. The `config.js` is updated to the latest example.
I defined
```
const Kbl = () => Label({
    connections: [[Hyprland, (label,kbName,layoutName) => {
	label.label = kbName? ('kb:' + kbName + ', ln: ' + layoutName ) : 'yy';
    }, 'keyboard-layout']],
});
```
and added `Kbl()` to the `Right` children array.
I see two issues:
1. At start, the label shows `yy`
2. After switching layouts in Hyprland, the label shows `kb:at-translated-set2-keyboard, ln: undefined`. I can confirm that layout switch works properly and I can type in all the languages. Relevant Hyprland config:
``` 
 input {
    kb_layout = us,ru,il
    kb_variant = ,phonetic,
    kb_model = pc104
    kb_options = grp:ctrl_space_toggle
    ...
```
Please advise. Thanks in advance

**Comment by Aylur** [comment]
layout name is undefined because I left in `.split()` accidentally.
At start it will always be `yy`, because it only emits when you do a switch. You need to initalize its label value

**Comment by igorepst** [comment]
Is there a way to initialize the value dynamically? I mean, depending on the current layout using built in features?
In addition, initializing the value seem to contradict the examples, where it is stated that connections emit values at the start.
Thanks!

**Comment by Aylur** [comment]
yeah, this is one of the few cases where it doesn't make sense to run the connection callback on construct.
you could force a kbd layout change with `execAsync('hyprctl <something>') in label.setup so the signal fires off

**Comment by igorepst** [comment]
Thank you for the fix :)
