### ISSUE TITLE
[help] detect mouse motion

### ISSUE THREAD

**Issue by wathhr** [Aylur/ags#521]
I am trying to add a mouse move listener using the `EventControllerMotion` class from `types/@girs/gtk-3.0/gtk-3.0.cjs` (specifically to a notification widget for the ability to drag it off screen)

unfortunately I haven't found any way to do this as I am unable to add a controller to any kind of widget and there's no other event that can do this as far as I can tell

**Comment by Aylur** [comment]
You can implement dragging with [Gtk.GestureDrag](https://gjs-docs.gnome.org/gtk30~3.0/gtk.gesturedrag)
