### ISSUE TITLE
Wine System Tray

### ISSUE THREAD

**Issue by BennyDioxide** [Aylur/ags#527]
OS: NixOS 24.11.20240727.b73c222 (Vicuna) x86_64
AGS version: `1.8.2`
ags flake rev: `646d5ad073ff7f8b1d50cfbd40f5b8a250fcd59d`
nixpkgs flake rev: `c00d587b1a1afbf200b1d8f0b0e4ba9deb1c7f0e`
`hyprctl vesrion` output:
```
Hyprland, built from branch  at commit bc6b0880dda2607a80f000c134f573c970452a0f  ().
Date: 2024-07-13
Tag: , commits: bc6b0880dda2607a80f000c134f573c970452a0f

flags: (if any)
```
[config/dotfiles](https://github.com/BennyDioxide/nixos-config)

I'm using end-4's ags configuration recently, and I found that when I use any windows apps with tray on wine, there would always be a "Wine System Tray" (actually there's no title, and in `hyprctl` it is shown as `explorer.exe`) floating window, which the item inside should be in the AGS tray module.

For instance, where I started LINE, a messaging app under Hyprland and AGS:
![image](https://github.com/user-attachments/assets/ff423a32-d341-4f05-8b62-5919e2963c21)
(Please mention that there's a little white floating window near the right center)

It would be nice to add this feature, as I use LINE so often as literally everyone in Taiwan uses it. T_T

**Comment by kotontrion** [comment]
The systemtray uses the StatusNotifierItem protocol for the tray, which is widely supported. Wine still uses the older xembed method, which can't be implemented in ags as it is X11 only.

There is a PR for wine to add SNI support, but I don't think this will be merged anytime soon.

You could try `xembedsniproxy`, which is a proxy from xembed to SNI used by KDE, but I never tried it.

**Comment by BennyDioxide** [comment]
> You could try `xembedsniproxy`, which is a proxy from xembed to SNI used by KDE, but I never tried it.

Thanks for the help! I enabled `services.xemded-sni-proxy` in home-manager, and after `systemctl --user start xembed-sni-proxy.service`, it **immediately** works perfectly.

Should I close this issue or left it open?

**Comment by kotontrion** [comment]
When the app uses SNI, the menu is exported over dbus, and then created and rendered by ags. When using xembed, the menu is rendered by the app itself. So the app has to know where to render that window. To do that , you have to pass the click event to the activate function of the tray item:

```js
on_primary_click: (_, event) => item.activate(event),
//same for item.secondaryActivate
```

What you probably want to do is differentiate between SNI and xembed items, like check if item.menu is defined, then open the menu using something like `item.menu.popup_at_widget`else call `item.secondaryActivate`.

It could also be Hyprland being a tiling window manager messing with the position of that the, not sure though.

Close the issue, as there is nothing actionable here.
