### ISSUE TITLE
Wiki: Hyprland example widget is outdated and only partially works

### ISSUE THREAD

**Issue by tralph3** [Aylur/ags#528]
The [example widget](https://aylur.github.io/ags-docs/services/hyprland/#example-widget) for the hyprland service section in the wiki contains an entry for a "focused title" widget which is just a label containing the title of the currently active window. Code below:

```js
const focusedTitle = Widget.Label({
    label: hyprland.active.client.bind('title'),
    visible: hyprland.active.client.bind('address')
        .as(addr => !!addr),
})
```

This still works fine, but the `visible` property, while being set correctly, does not have an effect, and so the label can still be seen when its empty. This used to work, but broke at some point. I've seen other people facing this issue in #356, but the discussion seems to imply it has always been this way.

Doing as the comments suggest and wrapping the label in a box (and setting the `visible` property of the box) does initially work. The label is not visible when launching `ags`, but when a window becomes active and the label stops being empty, switching to empty workspaces or closing the window still displays the empty label.

The wiki should be updated with a fully working example.

**Comment by Aylur** [comment]
Hyprland seems to have changed the address at some point when there is no focused window
