### ISSUE TITLE
weird errors from ags

### ISSUE THREAD

**Issue by fucksophie** [Aylur/ags#529]
I keep getting crashes and errors such as:
`Gdk-Message: 00:35:54.800: Error reading events from display: Connection reset by peer`
and
`Gdk-Message: 00:15:35.983: Lost connection to Wayland compositor.`.

**Comment by Aylur** [comment]
Compositor issue. What do you use?

**Comment by fucksophie** [comment]
I use Hyprland. My configuration is available here. https://git.sad.ovh/sophie/dots/src/branch/main/src/.config/ags
