### ISSUE TITLE
QOL change for className prop

### ISSUE THREAD

**Issue by Frontear** [Aylur/ags#53]
When accessing via the setter, replace all classes.

Why: It feels more logical since a setter is meant to "set" a value, not just "append" it. As it is currently, doing `widget.className` in, say a setup call will simply add a class to the classNames, not replace them.

Main reason I'm bringing this up is that I'm trying to write dark/light themes for my config. My thought process was that I could have two classes, `dark` and `light`, define colors for each of them based on other, parent classes `.modules.dark`, `.modules.light`, and wrote a Service to change the classes when it emits "changed". Unfortunately, doing `widget.className = Theme.theme` does not replace the classes, it seems to append to it, which is a problem since then I can't really use this method without going deep into the GTK/GJS code and modifying it through a StyleContext instead.

If this isn't possible what would you suggest as an alternative to what I'm trying to do.

**Comment by Frontear** [comment]
Suppose I could get around it by doing `toggleClassName("dark"/"light")`, but it seems a bit non-straightforward

**Comment by Aylur** [comment]
I meant it to behave like this, I just forgot to add the line which removes them first
