### ISSUE TITLE
Hyprland wont start ags on startup

### ISSUE THREAD

**Issue by Anik200** [Aylur/ags#533]
I did add `exec-once= ags` but it wont start

**Comment by Aylur** [comment]
most probably some an environment variable issue, but can't really help you without you also sharing the config

**Comment by Anik200** [comment]
> most probably some an environment variable issue, but can't really help you without you also sharing the config

https://github.com/mewoocat/NixOS/tree/ags-overhaul
here are the config files i am using

**Comment by MonstrousOgre** [comment]
I was facing the same issue. For me, it was because sass was installed locally in my home directory. I installed it system-wide and no longer have the issue

**Comment by Anik200** [comment]
> I was facing the same issue. For me, it was because sass was installed locally in my home directory, and my Hyprland config didn't have the updated PATH variable I was setting. I installed it system-wide and no longer have the issue

![image](https://github.com/user-attachments/assets/ba2651ce-14b9-471b-8450-ab739ca45db9)
this is what mine looks like

**Comment by MonstrousOgre** [comment]
@Anik200 what happens when you type the full path to ags in your Hyprland config?

**Comment by Anik200** [comment]
The issue got fixed once i put `exec-once=/usr/local/bin/ags`
Instead of `exec-once=ags`. Thanks everyone for their time :)

**Comment by ctilley83** [comment]
> The issue got fixed once i put `exec-once=/usr/local/bin/ags` Instead of `exec-once=ags`. Thanks everyone for their time :)

It's strange but providing an absolute path did not work for me. AGS launches fine from the command line but not using exec-once in hyprland.conf. I'm on the just released 0.42 version of hyprland.

![image](https://github.com/user-attachments/assets/fc443502-917f-4a51-b95c-e2e1fb52e6f3)

**Comment by Anik200** [comment]
> > The issue got fixed once i put `exec-once=/usr/local/bin/ags` Instead of `exec-once=ags`. Thanks everyone for their time :)
> 
> It's strange but providing an absolute path did not work for me. AGS launches fine from the command line but not using exec-once in hyprland.conf. I'm on the just released 0.42 version of hyprland.
> 
> ![image](https://github.com/user-attachments/assets/fc443502-917f-4a51-b95c-e2e1fb52e6f3)
> 
> Here's part of my hyprland.conf
> env = XCURSOR_SIZE,24
> env = HYPRCURSOR_SIZE,24
> env = QT_QPA_PLATFORM,wayland;xcb
> env = QT_QPA_PLATFORMTHEME,kde
> #env = QT_STYLE_OVERRIDE,kvantum
> env = QT_AUTO_SCREEN_SCALE_FACTOR,1
> env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
> env = XDG_CURRENT_DESKTOP,Hyprland
> env = XDG_SESSION_TYPE,wayland
> env = XDG_SESSION_DESKTOP,Hyprland
> env = MOZ_ENABLE_WAYLAND,1
> env = OZONE_PLATFORM,wayland
> #env GTK_DEBUG=interactive waybar
> 
> 
> # Hyprland initialization options
> exec-once = hyprpaper & hypridle
> exec-once = /usr/local/bin/ags
> #exec-once = waybar
> exec-once = /usr/libexec/polkit-kde-authentication-agent-1
> #exec-once = swaync & # start notification demon
> exec-once = wl-paste --type text --watch cliphist store #Stores only text data
> exec-once = wl-paste --type image --watch cliphist store #Stores only image data

forgot to mention you have to add `env = ags,/usr/local/bin/ags` into your hyprland config too

**Comment by ducpm151061** [comment]
same here

**Comment by ctilley83** [comment]
I'm still having problems with this. I added the env environment variable plus an absolute path to ags in my exec-once command
