### ISSUE TITLE
Missing .config/ags/config.js (NixOS, Flakes, Home Manager)

### ISSUE THREAD

**Issue by Scovi** [Aylur/ags#535]
Hi, I am struggling to get ags working with flakes and homemanager (not standalone). I am building my configuration based off of [https://github.com/linuxmobile/kaku](url). When running `nixos-rebuild switch --flake` home manager would not create a `config.js` file nor an `ags` folder in the `~/.config` directory.

Using the sample home manager module provided as well as reading the options in hm-module.nix I deduced (incorrectly) that I needed to add `programs.ags.configDir = ../ags;` to my  [https://github.com/linuxmobile/kaku/blob/580d755a9f858677c0ef5c070aac3c3fa8f194e5/home/services/ags/default.nix](url). What this did was symlink a copy of my `default.nix` in a new `~/.config/ags` directory. The description of  `configDir` reads:
> The directory to symlink to {file}`$XDG_CONFIG_HOME/ags`

If I read [https://github.com/nix-community/home-manager/blob/b3d5ea65d88d67d4ec578ed11d4d2d51e3de525e/home-manager/home-manager#L174](url) correctly this quite literally means that using `programs.ags.configDir = ../ags;` symlinks my ags nix configuation from `/etc/nixos/home/services/ags/default.nix` to `~/.config/ags/default.nix`.

How do I go about generating `/nix/store/#-home-manager-files/.config/ags/config.js` and linking it to `~/.config/ags/config.js`?

Thanks for your time and sorry for the noob question.

**Comment by Aylur** [comment]
You would have to ask the author of that repo for source code as there doesn't seem to be any source of their ags config. Which from the single screenshot in their readme seems to be an unmodified version of mine.

`programs.ags.configDir = ../ags` literally means to copy the directory `../ags` to the nix store and symlink that to `~/.config/ags`. I am assuming you cloned this repo in which case, `../ags` refers to a directory that only has a default.nix file in it.

**Comment by Scovi** [comment]
Wow thanks for answering so fast!

To make sure I understand you completely:
1. The repo I cloned is missing a `config.js`
and 
2. Following your home manager implementation (and its implied file structure) that would mean that I need to create the `config.js` file in `/etc/nixos/ags`?

If so, this makes so much sense now and I know exactly what at to.

Additionally, when you said they used an unmodified version of your config would that be the simple-bar in your examples?

Thanks again for your time.

**Comment by Aylur** [comment]
1. yes
2. it doesn't matter where you store you config files, since you can import them from anywhere, file structure depends on your personal preference

> Additionally, when you said they used an unmodified version of your config would that be the simple-bar in your examples?

I was referring to [my setup](https://github.com/Aylur/dotfiles)

**Comment by Scovi** [comment]
Ok, awesome. I'm gonna try it out with the simple-bar example and go from there.

Your set up looks amazing!

When I work through the docs to personalize my set I'm going to be referencing your dots alot.

Last noob question. Are the application launcher and notification popups drop in replacements for rofi and dunst respectively?
