### ISSUE TITLE
Reasoning behind GTK3

### ISSUE THREAD

**Issue by DevAlien** [Aylur/ags#54]
Hi, I'd like to know the reasoning on using GTK3 instead of GTK4.

Some things are easier with GTK4, just wanted to understand :)

**Comment by Aylur** [comment]
[gtk4-layer-shell](https://github.com/wmww/gtk4-layer-shell) crashed a lot on me, you can find my attempt on the [gtk4 branch](https://github.com/Aylur/ags/tree/gtk4), which I want to update sometime in the future

**Comment by Aylur** [comment]
soon™

**Comment by Aylur** [comment]
https://github.com/Aylur/Astal

**Comment by Aylur** [comment]
> But it seems that it's still on gtk3. Will it be ported to gtk4 in the future?

yes, there will be a gtk4 version too
