### ISSUE TITLE
Widget Show / Hide CLI

### ISSUE THREAD

**Issue by jncsotk30** [Aylur/ags#543]
Could a direct show / hide option be included in the ags cli options? I know there's already a toggle (`ags -t`) switch, but it'd be nice to specifically hide a window when needed. I have a control center window I'd like to close when potentially switching workspaces.

Something like so..

**Hide**
`ags -H <widget-window-name>`

**Show**
`ags -S <widget-window-name>`

**Comment by Aylur** [comment]
duplicate of https://github.com/Aylur/ags/pull/484
