### ISSUE TITLE
position bar on the bottom instead of top of screen

### ISSUE THREAD

**Issue by tyriis** [Aylur/ags#544]
Hello,

I am not able to setup the bar to show up on the bottom of the screen instead of the top.

Maybe I am missing something.

**Comment by Aylur** [comment]
set the anchor property of the [window](https://aylur.github.io/ags-docs/config/widgets/#window) to `["bottom", "left", "right"]`

**Comment by tyriis** [comment]
embarrassing, thank you, absolutely make sense :), I feel like a noob.
