### ISSUE TITLE
Bar jitter when switching workspaces

### ISSUE THREAD

**Issue by wxqwinner** [Aylur/ags#545]
https://github.com/user-attachments/assets/425bfddf-2c7b-4f89-a2ff-2ac9ba97cc16

https://github.com/user-attachments/assets/8d259fb0-4807-4018-afd0-07a31bfbe31b

Observe the presence of the Widget.Slider component at the top, leading to changes caused by switching workspaces.

**Comment by Noname672** [comment]
The buttons in the workspaces part of the bar get smaller than bigger during change so the whole bar resizes to accomodate for it. Anyways, it should be solved by setting a high enough min-height for the bar in css.

**Comment by wxqwinner** [comment]
![image](https://github.com/user-attachments/assets/f47d9ee3-481b-443a-9119-5074180121f7)
The setting here is invalid, I chose a label, set min-height, and it works.
![image](https://github.com/user-attachments/assets/424e43b8-b5b5-4049-a1fe-89b0139157cc)

**Comment by wxqwinner** [comment]
@Noname672 Thanks.
