### ISSUE TITLE
Icons not updating on change in wifi state

### ISSUE THREAD

**Issue by yashranjan1** [Aylur/ags#547]
When i turn off my wifi using either the terminal or the UI button I have made, the UI icons and label do not seem to be updating. However, when I switch it on using either the terminal or the the UI button, both of them update. On reloading the widget, all states are initially correct but do not update. I think I just haven't implemented the bind function well, but I have gone over the documentation multiple times and cant figure out whats wrong. Thanks for your time 

```
const Wifi = () => {   

    return Widget.Box({
        spacing: 8,
        children: [
            Widget.Button({
                on_clicked: ()=>{ {
                    if (network.wifi.enabled){
                        network.wifi.enabled = false
                    }
                    else {
                        network.wifi.enabled = true
                    }
                } },
                child: Widget.Box({
                    children: [
                        Widget.Icon({
                            icon: network.wifi.bind("icon_name")
                        }),
                        Widget.Label({
                            label: network.wifi.bind("ssid").as(ssid => ssid || "Not Connected")
                        })
                    ]
                })
            })
        ],
        hexpand: true,
        class_name: 'section shortcut-menu-item'
    })
}
```

**Comment by yashranjan1** [comment]
I substituted bind with hook and it seems to be working right now, seems more likely that it is a problem with implementation.

**Comment by yashranjan1** [comment]
> getting the following errors in the logs:

Just to make sure i understand, are you using the in-built network service? If yes, the [in-built service](https://aylur.github.io/ags-docs/services/network/) has a ```network-manager``` listed as a dependency

**Comment by adminy** [comment]
No I didn't have network-manager enabled. I enabled it and that seems to have solved the issue.
