### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by Xtr4F** [Aylur/ags#549]
RAM usage is growing uncontrollably when using `Utils.interval`. it looks like it's a problem with `hyprland.messge()` (and `.messageAsync()` as well, which is causing this to happen. I've tried using `Utils.exec()` alternatively and haven't noticed this behavior. Video below:

https://github.com/user-attachments/assets/70a87d41-3bef-48b4-8666-6df4a5a27275

P.s. 1 millisecond interval for clarity. In reality, even with interval values like 100, memory usage grows, just a bit slower, but it is never freed, even when the interval is already destroyed.

**Comment by Xtr4F** [comment]
P.s.s. At the time of writing this issue, ags crashed with an error, filling about 770mb of memory, lol: 
![image](https://github.com/user-attachments/assets/18b49885-eea1-48df-919f-cf43dd8ee24a)

**Comment by Xtr4F** [comment]
So, I did a little investigation (ran 4 different ags instances with different interval times, the first two with 5ms, the last two with 50ms. The first and third call `hyprland.message`, the second and fourth call `Utils.exec`) and it turns out that all of them increase memory usage over time for some JavaScript reason I don't understand, just at different speeds:

![изображение](https://github.com/user-attachments/assets/0deebff7-3b11-4d13-a315-d5e4444dcf1d)


 So maybe I was wrong with the issue name... But now I'm even more confused as why in the world this is happening? 

Well ok, in many cases it's not that critical since you won't run it infinitely, but the problem is that it doesn't clear memory even when the interval is destroyed (or I'm doing something wrong, I'm a noob in JS), which can already lead to some bad consequences

**Comment by its-darsh** [comment]
does printing the output directly (without passing into the json parser) trigger the GC?

might be a leak in the JSON parser

**Comment by Xtr4F** [comment]
No, it doesn't. And memory leak happens only with Utils methods

**Comment by Xtr4F** [comment]
upd. The only solution I've come up with so far is to use an external script. But `Utils.subprocess()` also causes a leak. So I use `Variable` instead. And for some reason it works fine. I left this code running for about an hour and RAM usage never once went over 60mb:

![pic](https://github.com/user-attachments/assets/96df9006-1492-452a-8d14-679ea704b398)

It really seems to be a problem with some parts of `Utils` and `Services` 🤔

**Comment by Xtr4F** [comment]
What's even weirder is that I have looked at the sources and `Variable` also uses `subprocess` but for some reason doesn't cause this problem:


https://github.com/user-attachments/assets/f9ddbbf6-20cc-4450-9c10-629bbd477d3e
