### ISSUE TITLE
One problem

### ISSUE THREAD

**Issue by ASH-OBS9** [Aylur/ags#55]
When I enter ags, it reports the following error:

(ags:23609): Gjs-WARNING **: 13:31:34.064: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/ash/.config/ags/config.js:1:0

(ags:23609): Gjs-WARNING **: 13:31:34.064: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/ash/.config/ags/config.js:1:0
Gjs-Message: 13:31:34.064: JS LOG: ERROR: No config was provided or there was an error

(ags:23609): Gjs-WARNING **: 13:31:34.064: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ /home/ash/.config/ags/config.js:1:0

Can someone give me some help

**Comment by Axenide** [comment]
Hello, sorry if this is inappropriate, I'm new to GitHub Issues, but how did you solve this? I have the same problem.
