### ISSUE TITLE
ags crashes with too many notifications. Won't start

### ISSUE THREAD

**Issue by Fifthdread** [Aylur/ags#555]
I let my laptop sit for a while and I returned with over 100 notifications, maybe 150. I clicked the notification panel so I could clear it, it hung for a moment then crashed.

When trying to start ags I get the following error:

```
(com.github.Aylur.ags:4981): Gdk-CRITICAL **: 22:57:00.264: ../gtk/gdk/wayland/gdkdisplay-wayland.c:1433: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
[1]    4981 segmentation fault (core dumped)  ags
```

![image](https://github.com/user-attachments/assets/a65b97f6-73e1-47c7-a002-11a8bfca1969)

**Comment by its-darsh** [comment]
this assertion error might be triggered if your `Gtk.Window` exceeds a specific size, your window gets so big that Gdk couldn't make a surface for it, and if it could make one, bad things would happen

you better consider how you manage your window, for example you can limit your widget to not exceed a certain size by packing it inside a scrollable

**Comment by Fifthdread** [comment]
Hmmm I'll check it out. Thanks for the info.
