### ISSUE TITLE
Dynamic monitors

### ISSUE THREAD

**Issue by zoriya** [Aylur/ags#56]
All windows have to be defined inside the windows array of the default export of config.js, and we can't register new windows at runtime (I think). I would like to automatically create new bars for newly plugged in monitors so to do that ags should either:
 - Support a monitor factory method in the config that would create a list of windows for a given monitor id/name.
 - Support dynamic windows creation via a connect or an event to a service that will be notified when a monitor is created/destroyed.

**Comment by Aylur** [comment]
Its true you can't register new windows at runtime, but you can definitely make new ones with just calling `ags.Widget.Window`, and you can use `Gdk.Display` signals to watch for monitors.
This feature sounds useful, I will integrate something into `ags.App`

**Comment by Aylur** [comment]
Added the option to register windows on runtime. Now it is also possible to pass a `Gdk.Monitor` to `ags.Widget.Window`
so the emitted monitors from `Gdk.Display` signals can be used

**Comment by Aylur** [comment]
you can also get the monitor associated with each window, so it can be removed on `Gdk.Display` signal

**Comment by Aylur** [comment]
```js
// example
const display = imports.gi.Gdk.Display.get_default();
display.connect('monitor-added', (_, monitor) => {
    const win = ags.Widget.Window({
        name: 'test',
        child: ags.Widget.Label('test'),
        monitor,
    });

    ags.App.addWindow(win);
});
display.connect('monitor-removed', (_, monitor) => {
    for (const [name, win] of ags.App.windows) {
        if (win.monitor == monitor)
            ags.App.removeWindow(name);
    }
});
```

you will still have to makes sure that Window.name is unique
