### ISSUE TITLE
OSD randomly appears when binding to `audio.speaker.bind("volume")`

### ISSUE THREAD

**Issue by mike-lloyd03** [Aylur/ags#564]
I have an OSD widget which binds a Revealer widget to the following hooks:

```typescript
  return revealer
    .hook(audio.speaker.bind("volume").emitter, () =>
      show(audio.speaker.volume, 1.5, getVolumeIcon()),
    )
    .hook(brightness, () =>
      show(brightness.screen, 1, "brightness-high-symbolic"),
    );
```

Sometimes, the volume widget randomly appears. This happens especially when scrolling YouTube or other pages with some kind of autoplay content. Should I be binding to something else?  I'm using `pipewire`/`pipewire-pulse`.

Link to full source:
https://github.com/mike-lloyd03/.dotfiles/blob/a08ef8ec0a0c9a99ffa9a98c3f1d036491a125c8/ags/lib/osd.ts#L41-L48

**Comment by kotontrion** [comment]
You are using it wrong.
`audio.speaker.bind("volume").emitter` is the same as `audio.speaker` the bind here is completely unnecessary. You don't specify a signal in the hook, therefore it connects to the changed aignal, which also gets emitted when streams are added/removed eg when starting to play some audio. Connect to the `notify::volume` signal instead:
```js
.hook(audio.speaker, () =>
      show(audio.speaker.volume, 1.5, getVolumeIcon()),
    "notify::volume")
```

**Comment by mike-lloyd03** [comment]
That's very helpful, thank you. I'm not totally sure how signals work and couldn't really grok it from the docs.
