### ISSUE TITLE
No available ComboBox/DropDown widget

### ISSUE THREAD

**Issue by Przegryw321** [Aylur/ags#568]
I want to use what is basically the `<select>` tag in HTML. From googling I discovered that this is called a ComboBox in gtk3, and DropDown in gtk4. I've seen this type of widget used in some ags showcases (as a theme switcher for example, which is what I'm trying to do), but I can't seem to find it. Am i missing something or do I need to make my own?

**Comment by kotontrion** [comment]
In ags you can all gtk widgets even if they are not subclassed.
```js
const cb = new Gtk.ComboBox()
```
But in that case ags specific things like hooks and binds won't work. To do that you can subclass yourself like this:
```js
const ComboBox = Widget.subclass(Gtk.ComboBoxText);
const cb = ComboBox()
```
Note that here ComboBoxText is subclasssd. In most cases this is what you want as you won't need to use LostStores to use them.

**Comment by Przegryw321** [comment]
I see, thanks!
I had no idea that you had to use `Gtk` for this. I was just trying to use `Widget` before and it didn't work.
