### ISSUE TITLE
[ASK] is it possible to embed cava audio visualizer into a widget somehow?

### ISSUE THREAD

**Issue by Eugenenoble2005** [Aylur/ags#570]
I can't seem to find any instructions on this. Is it possible and where can i read more about it/ find some example. Many thanks!!

**Comment by kotontrion** [comment]
Yes it is possible. The easiest way to achieve this is, is by configuring caca to print the values to stdout and use a Variable to listen to it. In my config I do exactly that. I then use a drawing area for the visualization.

https://github.com/kotontrion/dotfiles/blob/main/.config%2Fags%2Fmodules%2Fcava%2Fcava.js

**Comment by Eugenenoble2005** [comment]
Alright, @kotontrion  ill be sure to check this out. Thanks alot.
