### ISSUE TITLE
Calendar Widget: Possibility to always show current date on open?

### ISSUE THREAD

**Issue by ajboni** [Aylur/ags#573]
Is it possible to force the calendar widget to always highlight the current date on show?

If you open the calendar and select another date, and then hide it. The next time you open it shows that date as default. It's confusing!

**Comment by Aylur** [comment]
you have to select the current day explicitly everytime the window the calendar is in is opened
```js
App.connect("window-toggled", (_, name, visible) => {
  if (visible && name == yourWindow.name) {
    // select the day on calender
  }
})
```

**Comment by mylinuxforwork** [comment]
> you have to select the current day explicitly everytime the window the calendar is in is opened
> 
> ```js
> App.connect("window-toggled", (_, name, visible) => {
>   if (visible && name == yourWindow.name) {
>     // select the day on calender
>   }
> })
> ```

I was able to add this listener. But how can I set the current date of the Calendar widget?

Thanks in advance for your help.

**Comment by Aylur** [comment]
https://gjs-docs.gnome.org/gtk30~3.0/gtk.calendar#method-select_month
https://gjs-docs.gnome.org/gtk30~3.0/gtk.calendar#method-select_day
