### ISSUE TITLE
 I haven't started using ags bar yet. Does it support a global menu?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Aylur/ags#574]

**Comment by kotontrion** [comment]
It does not.
For something like that you need something to associate a menu (possibly exposed over dbus) with a window. So you can build and display the menu for the currently focused window. But this is currently not possible in Wayland, as there no protocol for that. Iirc there are some efforts made on a protocol with which something like this could be achieved, but don't expect it anytime soon.

**Comment by MRSS02** [comment]
> It does not. For something like that you need something to associate a menu (possibly exposed over dbus) with a window. So you can build and display the menu for the currently focused window. But this is currently not possible in Wayland, as there no protocol for that. Iirc there are some efforts made on a protocol with which something like this could be achieved, but don't expect it anytime soon.

How does kde plasma do it then, even on wayland?

**Comment by kotontrion** [comment]
> How does kde plasma do it then, even on wayland?

KDE made its own protocol for this, so did gnome. But no other compositors implement them. So you can get global menus for QT apps when using kwin and you can get a global menu for gtk apps when using mutter, but for other compositors you are out of luck. Something like this needs support from the compositor.
