### ISSUE TITLE
messageAsync handling multiple words argument inside quotes incorrectly?

### ISSUE THREAD

**Issue by HydroSulphide** [Aylur/ags#581]
I'm not sure if the messageAsync() in src/service/hyprland.ts is the culprit, but I don't know what else could be the problem.

What I essentially want to do is:
`hyprctl keyword general:col.active_border "rgba(00FF99EE) rgba(FE4761EE) 30deg"`

I'm using the config from [aylur's dotfiles](https://github.com/Aylur/dotfiles) and wanted to test this by editing the SetupHyprland() function inside [lib/hyprland.ts](https://github.com/Aylur/dotfiles/blob/main/ags/lib/hyprland.ts):

For testing I replaced 
`general:col.active_border ${rgba(primary())}` 
with
`general:col.active_border "rgba(00ff99ee) rgba(FE4761EE) 30deg"`

This is how the active border looks like, when I'm executing 
`hyprctl keyword general:col.active_border "rgba(00FF99EE) rgba(FE4761EE) 30deg"` 
in my terminal:

![2024-09-23_11-14-07](https://github.com/user-attachments/assets/15c0c3a1-b102-4ae4-84e3-5e035121a08f)

And this is what it looks like, when reloading ags:

![2024-09-23_11-14-26](https://github.com/user-attachments/assets/60840520-af2c-4af9-9861-603e513de58a)

It seems that is is ignoring the first color "rgba(00FF99EE)" or at least makes it transparent, because I'm getting the exact same result by executing `hyprctl keyword general:col.active_border "rgba(00FF9900) rgba(FE4761EE) 30deg"`

I also tried it isolated from the sendBatch() function call and directly called
`messageAsync('keyword general:col.active_border "rgba(00ff99ee) rgba(FE4761EE) 30deg"')` 
which gives me the same result.

Is it an error on my side or is it a bug in the communication handling with hyprland?

**Comment by Aylur** [comment]
The parameter passed to the message method just sends the string as is through the socket to hyprland and its parsing is done on their side
Maybe try without the quotes, otherwise ask on a hyprland how you could dispatch this through the socket.
If all else fails, you could `execAsync("hyprctl")` as a fallback
