### ISSUE TITLE
[Question v2] Running JS from CLI / Intercept widget props changes

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/ags#588]
Hello, 
I am trying to make a popup window with a background window containing an eventbox. Previously I used a custom function that toggles the background window and after the popup, I added it to the global scope and ran it with “ags --run-js”. So the question is, is there any way to call functions in ags v2 from cli or intercept variable from code to show background window before toggling popup?

**Comment by Aylur** [comment]
https://aylur.github.io/astal/guide/ags/cli-app#messaging-from-cli
