### ISSUE TITLE
ags v2: home manager systemd service running invalid command

### ISSUE THREAD

**Issue by matteo4375** [Aylur/ags#592]
the systemd service runs `ags -b hypr` which on ags v2 will bundle the config instead of running it

https://github.com/Aylur/ags/blob/cd543afec4d9ed708990e5ba52184716809bf248/nix/hm-module.nix#L90

**Comment by Aylur** [comment]
oh oops, I did not pay enough attention from that PR either, it should not have a hardcoded bus name on v1 either
