### ISSUE TITLE
mpris player duplicates

### ISSUE THREAD

**Issue by themvl** [Aylur/ags#593]
using this code in a module, i get duplicates of mpris players. They dont exist on my system checking with playerctl. Youtube on chrome appears 3 times and strawberry and youtube on firefox appear 2 times. 
I have looked everywhere i cant seem to find the issue so maybe there is a issue with the service?

```ts
import {mpris} from 'resource:///com/github/Aylur/ags/service/mpris.js'

const Player = player => Widget.Button({
    onClicked: () => player.playPause(),
    child: Widget.Label().hook(player, label => {
        const { track_title } = player;
        label.label = `${track_title}`;
        label.truncate = "end";
    }),
})


export function Music() {
    return Widget.Box({
        className: "widget music",
        children: mpris.bind('players').as(p => p.map(Player))
    })
}
```

**Comment by themvl** [comment]
this also happens with the media-widget example run directly

**Comment by Aylur** [comment]
playerctl might expose an mpris interface itself

you can check the full list of available players through dbus
```sh
dbus-send --session \
    --dest=org.freedesktop.DBus \
    --type=method_call \
    --print-reply \
    /org/freedesktop/DBus org.freedesktop.DBus.ListNames \
    | grep string \
    | cut -d '"' -f 2 \
    | grep org.mpris.MediaPlayer2
```

**Comment by themvl** [comment]
it turned out to be playerctl daemon that i started in my hyprland config. Maybe this should be added in the mpris wiki. To warn future users that the playerctl daemon can add duplicate mpris players.

**Comment by utkarsh-20-rajput** [comment]
> it turned out to be playerctl daemon that i started in my hyprland config. Maybe this should be added in the mpris wiki. To warn future users that the playerctl daemon can add duplicate mpris players.

what was the solution? I'm new to all this so was unable to solve this

**Comment by themvl** [comment]
you dont start playerctl deamon i removed the line in the hyprland config that starts it... this introduces a new thing where it no longer remembers the last one playing so shortcuts for example that you use with playerctl deamon (like skip play pause...) no longer work in that way.
