### ISSUE TITLE
Trouble Installing Ags

### ISSUE THREAD

**Issue by TryingToBeHooman** [Aylur/ags#599]
I always get this whenever i try installing ags with yay

:: PGP keys need importing:
 -> 50F91FB550EC32AB4A710286FA148B892AB48044, required by: sdl2_sound
:: Import? [Y/n] y
:: Importing keys with gpg...
gpg: keyserver receive failed: No data

**Comment by zielOS** [comment]
That's not really an ags issue. It's more of an arch and yay issue,  and a very common one. What command with yay did u issue @TryingToBeHooman ?

**Comment by kotontrion** [comment]
You most likely tried to install the wrong package.
The AUR package is not called ags, that name was already taken by adventure game studio. The package is called aylurs-gtk-shell.

**Comment by TryingToBeHooman** [comment]
> You most likely tried to install the wrong package. The AUR package is not called ags, that name was already taken by adventure game studio. The package is called aylurs-gtk-shell.

it worked tysm im so dumb
