### ISSUE TITLE
Any chances of adopting a different name?

### ISSUE THREAD

**Issue by iErik** [Aylur/ags#60]
This might sound very silly and I guess understandably so but is there any possibility that the project might go under a different name? ags makes it difficult to find it and really just doesn't give any idea what it is about upfront, plus it conflicts with another project that is apparently meant to be a game engine

**Comment by Aylur** [comment]
I mean so does Eww, but I agree, I really should have checked the AUR for this name, not just nixpkgs. Wouldn't it be even more confusing if I changed it now?

**Comment by iErik** [comment]
I also don't think Eww has great naming either, but for some reason it ends up working okay for them, maybe because "eww" is also play on words so it's not as lost in memory as much as "ags", if that makes any sense? But as for the question if whether or not it would be more confusing, I don't think so, the project is still quite small for now and there's still aren't that many people that know about it, so in my view that would be an appropriate time to make such change, I believe it's not even packaged yet in any major distros, right?

I do really like the project though and I think it has a lot of potential, I really just wish it would be easier to find it through google or in the AUR xDD I could help with name suggestions if you, but obviously that's a decision that's ultimately up to you. Since it seems popular among users of Hyprland we could think of something along these lines? Maybe hyprshell, hyprwidgets or hypereww, idk xD

**Comment by kotontrion** [comment]
IMO the name ags is fine. It's unfortunate there is already an project with that name in the AUR.
It will be easier to find as time goes on and more people get interested in regardless if the name is changed or not. I'm using it for about two weeks now and it did already get noticeable better.

But if you decide to change to name, here are two suggestions that came to my mind:
JavaScript Widget Library - jwl or jewel
Gtk Layouts - glay
both of them are available in the AUR.

**Comment by Aylur** [comment]
I don't think major distros will ever package it, so my only concern is the AUR and nixpkgs. It may confuse some users if they see ags packaged only to realize its the game engine with the same name. I think I will keep this name in hope that most users will read the wiki on how to install and not confuse the two, but I am open for another name, I admit I did a poor job of this.
I would rather not have hypr in the name, people would think its something Hyprland specific.

**Comment by iErik** [comment]
I think most of us are bad with names, and I see the point of not wanting to be seen as something specific to Hyprland, so that's fair, I just really got frustrated trying to find it because all the information I could find by typing "ags" on search engines and the AUR was about the game engine, to the point where I started wondering if people were using that to build shell components, I could only find the project after searching for a while on Reddit to see the post where someone mentioned it. One could argue that it is because the project is still small, but there are other small projects such as RagnarWM which are easier to remember and find if u need to take a look at the documentation, github repo or the package in some distro's repository

**Comment by Aylur** [comment]
I always search `<program> github` for this reason. On google right now this repo is the third link when searching for `ags github` and second on `ags widgets`. Turns out there is also a repo called ags-widgets which is also a typescript project. This name is really unfortunate, but I think that if you search for any abbreviation you will never get what you want anyway. I am really tempted to rename, but I am positive that in a few months searching for `ags <some-keyword>` will have this repo as the first result.

**Comment by cenunix** [comment]
my 2 cents, the name should probably change, as you mentioned in this comment above mine. There are tons of conflicting projects which make it annoying to find specific material/documentation. If you think about the project going forward, there will probably be plenty of posts on reddit or other forums mentioning ags. If the name is more clear and unique discovery of the project will be better. Even something like aylur-shell would be so easy to search for, not just using a search engine, but reddit, searching through text in a discord chat, etc etc. The sooner it changes the better the search discovery will be.

**Comment by Aylur** [comment]
I think I will keep the name, it's just a matter of finding this repo, an I have seen a number of conversations on github that went
- it's ags
- what's ags
- aylurs gtk shell

And since the aur package is spelled out I think it's fine. I admit something more unique would have been better like aylurs-shell, but at this point I think I'll keep it.

**Comment by AdsonCicilioti** [comment]
> aylurs-shell,

LGTM!

**Comment by DaniD3v** [comment]
> I think I will keep the name, it's just a matter of finding this repo. I have seen a number of conversations on Discord that went
> 
> > - it's ags
> > - what's ags
> > - aylurs gtk shell
> 
> And since the aur package is spelled out I think it's fine. I admit something more unique would have been better like aylurs-shell, but at this point I think I'll keep it.

I just wanted to mention that I first stumbled upon this project 2 months ago on r/unixporn, searched it up because I wanted to use it, found the other ags and forgot about it for ... well 2 months. The only reason I eventually found this github is that some reddit user posted a link.

I think a new name would definitely be a good decision and AUR name changes only take about a day. Did it for my package once.

**Comment by Aylur** [comment]
I do plan on having a different name for the gtk4 version to differentiate the two versions even more. Someone suggested `Aylur's Wayland Widgets` - `AWW`, which I like a lot, I think I'll go with that, but I am open to more suggestions. A one word name like how other libraries have would be cool, but I can't come up with one.

**Comment by 42Willow** [comment]
> I do plan on having a different name for the gtk4 version to differentiate the two versions even more. Someone suggested `Aylur's Wayland Widgets` - `AWW`, which I like a lot, I think I'll go with that, but I am open to more suggestions. A one word name like how other libraries have would be cool, but I can't come up with one.

That's a great name! Quick noob question (I know which is off-topic but I don't know where else to ask).

Will there be any differences in terms of code with the GTK4 version? Is there any ETA? (I'm thinking of learning how to use AGS/AWW)

**Comment by SystematicError** [comment]
> I do plan on having a different name for the gtk4 version to differentiate the two versions even more. Someone suggested `Aylur's Wayland Widgets` - `AWW`, which I like a lot, I think I'll go with that, but I am open to more suggestions. A one word name like how other libraries have would be cool, but I can't come up with one.

I like the name and acronym! Although wouldn't the name be conflicting if an X11 backend was added?
