### ISSUE TITLE
Not working on Gnome 47.1

### ISSUE THREAD

**Issue by Pocitanoide** [Aylur/ags#601]
As i saw, it looks like the problem its not ags itself, its because of ags uses "Layer Shell" which not supports Gnome on Wayland. If can't be fixed, could be nice to make it clear. Thanks! Here is my console output:

** (com.github.Aylur.ags:50514): WARNING **: 17:42:09.517: It appears your Wayland compositor does not support the Layer Shell protocol

** (com.github.Aylur.ags:50514): CRITICAL **: 17:42:09.517: layer_surface_new: assertion 'gtk_wayland_get_layer_shell_global ()' failed

** (com.github.Aylur.ags:50514): WARNING **: 17:42:09.517: Falling back to XDG shell instead of Layer Shell (surface should appear but layer features will not work)

** (com.github.Aylur.ags:50514): CRITICAL **: 17:42:09.517: Custom wayland shell surface is not a layer surface, your Wayland compositor may not support Layer Shell

**Comment by Aylur** [comment]
Its the other way around: Gnome does not support the layer shell protocol and they probably never will. If you want to write custom widgets on Gnome look into [gnome extensions](https://gjs.guide/extensions/)
