### ISSUE TITLE
AGS hangs/crashes when a notification occurs while a video is playing in firefox.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [Aylur/ags#605]
If you have a notification that occurs while playing a video in firefox (ex: youtube), AGS will freeze along with firefox.

## Steps to reproduce
1. https://jsitor.com/vGOi-h09sc go to this sandbox made for sending notifications
2. https://www.youtube.com/watch?v=No28L4O-T_Y&t=4742s start playing this video
3. On the `jsitor` sandbox, spam the 'Notify me!' button

Notice that Firefox and AGS both freeze and you have to kill AGS and firefox to proceed. I have tried this with https://github.com/Aylur/dotfiles and was able to replicate it.

**Comment by iMithrellas** [comment]
Hi, this has been bothering me for some time, randomly a notification freezes AGS and a firefox instance. I have to "pkill ags" and start it again to resolve the issue.
