### ISSUE TITLE
How can I use SCSS on my AGS config instead of base CSS?

### ISSUE THREAD

**Issue by Alanzcc** [Aylur/ags#609]
I'm trying to style my AGS bar with SCSS, but simply changing where it receives the styles from and the file type isn't enough

**Comment by Aylur** [comment]
- [v1](https://aylur.github.io/ags-docs/config/theming/#using-pre-processors-like-scss)
- [v2](https://aylur.github.io/astal/guide/typescript/theming#using-scss)
