### ISSUE TITLE
run-js parameter output

### ISSUE THREAD

**Issue by kotontrion** [Aylur/ags#61]
Currently the run-js parameter does not output anything. It would be a great addition to change that. Then it would be possible to access some internal ags services and variables from external scripts, which could be quite useful.

**Comment by Aylur** [comment]
I couldn't find a way to redirect stdout and I am not even sure if its possible, but having the run-js function return something, sending it through dbus and printing is possible.

**Comment by Aylur** [comment]
Issue with this is that while a run-js proccess is running another one can't be run.

**Comment by kotontrion** [comment]
I just looked at it. Couldn't this be overcome, if the client registers random name on the bus? This name would then either be fetched in ags (can you access the busname of the caller of an action? idk) or it has to be a second parameter.

**Comment by Aylur** [comment]
The bus name will have to be passed on dbus too.
I also found it to have a small delay even on just
```bash
ags run-js "ags.Service.Mpris.getPlayer()?.name"
```

Maybe it would be better to drop async support and just use a simple dbus call that will return a string
