### ISSUE TITLE
Build fails off AUR and git

### ISSUE THREAD

**Issue by Robert4S** [Aylur/ags#612]
The build fails when building GUtils. From what I have read so far, my distutils is probably on an incorrect version, but nowhere in the build or docs seems to specify the correct version. Error:

`
FAILED: subprojects/gutils/GUtils-1.0.gir 
env PKG_CONFIG_PATH=/home/robert/.cache/yay/aylurs-gtk-shell/src/ags/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=GUtils --nsversion=1.0 --warn-all --output subprojects/gutils/GUtils-1.0.gir -I/home/robert/.cache/yay/aylurs-gtk-shell/src/ags/subprojects/gutils -I/home/robert/.cache/yay/aylurs-gtk-shell/src/ags/build/subprojects/gutils --filelist=/home/robert/.cache/yay/aylurs-gtk-shell/src/ags/build/subprojects/gutils/libgutils.so.p/GUtils_1.0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --symbol-prefix=gutils --identifier-prefix=GUtils --cflags-begin -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/security -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/robert/.cache/yay/aylurs-gtk-shell/src/ags/build/subprojects/gutils --library gutils -lgobject-2.0 -lglib-2.0 -lgio-2.0 -lpam -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 25, in <module>
    from .ccompiler import CCompiler
  File "/usr/lib/gobject-introspection/giscanner/ccompiler.py", line 29, in <module>
    from distutils.msvccompiler import MSVCCompiler
ModuleNotFoundError: No module named 'distutils.msvccompiler'
`

**Comment by Robert4S** [comment]
Is it possible to know why this was closed? It seems distutils.msvccompiler was deprecated over 2 years ago, and I could only get ags to build by removing the imports myself and creating a mock MSVCCompiler class with the same name as the one imported.

**Comment by Aylur** [comment]
https://github.com/Aylur/ags/pull/504

**Comment by kotontrion** [comment]
also see #554
