### ISSUE TITLE
Moving over from ags v1?

### ISSUE THREAD

**Issue by dtomvan** [Aylur/ags#618]
I have a question: how would one go about moving their config over to ags v2? Or do I need to basically refactor everything by hand? My nix updated to ags 2.0 and now I need to move over or rollback. I'd like to move my existing config.js to the new system, but I can't just call `ags run` sadly, because it expects jsx instead of normal js which defines GTK widgets...

**Comment by kurtbahartr** [comment]
I have the exact same question before AGS is updated to v2 on the AUR. I don't to lose my entire desktop, which I worked day and night just to get it to be the way I and a friend of mine are comfortable with recently, just because there's basically no documentation as to porting it.

Aylur and other AGS and Astal devs- How about making a porting guide like how Hyprland does it *before releasing a new build*? I'm sure it would be a breeze not just for other users but also you all too especially when there's just possible too much to port over.

**Comment by kotontrion** [comment]
there were so many breaking changes. You will have to change basically every part in your config.

I recommend starting from scratch and use jsx.

The aur packages were already updates to v2. If you don't want to migrate yet, you can hold that package, so it won't get updated. I also made a [pkgbuild](https://github.com/kotontrion/PKGBUILDS/blob/main/agsv1/PKGBUILD) which installs the latest version before v2 with a different name (agsv1) so you can use both version at the same time, which is useful for migrating.

**Comment by kurtbahartr** [comment]
> there were so many breaking changes. You will have to change basically every part in your config.
> 
> I recommend starting from scratch and use jsx.

Then it's about time that I start reading the documentation this summer. :P

> The aur packages were already updates to v2. If you don't want to migrate yet, you can hold that package, so it won't get updated. I also made a [pkgbuild](https://github.com/kotontrion/PKGBUILDS/blob/main/agsv1/PKGBUILD) which installs the latest version before v2 with a different name (agsv1) so you can use both version at the same time, which is useful for migrating.

The first two sentences got me scared but then reading the next one made me give out a sigh of relief out loud! Thanks a lot for thinking that part! I should configure Diana's dotfiles to use that and let her know about this for the time being.

**Comment by dtomvan** [comment]
@kotontrion Thank you, that clarifies it for me. I guess I'll slowly migrate while keeping ags v1. I'll write a nix drv for it. If anyone (or this repo's flake) needs it, I'd be happy to help!

Sorry for the rushed issue description. I couldn't rebuild my home-manager config after the update, because `agsNoTypes` didn't exist anymore...

**Comment by kurtbahartr** [comment]
@dtomvan so, you planning to close this issue or..?

**Comment by dtomvan** [comment]
I can't convert it to a discussion, but if I could I would do that instead. Because I think people might want to discuss the v1->v2 migration... But there's no bug or problem to be discussed, so I guess this shouldn't be an open issue either.

**Comment by dtomvan** [comment]
Nevermind, there is also a discussion: https://github.com/Aylur/ags/discussions/615#discussion-7481707

This'll be a dup.
