### ISSUE TITLE
mpris service/dbus issue after system has been up a while

### ISSUE THREAD

**Issue by ferrreo** [Aylur/ags#62]
If I restart ags after my system has been up for over 12 hours or so I get this error from the mpris service:

![image](https://github.com/Aylur/ags/assets/482133/ff6fad6f-1cb0-464f-9ea7-a1a99386bfda)

The mpris service at this point also no longer works no matter the restarting of players etc I do I have to reboot to get it working again.

Playerctl is still working as normal as are anything else I have that interacts with mpris.
I'm guessing if I used them any other service that does ListNamesRemote would also start failing.

At a loss here as I can't see anything wrong in ags and everything else on my system using dbus seems to be working fine.

**Comment by Aylur** [comment]
Weird, I yanked that part of the code directly from gnome. Did this happen multiple times?

**Comment by ferrreo** [comment]
Yeah 3 or 4 times so far. Never seen it have a problem until I've quit and restarted ags though.

**Comment by cpiscos** [comment]
I get this issue as well showing this error in console:
```
(com.github.Aylur.ags:118582): Gjs-WARNING **: 03:57:58.371: JS ERROR: TypeError: (intermediate value).config is undefined
_cacheCoverArt@resource:///com/github/Aylur/ags/service/mpris.js:138:13
_updateState@resource:///com/github/Aylur/ags/service/mpris.js:134:14
_onPlayerProxyReady@resource:///com/github/Aylur/ags/service/mpris.js:105:14
MprisPlayer@resource:///com/github/Aylur/ags/service/mpris.js:85:14
_addPlayer@resource:///com/github/Aylur/ags/service/mpris.js:226:24
_onProxyReady@resource:///com/github/Aylur/ags/service/mpris.js:247:22
async*wrapper/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:251:36
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by jostal** [comment]
> I get this issue as well showing this error in console:
> 
> ```
> (com.github.Aylur.ags:118582): Gjs-WARNING **: 03:57:58.371: JS ERROR: TypeError: (intermediate value).config is undefined
> _cacheCoverArt@resource:///com/github/Aylur/ags/service/mpris.js:138:13
> _updateState@resource:///com/github/Aylur/ags/service/mpris.js:134:14
> _onPlayerProxyReady@resource:///com/github/Aylur/ags/service/mpris.js:105:14
> MprisPlayer@resource:///com/github/Aylur/ags/service/mpris.js:85:14
> _addPlayer@resource:///com/github/Aylur/ags/service/mpris.js:226:24
> _onProxyReady@resource:///com/github/Aylur/ags/service/mpris.js:247:22
> async*wrapper/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:251:36
> _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
> ```
> 
> I've noticed it also happens with rerunning after terminating with ags -q.

I'm getting the same error. I think it's only happening when I already have some audio running though and then try to launch ags. If nothing is open then ags starts fine and then I can open Spotify/YouTube or whatever else.

**Comment by Aylur** [comment]
This error usually shows up when you have another unrelated error in your config. I couldn't figure out why this shows up instead of a stack yet
