### ISSUE TITLE
Runtime Dependencies

### ISSUE THREAD

**Issue by ojaskavathe** [Aylur/ags#622]
Is there a way to add runtime dependencies to ags through nix? I understand `programs.ags.extraPackages` in the home-manager module lets you add packages to the gjs runtime, but about ags itself?

If I want to run a python script through `exec` on a button, but don't want to expose the python package in `home.packages`, is there a way to add it to the runtime dependencies of ags?

I'm a bit new to nix, apologies for the query.

**Comment by Aylur** [comment]
<https://aylur.github.io/ags/guide/nix.html#bundle-and-devshell>
`extraPackages` you pass to the derivation can also include binaries
```nix
ags.packages.${system}.default.overrideAttrs { 
  extraPackages = [
    pkgs.python3
  ];
}
```

**Comment by Aylur** [comment]
I am not sure why its not working in a devshell
```nix
packages.${system}.default = ags.lib.bundle {
  extraPackages = [
    pkgs.python3 # works
  ];
};

devShells.${system} = {
  default = pkgs.mkShell {
    buildInputs = [
      (ags.packages.${system}.default.overrideAttrs {
        extraPackages = [
          pkgs.python3 # does not work
        ];
      })
      pkgs.python3 # just put it here while developig
    ];
  };
};
```

**Comment by ojaskavathe** [comment]
That fixes it in the devShell, thank you. And bundling the application works as expected through `nix run`.

I also meant to ask how I could call ags in something like a `hyprland.conf` if I have it configured through home-manager. Is there a way to bundle the application through home-manager or through the nixOS system flake?

I tried
```nix
programs.ags = let
  ags-with-python = inputs.ags.packages."x86_64".default.overrideAttrs {
    extraPackages = [
      pkgs.python3 # doesn't work
    ];
  };
in {
  enable = true;
  configDir = ./ags;
  package = ags-with-python; 

  extraPackages = with pkgs; [
    python3 # doesn't work either
  ];
};
```

They all spit out the same error as before.

**Comment by ojaskavathe** [comment]
I suspect the reason it's not working in a devShell is that the wrapper isn't working properly?
```nix
preFixup = ''
  gappsWrapperArgs+=(
    --prefix NIX_GI_DIRS : "$(${datadirs})" # is something wrong here?
    --prefix PATH : "${lib.makeBinPath (bins ++ extraPackages)}"
  )
'';
```
Because the (almost) same wrapper works with the bundler:
```nix
preFixup = ''
  gappsWrapperArgs+=(
    --prefix PATH : ${with pkgs;
    lib.makeBinPath (extraPackages
      ++ [
        dart-sass
        fzf
        gtk3
      ])}
  )
'';
```
