### ISSUE TITLE
Hyprland focusedWorkspace binding not functioning as expected

### ISSUE THREAD

**Issue by Sem1Rose** [Aylur/ags#627]
So, I'm migrating my configs from Eww to ags v2, and i'm trying to make a simple workspace widget using this bit of code:
``` JSX
const hl = AstalHyprland.Hyprland.get_default();
const default_widget = <box className={"widget workspaces"} />;
let widget: Binding<JSX.Element>;

export function Workspaces() {
	if (hl == null) return widget;

	return (
		<box className={"widget workspaces"}>
			{bind(hl, "focusedWorkspace").as((_) => Handle())}
		</box>
	);
}

function Handle() {
	if (hl == null) return default_widget;

	let workspaces: [id: number, focused: boolean][] = [];

	hl.get_workspaces().map((x) =>
		workspaces.push([x.id, x.id == hl.get_focused_workspace().id])
	);
	workspaces.sort((a, b) => a[0] - b[0]);

	return workspaces.map(([id, focused]) => (
		<eventbox
			cursor={"pointer"}
			onClick={() => hl.dispatch("workspace", id.toString())}
			className={focused ? "workspace active" : "workspace inactive"}
		>
			<label
				label={
					id <= workspace_symbols.length
						? workspace_symbols[id - 1]
						: "O"
				}
			/>
		</eventbox>
	));
}
```
And it might be because of my illiteracy in essentially anything JS, but the widget only update once on startup, and after that it doesn't update the currently focused workspace at all. It partially works when binding `workspaces` instead of `focusedWorkspace`, but it only updates when a pinned window is focused.

**Comment by 44mira** [comment]
This is how I have my workspaces box setup:

```tsx
    <box spacing={6} className="workspaces">
      {bind(hypr, "workspaces").as((workspaces) =>
        workspaces
          .sort((a, b) => a.id - b.id)
          .map((ws) => (
            <button
              cursor="pointer"
              onClick={() => hypr.dispatch("workspace", ws.id.toString())}
              className={bind(hypr, "focusedWorkspace").as((active) =>
                ws == active ? "focused-workspace" : "",
              )}
            >
              {ws.id}
            </button>
          )),
      )}
    </box>

```

I believe something went wrong with your bindings.

**Comment by 44mira** [comment]
I just noticed you're managing state without `Variable` too. You can refer to [First Widgets#State Management](https://aylur.github.io/astal/guide/typescript/first-widgets#state-management) or [Variable](https://aylur.github.io/astal/guide/typescript/variable) sections in the docs for more information.

```tsx
let workspaces: [id: number, focused: boolean][] = [];

	hl.get_workspaces().map((x) =>
		workspaces.push([x.id, x.id == hl.get_focused_workspace().id])
	);
	workspaces.sort((a, b) => a[0] - b[0]);
```

Moreover, as you can probably infer from my codeblock above: `AstalHyprland.Hyprland` has a property [`workspaces`](https://aylur.github.io/libastal/hyprland/property.Hyprland.workspaces.html) which already does what you were trying to do + signals.

**Comment by Sem1Rose** [comment]
> This is how I have my workspaces box setup:

tysm, this works like a charm!

> Moreover, as you can probably infer from my codeblock above: `AstalHyprland.Hyprland` has a property [`workspaces`](https://aylur.github.io/libastal/hyprland/property.Hyprland.workspaces.html) which already does what you were trying to do + signals.

Yeah i'm aware. This snippet is what remains of a version of the code where i tried to show all the workspaces, even the empty ones, and i think i forgot to switch back to using `workspaces` again.

> I believe something went wrong with your bindings.

I should probably RTFM again because my implementation is just pathetic. I'll mark the question solved for now, thanks!

**Comment by 44mira** [comment]
If you want to show empty workspaces as well, you can try out generating the boxes using a range of numbers instead of using `workspaces`.
