### ISSUE TITLE
Does the AGS wiki have plans to provide translations into other languages?

### ISSUE THREAD

**Issue by asfuon** [Aylur/ags#640]
Hello, Aylur. I am a developer from China. I am interested in your project and hope that AGS can provide documentation in other languages.

As a native Chinese, I am willing to contribute to AGS's Chinese documentation translation. I'd like to ask for your advice.

**Comment by Aylur** [comment]
I wouldn't feel comfortable merging something as huge as a chinese translation for the wiki, but if you fork the repo and host a translated version on either github pages or wherever I would be happy to promote it and link it on both the astal and ags wiki
