### ISSUE TITLE
ags cli issue

### ISSUE THREAD

**Issue by Rkortlandt** [Aylur/ags#645]
The cli is inconsistent between ags run and ags types for specifying a custom directory 

With the types command you have to specify the directory with the -d flag proceeding you directory with the run flag the -d flag is unnecessary. 

Ex
This works
`ags run ~/some/file/path`
This does not
`ags types ~/some/file/path`
You have to run this...
`ags types -d ~/some/file/path`

**Comment by Aylur** [comment]
This is intended

- the positional parameter of `run` accepts a typescript file or using `-d` a directory can be given
- the positional parameter of `types` is a pattern to look for libraries and with `-d` a target directory can be given
