### ISSUE TITLE
process name

### ISSUE THREAD

**Issue by benthejack-vuw** [Aylur/ags#65]
Currently the ags process is under gjs (makes sense given it's a gjs project) but is it possible to rename it? (not sure about this - fairly new to linux development)

If there is another instance of gjs using killall etc will kill those processes also. It is also not so obvious, and would be nice to be able to pkill or killall ags

**Comment by Aylur** [comment]
The process name should be the same as the binary's name. You should be using `ags --quit --bus-name <name>`
