### ISSUE TITLE
Lacking examples and documentation for AGS2

### ISSUE THREAD

**Issue by Rabcor** [Aylur/ags#650]
I've been wanting to make something cool with AGS, like a fully functional taskbar/panel, and some accompanying widgets, like popups to show battery information, control brightness, volume controls, and all that fun stuff, maybe a clock and some system resource monitors on the desktop itself, etc.

But I can't figure out how to do it.

Normally what I do, for instance with conky and waybar, is find someone else's working config, and modify it until it looks the way I want it to, that way I don't have to figure out every possible function on my own by browsing docs.

I searched for ags2 configs, and I searched the docs for ags2, for how to progress with a bar, like just how to set up a tray maybe, and I get nothing. Documentation says absolutely nothing about it, there is some for how it could be done in agsv1.x, but nothing for v2; and I'm not sure how to translate the v1 method to v2.

AGS is a cool piece of software, but I cannot figure out how to make anything with it, and I struggle to find up to date examples of stuff others have made with it, the only thing I could actually find was a sidebar used in the ml4w dotfiles. It's a neat example for a lot of things but it does not show me how to set up a system tray.

**Comment by pynappo** [comment]
Maybe it's confusing is that there's just a single example on the AGS site but a few more basic ones on the Astal site (the underlying framework AGS binds to) 

You can find a simple bar example at https://aylur.github.io/astal/guide/typescript/examples#typescript-examples

For finding examples on github if you search something like `astal language:TSX` there's quite a few configs.

**Comment by Aylur** [comment]
A link to the astal examples have been added to ags' example page, and smaller widget snippets have been added to the astal page.
The example on the ags site merely exists to show that you can run a typescript file without any configuration files
