### ISSUE TITLE
Accessibility for ags

### ISSUE THREAD

**Issue by cafetestrest** [Aylur/ags#66]
Hi @Aylur ,
Is there any Accessibility for ags, I'm mainly interested in a feature of moving just by using keyboard (Tab, arrows, ...) without the need of mouse?

Some examples I can come up with:
1. Power menu, should have a focus and should be able to react just by arrows on keyboard and enter to confirm.
2. Notifications should be able to be cleared one by one using keyboard.
3. Moving trough date menu by keyboard.
4. Quick Settings panel to toggle on/off and select stuff by Enter/Tab keys.

Where I see that this is working as expected is on App Launcher.

**Comment by Aylur** [comment]
You would need to make your layout accordingly to keep accessibility in mind. Buttons and other reactive elements like entries and switches gets selected automatically with the tab key for example, most of this is default behavior in gtk. You just need to make the window focusable.
