### ISSUE TITLE
Mpris cache for remote albums

### ISSUE THREAD

**Issue by zoriya** [Aylur/ags#67]
If a player use a remote url for the `mpris:artUrl` metadata, ags throws an error and does not store the album art. This can be easily reproduced by using [this youtube-music client](https://github.com/th-ch/youtube-music).

Here is an example mpris metadata:
```
youtube-music mpris:length              213000000
youtube-music mpris:artUrl              https://lh3.googleusercontent.com/AjWNrfzz6BqjRL5diZ-bPxFqGOsNk20xS6jcqoQWpNGWdch404mDWKVBkl4s9n74aLjXJWgldqm3Dc8=w544-h544-l90-rj
youtube-music xesam:title               アイドル
youtube-music xesam:url                 https://music.youtube.com/watch?v=m9SMT5ipbxk
youtube-music xesam:artist              YOASOBI
youtube-music mpris:trackid             '/'
``` 

and the resulting error:

```
(ags:1388801): Gjs-WARNING **: 20:36:41.199: JS ERROR: failed to cache /home/zoriya/.cache/ags/media/YOASOBI-アイドル: Gio.IOErrorEnum: Operation not supported
_cacheCoverArt/<@resource:///com/github/Aylur/ags/service/mpris.js:125:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

```

**Comment by ferrreo** [comment]
I'll fix this in my media cache pr.

I think it doesn't like HTTPS, I'll switch it to using curl to fetch the images or something.

**Comment by ferrreo** [comment]
Actually looking at it artUrl is coming back as empty from that app

**Comment by ferrreo** [comment]
Looks like chromium/electron does not send the artUrl by default. How are you getting it to send it?

**Comment by zoriya** [comment]
The mpris properties are set by a plugin in this app named `shortcut`. You need to enable it on the top bar to get mpris metadatas.

I forgot about that for my reproduction steps, sorry about that

**Comment by ferrreo** [comment]
@zoriya it is working for me with ags built against my PR here: https://github.com/Aylur/ags/pull/47

![image](https://github.com/Aylur/ags/assets/482133/56d1f936-57eb-48c3-8f88-bf74e7448417)

**Comment by zoriya** [comment]
Just tested your PR and it did not fix the bug

```(ags:2321721): Gjs-WARNING **: 22:07:27.729: JS ERROR: Gio.IOErrorEnum: Operation not supported
writePath/</<@resource:///com/github/Aylur/ags/service/cache.js:96:26
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

with

```
youtube-music mpris:length              313000000
youtube-music mpris:artUrl              https://lh3.googleusercontent.com/Tb1AQcEWwitpUpxyIOdr5yRhjbOMIV10d4zdwIigDGt_096TLD_k5j6APnuPNt5zVcmhfYqSD4AueR5u=w544-h544-l90-rj
youtube-music xesam:title               夜明けと蛍
youtube-music xesam:url                 https://music.youtube.com/watch?v=vcTcefDysyA
youtube-music xesam:artist              天月-あまつき-
youtube-music mpris:trackid             '/'
youtube-music xesam:album               天月が歌ってみた Vol. 1
```

**Comment by ferrreo** [comment]
Is the .cache folder in your ~ actually writable because as you can see from my screenshot it works fine with that exact app I also just tried the exact image URL you posted and it works fine also?

**Comment by ferrreo** [comment]
After reading up on possible causes of the error you need to make sure you have the http backend for gvfs installed for whatever distribution you are running.

**Comment by zoriya** [comment]
Oh wow I would have never guessed it, thanks for the help! I use nix and installed it throught the flake.nix at the root of the project, I will try to find how to add this dependency to the flake.

**Comment by zoriya** [comment]
Turns out, gvfs is exposed through dbus, so it must be installed on the host system. It actually already works on master.
Sorry for the noice and thanks for the help!
