### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by darman96** [Aylur/ags#68]
Is there a way to get key-press events on a widget?
I tried a connection with the key-press-event signal, the connection is triggered but how do I get the event data?

**Comment by Aylur** [comment]
```js
connections: [['key-press-event', (button, event) => {
  print(event) // the Gdk.Event object
}]]
```

**Comment by darman96** [comment]
Event is an empty object, `print` says it's a Gdk.Event but when I `console.log` it, it logs `{}`

**Comment by Aylur** [comment]
That's to be expected, checkout the gtk docs for it's properties

**Comment by darman96** [comment]
What do you mean? 
On the EventKey page it says that it has properties: https://docs.gtk.org/gdk3/struct.EventKey.html

**Comment by Aylur** [comment]
the event is of type Gdk.Event, not a Gdk.EventKey
