### ISSUE TITLE
How to start developing?

### ISSUE THREAD

**Issue by TangerineGameDev** [Aylur/ags#74]
I am honestly pretty weirded out, by how ags globally imports itself, disallowing any IntelliSense support... (I am new to JS)

If there is a way to get it to work, excuse my illiteracy. (I would still include, setup like that in the README...)

Thank you in advance!

(Installed from the AUR, if directory structure that matters)

**Comment by Aylur** [comment]
you can import from the resource, if you prefer that
```js
import Widget from 'resource:///com/github/Aylur/ags/widget.js';
```

but this still won't give you IntelliSense, see #39

**Comment by TangerineGameDev** [comment]
Thing is I noticed IntelliSense would work, if one would download the source code, then link to the path using import.
But that is seriously cumbersome...

I don't know if giving an explicit path, is an appropriate solution for this project, but if stuff would be inside /usr/lib/ags/services or something like that, it would theoretically allow importing and IntelliSense...

What do you think? Is there a way to code something in the current state that makes it work automatically or would one be required to have a specified directory?

**Comment by Aylur** [comment]
I am not sure if setting an explicit path would be a good idea, for example it would complicate things on nix, and importing gvc wouldn't work on every distro the same, I would rather let meson do this as most if not all gobject based projects are packed as a gresource.
It is also compiled to js so you wouldn't get type suggestions, only the prop names and on the widget functions you wouldn't even have that

**Comment by TangerineGameDev** [comment]
Pretty annoying huh…
Well then, the documentation is good anyways so it should suffice!
Thank you for this project!

I’ll watch the talks in the IntelliSense Issue if something could be worked on.
