### ISSUE TITLE
Request to Add a License to the Project

### ISSUE THREAD

**Issue by mrhyperbit** [Aylur/ags#78]
### Description
The project currently does not have a license, which can have significant implications for both the project's author and its users. A license is essential for clarifying how the project can be used, modified, and distributed, providing legal protection, and ensuring the project's long-term sustainability. 

### Why a License is Essential
1. **Legal Protection**: A license sets clear terms and conditions for the use of the project. Without a license, users may assume they have no restrictions, potentially leading to misuse or legal issues.

2. **Open Source Community**: A license encourages contributions from the open-source community. Contributors need to know how their contributions will be used and how they can use the project's code themselves.

3. **Sustainability**: A license helps ensure the long-term sustainability of the project. If the author decides to abandon it or hand it over to the community, a license guides future maintainers and contributors.

4. **User Trust**: A project with a well-defined license is more trustworthy for users and potential contributors. It provides transparency and clarity.

### Suggested License(s)
Please consider selecting an open-source license that aligns with your project's goals and intentions. Some common open-source licenses include:

- [MIT License](https://opensource.org/licenses/MIT)
- [GNU General Public License (GPL)](https://www.gnu.org/licenses/gpl-3.0.en.html)
- [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)

### Additional Resources
- [Open Source Initiative (OSI) - Choosing a License](https://opensource.org/licenses)
- [GitHub - Adding a License to a Repository](https://docs.github.com/en/get-started/quickstart/adding-a-license-to-a-repository)

Please consider adding a license to your project as soon as possible to provide clarity, protection, and foster a healthy open-source community around your work.

Thank you for your attention to this matter.

**Comment by kotontrion** [comment]
There is a license specified in the build files and some source files (it's GPL3), but I agree, that it adding a license file to github would make it clearer.
