### ISSUE TITLE
How to build in Nixos?

### ISSUE THREAD

**Issue by dongsu8142** [Aylur/ags#8]
I want to use it on Nixos, what should I do?

**Comment by Aylur** [comment]
I am not familiar with how NixOS works, can't help you, sorry

**Comment by dongsu8142** [comment]
I succeeded in bringing this to nix. https://github.com/dongsu8142/dotfiles/blob/master/overlays/ags/default.nix

**Comment by Aylur** [comment]
how does default.nix work? how could I use nix to build and run ags?
I only know `nix run` , `nix profile` etc, but I don't know how to write a flake

**Comment by dongsu8142** [comment]
If you want, I can write a flake when I have time.

**Comment by Aylur** [comment]
I would appreciate it
