### ISSUE TITLE
When i run ags command i get this error

### ISSUE THREAD

**Issue by RimazFlyil** [Aylur/ags#89]
Gjs-CRITICAL **: 12:52:56.551: JS ERROR: Error: Requiring GnomeBluetooth, version 3.0

Please help

**Comment by its-darsh** [comment]
install the `gnome-bluetooth` pkg

**Comment by RimazFlyil** [comment]
(ags:2120): Gjs-WARNING **: 14:21:09.695: JS ERROR: TypeError: option is undefined
AgsVariable@resource:///com/github/Aylur/ags/variable.js:17:13
default@resource:///com/github/Aylur/ags/variable.js:45:36
@file:///home/rimaz/.config/ags/js/bar/buttons/ColorPicker.js:10:20
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by Aylur** [comment]
You need to wriite the .js extension when importing modules

**Comment by RimazFlyil** [comment]
I have install Hyprland and downloaded your dotfiles and copied to my .config/ ags thats all i did.

**Comment by RimazFlyil** [comment]
> You need to wriite the .js extension when importing modules

how do i write the .js extension and where

**Comment by Aylur** [comment]
are you sure you have my dotfiles? I don't have a `~/.config/ags/windows` file there

**Comment by RimazFlyil** [comment]
sorry i mistaken someones dotfile with yours . 
i am getting an error "no colorpicker cache found"

**Comment by RimazFlyil** [comment]
do i need to install all the dependncies to use your .dotfile.

**Comment by Aylur** [comment]
You probably should if you plan on using it

**Comment by Aylur** [comment]
>no colorpicker cache found

You can ignore that, use the color picker once to not get that warning message

**Comment by RimazFlyil** [comment]
ok Thank you
