### ISSUE TITLE
Cant toggle windows

### ISSUE THREAD

**Issue by kidfromjupiter** [Aylur/ags#93]
Toggling windows just says "There is no window named xxxxx" where xxxxx is my window name that i set... like so,

`ags.Widget.Window({
	name: "Countdown",
	title: "Countdown",
	layer: "overlay",
	child: ags.Widget.EventBox({
		onHover: () => {
			ags.App.toggleWindow("Countdown");
			ags.Utils.timeout(500, () => {
				ags.App.toggleWindow("Countdown");
			});
		},
                ......
	}),
});`

**Comment by Aylur** [comment]
you need to pass the window in the default export in `config.js`

**Comment by kidfromjupiter** [comment]
Yeah i did that. However, i did notice that just importing it into the config.js is enough to make ags recognise it and render the widget. I didnt need to add it to the windows array

**Comment by Aylur** [comment]
mentioned it on the [wiki](https://github.com/Aylur/ags/wiki/configuration)
