### ISSUE TITLE
onHover callback function runs on toggling window

### ISSUE THREAD

**Issue by kidfromjupiter** [Aylur/ags#95]
I have a window that should hide itself when cursor hovers over it. So in an `EventBox` I defined a callback function to the onHover property. 

### Expected behaviour
Mind you, this was done in proper arrow function syntax so the property isnt referencing the function itself. In the callback, there is logic that 

1. toggles the window
2. sets a timeout for 5 seconds upon which the window should again be visible

### Actual behaviour
Window is toggled on hover as expected. But as soon as timeout runs out, the onHover function is run again, toggling  the window again. This continues in a loop

_**However, this is not the case with the same callback function in a `onPrimaryClick` property**_

### Code

```
onPrimaryClick: () => {
			print("ran click");
			if (Countdown.visible) {
			        Countdown.visible = false;
				print("ran inside click");
			}
			print("ran2 click");
			ags.Utils.timeout(5000, () => (Countdown.visible = true));
			print("ran3 click");
		},
onHover: () => {
			print("ran");
			if (Countdown.visible) {
			        Countdown.visible = false;
				print("ran inside");
			}
			print("ran2");
			ags.Utils.timeout(5000, () => (Countdown.visible = true));
			print("ran3");
		},
```
This is the code that i used to debug this. `onPrimaryClick ` works as expected. `onHover` is executed each time window is toggled

**Comment by kidfromjupiter** [comment]
This solves the issue somewhat. Now it requires two hover states to trigger the `onHover` callback. The looping issue is gone however.

**Comment by kidfromjupiter** [comment]
I found a temporary solution by setting the margin of the window to be out of viewport. something like -10000. Its a hacky workaround and i dont like it but it gets the job done. 

No fancy fadeout animations or anything though. It would be nice if I could animate it sliding out of the viewport but I don't think I could animate the window itself.  

I don't think I should close this issue till it's properly resolved though

**Comment by Aylur** [comment]
I am not sure what it is that you are trying to accomplish exactly, what is wrong with the snippet?
if the window is anchored to the side of the screen, you could also use a Revealer widget, then you wouldn't need to set the visibility on the window

**Comment by kidfromjupiter** [comment]
I have a window that displays a countdown on the top of the screen. It should always be visible but disappear when the mouse is hovered over it (otherwise that part of the screen is entirely unusable). 

```js
const Countdown = Window({
	anchor: ["top"],
	style: "background-color: rgba(0, 0, 0, 0.5); border-radius: 12px;",
	margin: 10,
	name: "Countdown",
	title: "Countdown",
	layer: "overlay",
	child: EventBox({
		onHover: () => {
			if (Countdown._block) {
				Countdown._block = false;
				return;
			}

			Countdown.visible = false;
			timeout(5000, () => {
				Countdown.visible = true;
				Countdown._block = true;
			});
		},
		child: Box({
			style: "padding: 10px;",
			vertical: true,
			children: [time, effective_time],
		}),
	}),
});
```

**Comment by kidfromjupiter** [comment]
> I am not sure what it is that you are trying to accomplish exactly, what is wrong with the snippet? if the window is anchored to the side of the screen, you could also use a Revealer widget, then you wouldn't need to set the visibility on the window

Your suggestion worked! Instead of setting `visible=false`, I used a Revealer widget like you said and it worked like a charm.
