### ISSUE TITLE
Format mismatch between Hyprland.active.client.address and Hyprland.clients[i].address

### ISSUE THREAD

**Issue by magicmn** [Aylur/ags#96]
Hyprland.active.client.address returns address without "0x" prefix.
```
{
    "client": {
        "address": "77ffbd0",
        "title": "magic@desktop-magic: ~",
        "class": "kitty"
    },
    "monitor": "DP-3",
    "workspace": {
        "id": 2,
        "name": "2"
    }
} 
```

Hyprland.clients[i].address has the adrress with "0x" prefix.
```
{
    "address": "0x79a9c60",
    "mapped": true,
    "hidden": false,
    "at": [
        2571,
        11
    ],
    "size": [
        1263,
        1418
    ],
    "workspace": {
        "id": -1337,
        "name": "Game"
    },
    "floating": false,
    "monitor": 2,
    "class": "kitty",
    "title": "magic@desktop-magic: ~",
    "initialClass": "kitty",
    "initialTitle": "bash",
    "pid": 14649,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null,
    "active": false
}
```

`hyprctl clients -j` and `hyprctl activewindow -j` both return the address in the same format with "0x" prefix.

In addition `Hyprland.getClient(Hyprland.active.client.address)` will work as a workaround. However `Hyprland.getClient(client.address)` with "0x" returns `undefined`.

**Comment by Aylur** [comment]
The reason is that the Hyprland socket events dont have the `0x`, so they get mapped without the this prefix, but `hyprctl` does, which is what the `clients[i]` returns 
Should be an easy fix, just prefixing the socket events will do the trick, `hyprctl dispatch` also needs the prefix to work so it makes sense
